### ISSUE TITLE
Jagged indexing

### ISSUE THREAD

**Issue by mverzett** [scikit-hep/uproot#103]
Dear authors,

I am storing the number of few active pixels in a jet image as array and I am reading them out as a jaggedArray. I would like then to re-build the jet as an image on the fly. I tried:

```python
imgs = np.zeros((4,3,3))
imgs[:, sample['ix'], sample['iy']] = sample['iv']
```

but of course it does not work. Here ix, iy, and iv are the x index, y index, and value of each active cell, respectively.
For this to work think I would need a simple feature addition that returns the x index for each element. Would it make sense to you to implement it? Any suggestion for a quick and elegant hack to work in the meantime? 

Thanks

**Comment by jpivarski** [comment]
I'm actively developing the awkward-array library as a more feature-rich replacement for uproot's JaggedArrays and similar things (e.g. ChunkedArrays). Because of that, I'll be pushing new features into awkward-array with the intention of getting it as soon as possible into uproot 3.0. if something is needed on a shorter timescale, I'd suggest a function that temporarily provides that feature in your local environment.

However, I don't understand what you're looking for here. What do `sample['ix']` and `sample['iy']` return? What's `sample`? What do you mean by an "x index?"

**Comment by mverzett** [comment]
Hi @jpivarski,

Indeed, sorry for the lack of explanation: 
   * ```sample['ix']``` and ```sample['iy']``` are jagged arrays of indices of the pixels active in each image (multiple images stored). E.g.:
```
>>> sample['ix']
jaggedarray([[0 1 2], [0 1 2], [0 1], [0 1 2 1]])
```
   * ```sample``` is indeed just a ```dict``` containing my data in three columns.
   * "x index" i mean the index of the first axis of each element. In the meantime I found the workaround. Assuming the same naming what I am looking for is something that I can obtain with: ```idxs = np.concatenate([i*np.ones(sample['ix'][i].shape[0]) for i in range(len(sample['ix']))]).astype(int)```
In this way I can re-build on the fly very sparse images with (same naming convention, ```iv``` is the raw value read):
```
imgs[idxs, sample['ix'], sample['iy']] = sample['iv']
```

Thanks!

**Comment by jpivarski** [comment]
I see now. This is a sparse matrix implemented in JaggedArrays. I'm not 100% sure I understand what's happening in your `concatenate`, but I think it might be what will be called a "parents" array in the new JaggedArray:

https://github.com/scikit-hep/awkward-array/blob/master/awkward/array/jagged.py#L201

For the time being, I would recommend a work-around, but I want to keep in touch to consider adding this sort of thing as a first class citizen in the new library. If your case really is based on the parents array, the implementation above would probably be faster than building it from a list comprehension. If it's not, then I'd like to stare at it longer to see what it is, if it's as fundamentally relevant as the parents array.

**Comment by jpivarski** [comment]
See #99 for an interactive tutorial of the new operations that are coming in uproot 3.0.

**Comment by mverzett** [comment]
@jpivarski thanks!

**Comment by jpivarski** [comment]
Take a look at

    https://mybinder.org/v2/gh/scikit-hep/uproot/master?filepath=binder%2Fversion-3-features.ipynb

A pre-release of uproot 3 is available, and this notebook demonstrates the new jagged array features.

**Comment by jpivarski** [comment]
Since this was asking for the above, I'll close the issue now, even though it's only in pre-release.
