### ISSUE TITLE
Conditional Importing of Entries

### ISSUE THREAD

**Issue by ewengillies** [scikit-hep/uproot#117]
Hello!  I'd just like to say that `uproot` looks like really exciting software.  I'd like to move my own tracking software for the COMET experiment from `root_numpy` to `uproot`.

One feature I appreciate in `root_numpy` is the `selection` parameter.  
```
selection : str, optional (default=None)

    Only include entries fulfilling this condition. If the condition evaluates to multiple values per tree entry (e.g. conditions on array branches) then an entry will be included if the condition evaluates to true for at least one array element.
```

I was wondering if any idioms exist for similar behavior in `uproot`.  That is to say, for a tree with branches ['a', 'b', 'c'] that are all fundamental dtypes (and not vectors),  is it possible to only import entries into a numpy array where (a < 5) and (c > 3)?

I feel like this is probably already possible using the existing code, given the extensive breadth of memory-management and iteration-through-a-tree available in `uproot`. Perhaps you already know of an idiom that can iterate through the data, only storing entries that satisfies some requirement on the components of the entry?  Maybe something like, read in block of data, check data, store good data, continue. 

If nothing comes to mind immediately, I'll look into it when I make the switch in a month or so.  Thanks for all your hard work!

**Comment by jpivarski** [comment]
I haven't implemented that because if I did, it would be the same as a user applying a selection after the fact. So for simplicity, I left it out.

By "do it yourself," I mean:

```
a, b, c = tree.arrays(["a", "b", "c"], outputtype=tuple)
b[(a < 5) & (c > 3)]
```

Some kind of `selection` parameter in uproot, if it were implemented, would be exactly that (the baskets have to be loaded regardless), and it would be hard to make it as expressive as the above. The thing I'm working on now is an equivalent of the above for jagged arrays.

The `selection` parameter in root_numpy is relevant to root_numpy because it's a TFormula passed to ROOT that tells ROOT to skip entries in a loop over entries. uproot has no such loop— it just casts basket data as arrays.

**Comment by ewengillies** [comment]
thanks for the response!  I understand that `selection` won't be directly implemented, again I don't think you even need it.  I'm just getting started with `uproot`, and it would be nice if there were something that mimicked this functionality using the existing functionality in `uproot`.

To this end, the "do it yourself" example comes to mind immediately, thanks for that answer. I was curious if you could shed some light on how to do this in a more memory-conservative way using the existing memory management tools (for dealing with large files).

I am trying to possible read in `N` baskets at a time of a possible `M` baskets, filter the data from each group of `N`, save the results I want in some container (say a list of ndarrays), then at the end of reading all `M` baskets call numpy.concatenate or something.

I'm working on this now, I'll let you know if I come up with anything.  Thanks again!

**Comment by jpivarski** [comment]
I can point you in the right direction, since uproot has specific tools for this.

The general, high-level way to control the data footprint is to use `TTreeMethods.iterate` or `uproot.iterate` (I'd link to the uproot.readthedocs.org entries if that were easy to do on my phone). By default, this walks through data in steps where all the branches you've asked for have basket boundaries at the same events (discovered with `TTreeMethods.clusters`). If the baskets don't line up or these breaks are too widely spaced, you can supply an explicit `entrysteps` parameter (an iterable of start, stop pairs or a single number of entries to skip).

If you want to get lower-level, into the baskets themselves, the `TBranchMethods` class has a lot of methods for that. `iterate_baskets` may be the most helpful. You can also get a lot of information like `numbaskets`, `basket_numitems` and `basket_numentries` (which are different if jagged), etc.

**Comment by ewengillies** [comment]
thanks!  I'll post the links below and look into them.

[uproot.iterate](http://uproot.readthedocs.io/en/latest/opening-files.html#uproot-iterate)
[TTreeMethods](http://uproot.readthedocs.io/en/latest/ttree-handling.html#uproot-tree-ttreemethods)
[TBranchMethods](http://uproot.readthedocs.io/en/latest/ttree-handling.html#uproot-tree-tbranchmethods)

**Comment by ewengillies** [comment]
also, I'm very excited to see what you do with jagged arrays.  They caused me a lot of problems when I started my work with numpy several years ago.  I'm happy to know someone is formalizing a way for them to play well with numpy.  thanks again for all your work!

**Comment by jpivarski** [comment]
Try them out here:

https://mybinder.org/v2/gh/scikit-hep/awkward-array/0.0.5?filepath=binder%2Fjagged-arrays.ipynb

**Comment by andrewjohnlowe** [comment]
Just to confirm: 

If: 
* I have a humongous ROOT file on disk
* I have limited RAM on my hardware
* I only actually need to read out a small amount of data corresponding to some kinematic selection cuts
* The data post-selection would fit in RAM, but otherwise would not

Is there any way to get my data output to a Pandas DataFrame using uproot? 

Am I constrained to use other software that requires ROOT to be installed?

Thanks!

**Comment by jpivarski** [comment]
@andrewjohnlowe Your case is covered, though it's a little different from what @ewengillies was asking for.

You can limit the size of the data to be read (or, to be read at a time) in two ways: specify branches (columns) and/or specify entry ranges (rows). You're reading into Pandas, so you can do:

```python
df = tree.pandas.df(["branch_names", "more_*"])
```

to select `"branch_names"` and anything matching `"more_*"` (glob patterns, like files in UNIX). To select entry ranges, do:

```python
df = tree.pandas.df(["branch_names", "more_*"], entrystart=1000, entrystop=2000)
```

If you need to run over all entries, but can't load them all at once, you can iterate over DataFrames (a chunk of many entries in each step):

```python
for df in tree.pandas.iterate(["branch_names", "more_*"], entrysteps=10000):
    do_something(df)
```

and if you're iterating over many files with the same TTree name and branch structure in each, do:

```python
for df in uproot.pandas.iterate(["dir1/files*.root", "dir2/files*.root"], "ttree_name", ["branch_*"], entrysteps=10000):
    do_something(df)
```

The workflow is: pick a small number of entries and develop your analysis on it, probably interactively to fix mistakes early. Then take the analysis code you've written, which assumes a DataFrame named `df`, and put it in a loop to scale up. If you need to parallelize, that's a whole other discussion with many ways to do that, but they would all involve processes acting on DataFrames named `df` (or whatever; you might need more than one DataFrame).

**Comment by andrewjohnlowe** [comment]
Thanks! Probably the last chunk of code is closest to what I want. Say I have several ROOT files, all containing a TTree with name "T", with branches that refer to jet properties: pt, px, py, pz, and so on. The data is overwhelmingly low pT jets, but I'm only really interested in the high pT jets in the tail of the pT distribution, and that's data that I can read into memory. So what I want to do is read out to pandas just those jets for which pT < 25 GeV, say. And maybe some additional cuts, like the number of tracks is greater than some value. I want a "flat ntuple". Just rows and columns. Basically, I want to do SQL-like or Femtocode-like queries and get a view of the data. At that point, I can use any tool I like for my analysis; Python, R, Julia, MatLab/Octave, ...

It seems the suggested workflow to do this within the RAM of my hardware is to grab the pT branch (perhaps iterating in chunks), apply the selection, get the indices of the rows passing the cut, and iterate over the remaining branches and keep the rows matching the indices we found earlier. But that seems a bit cumbersome and will get more complicated if I include other cuts on other branches! Any shortcuts that I've missed?

**Comment by jpivarski** [comment]
Then you are asking something similar to the original poster: you wan to select entries/rows with a cut.

You can do that, but you have to do it explicitly by reading the branches required for the cut and applying a mask. Whether `x` is a Numpy array or a Pandas DataFrame, it's

```python
y = x[cut]
```

where `cut` is some logical expression, like `df["pT"] < 25` or `(df["pT"] < 25) & (abs(df["eta"]) < 5)`.

This doesn't avoid reading and decompressing the data, and it doesn't avoid the temporary memory use to have those arrays/DataFrames in memory. There is, in fact, no way to avoid that: if we had an API like root_numpy's, which takes a cut expression in the same function that reads and returns arrays, it doesn't change the fact that all of the arrays (the ones used in the cut expression and the ones the cut is applied to) have to be read, decompressed, and loaded into memory, even if some of them are only temporarily in memory. In root_numpy, this temporary memory is in the TBufferFiles on the ROOT side.

Therefore, you just need to make your `entrysteps` small enough to do the selections with the memory you have. If these small steps limit subsequent processing, you may want to do the filtering in one pass, concatenating the small chunks into larger chunks, save the large chunks, and then do the rest of your analysis starting with the large chunks. DataFrames can be concatenated and saved to a variety of forms.

This only helps if you're filtering out a lot of the input data, like 50% or 90% or more. In database terminology, this is "repartitioning" the dataset, and it's a general feature of file-backed databases.

Given your interest in a database-like view ("SQL-like or Femtocode-like queries") of ROOT files, you might be interested in [spark-ttree](https://github.com/PerilousApricot/spark-ttree)—_it's still in development,_ but it will allow ROOT files to be the backend of a SparkSQL DataFrame, reading data as arrays (like uproot, unlike root4j). When it's ready, you can run a single-node installation of Spark on your computer and use SparkSQL's query language to access these files. SparkSQL has an automatic `repartition` function to simplify all of the above—you wouldn't have to repartition by hand, which is what it looks like you're trying to avoid.
