### ISSUE TITLE
status of ROOT writing of histograms

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/uproot#121]
We are approaching a use-case in https://github.com/diana-hep/pyhf where we would like to write ROOT files (for backwards compatibility of recreating standard XML + ROOT represenations of HistFactory from the new HistFactory JSON spec)

I saw from @sbinet the recent progress on ROOT writing in Go-HEP and was wondering what the status in python was.

https://github.com/diana-hep/pyhf/pull/218

**Comment by jpivarski** [comment]
We've been writing objects to ROOT files for a few weeks now (not if interest to physics: TObjString and bare TAxis) and were stuck of the problem of adding streamers. ROOT needs streamers for a class to read out any instances of that class, and streamers are a particularly complex thing to start with.

However, just yesterday we came up with a way to punt on the streamer problem for now and get straight to the writing of histograms: we're going to insert a superset of all streamers a physicist would need (for histograms, profile plots, and TTrees of simple types) into every file as a binary blob. This will be a few unnecessary kilobytes per file, but it lets us focus on the problem of histogram objects.

Yesterday, we quietly released version [3.0.0b1](https://pypi.org/project/uproot/#history) of uproot, which has the new (possibly buggy) jagged arrays and stubs for file writing. Code will be copied into these stubs from the development branch as a quality check. Our goal is to have histogram writing in the first production release (3.0.0 proper) before the ROOT Workshop in two weeks.

**Comment by jpivarski** [comment]
You've already seen that we released the first non-beta 3.0.0 yesterday. This has histogram-writing support. We'll be posting a laundry list of improvements, so this support will incrementally grow, rather than being presented as a big bang. Nevertheless, it exists enough to say that this issue is satisfied.
