### ISSUE TITLE
uproot not available on conda

### ISSUE THREAD

**Issue by DylanReedy** [scikit-hep/uproot#122]
Hi there,

I'm unable to run ``conda install uproot``, and I also can't locate uproot by searching on anaconda.org.

Is this some kind of problem on my end?

Thanks!

**Comment by jpivarski** [comment]
I've only put it on PyPI, and I _had_ thought that there was a way to use conda to fetch from PyPI (a special channel, perhaps?) I've been trying to do it, too, with no luck.

For PyPI packages that are not on conda, I've had luck with `conda install pip` and then pip-installing. The packages go into the miniconda3 directory, so they are in a sense managed by conda (deleting the miniconda3 directory gives you a fresh start, and I think that conda's environments keep the pip packages installed this way separate).

But the short answer is that I've only deployed to one repository: PyPI.

**Comment by DylanReedy** [comment]
pip worked - thanks guys!

**Comment by jpivarski** [comment]
I should perhaps remove references to conda.

**Comment by jpivarski** [comment]
By the way, https://anaconda.org/conda-forge/uproot

This is maintained by @chrisburr, along with ROOT itself, XRootD, and other HEP packages.
