### ISSUE TITLE
failures during install using py2.7

### ISSUE THREAD

**Issue by vkuznet** [scikit-hep/uproot#123]
HI Jim,
here is what I got on lxplus using CMSSW environment (python 2.7):
```
Extracting uproot-3.0.0b2-py2.7.egg to /afs/cern.ch/work/v/valya/RandD/uproot/install/lib/python2.7/site-packages
  File "/afs/cern.ch/work/v/valya/RandD/uproot/install/lib/python2.7/site-packages/uproot-3.0.0b2-py2.7.egg/uproot/write/file.py", line 63
    cursor.fields(self.sink, [b"root", ...])
                                       ^
SyntaxError: invalid syntax
```

Even though the build for new uproot was done I saw these type of errors. Does it means that new uproot is only python 3.X complaint?

**Comment by jpivarski** [comment]
No, it should be 100% Python 2.7 compliant, let alone not have Python 3-only syntax. I don't know how this is passing all 6 of the Python 2.7 CI tests. It's probably a deployment bug.

**Comment by jpivarski** [comment]
This was not even real code. It's been commented out.
