### ISSUE TITLE
Possible regression in TH1* fSumw2?

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/uproot#130]
```
Python 2.7.14 (default, Mar 22 2018, 15:04:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> uproot.__version__
'2.9.11'
>>> f = uproot.open("./validation/xmlimport_input/data/example.root")
>>> f.items()
[('data;1', <TH1F 'data' 0x0001111af050>), ('signal;1', <TH1F 'signal' 0x0001111af2b8>), ('background1;1', <TH1F 'background1' 0x0001111af520>), ('background2;1', <TH1F 'background2' 0x0001111af788>), ('background1_statUncert;1', <TH1F 'background1_statUncert' 0x0001111af9f0>)]
>>> f['data']
<TH1F 'data' 0x0001111afc58>
>>> f['data'].fSumw2
[]
```

and the latest release of 3.0.0

```
Python 2.7.14 (default, Mar 22 2018, 15:04:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> uproot.__version__
'3.0.0'
>>> f = uproot.open("./validation/xmlimport_input/data/example.root")
>>> f.items()
[('data;1', <TH1F 'data' 0x000114f36d60>), ('signal;1', <TH1F 'signal' 0x000114f5c0a8>), ('background1;1', <TH1F 'background1' 0x000114f5ca48>), ('background2;1', <TH1F 'background2' 0x000114f5ccb0>), ('background1_statUncert;1', <TH1F 'background1_statUncert' 0x000114f5cf18>)]
>>> f['data']
<TH1F 'data' 0x000114f671b0>
>>> f['data'].fSumw2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TH1F' object has no attribute 'fSumw2'
```

Any ideas what happened? This is affecting our tests in diana-hep/pyhf :) [We rely on `fSumw2` to determine if the errors are stored with the histogram or separately]

**Comment by lukasheinrich** [comment]
if the `fSumw2` structure is supposed to be private, it would be good to have a public API to read errors some other way

**Comment by jpivarski** [comment]
It's an underscore. Member data from ROOT are now prepended with `_` because they're supposed to be Python-private. If you've been relying on them, search for `.f` and replace with `._f` if it looks like a C++ member carried over into Python.

Sorry for the version update pains— but that's why I had to go 3.0.

**Comment by jpivarski** [comment]
That's what uproot-methods is for (also new in 3.0). If you want access to `sumw2` (I didn't know anytime was using it), we should add a property to `uproot_methods.classes.TH1.Methods` with a Pythonic name. I would have thought `sumw2` is an internal thing— "variances" would be a more user-facing name.

**Comment by jpivarski** [comment]
(You're really living at head! You noticed quickly!)

Do you want to go about it by patching your own code to include underscores, adding methods to uproot-methods, or one now, the other later?

**Comment by lukasheinrich** [comment]
@jpivarski I think we'd be fine with patching our own code for now, but a public API for errors would be nice (sth like GetBinError in root)

**Comment by kratsg** [comment]
> Do you want to go about it by patching your own code to include underscores, adding methods to uproot-methods, or one now, the other later?

I can submit a PR pretty quickly to add into your python mixin (jeez, that's a brilliant idea btw for mixins)

**Comment by jpivarski** [comment]
There's a public `values` (no underflow/overflow) and `allvalues` (with underflow/overflow). Similar properties could be named `errors` and `allerrors` (with square root) and `variances` and `allvariances` (raw `sumw2`).

**Comment by jpivarski** [comment]
@kratsg Thanks! Use the names I suggested in the uproot-methods repo and bump the micro version number. I'll only have phone access for the rest of the evening, but I can press "accept" and deploy a new release of everything's fine. (Another reason for the separate repo: quicker turn-around.)

**Comment by kratsg** [comment]
I think for now, `variances` (I'm not sure how `allvariances` versus `variances` differs because I don't think errors have overflow/underflow, but I need an example root file to check)

**Comment by jpivarski** [comment]
uproot-methods 0.0.8

**Comment by jpivarski** [comment]
Your bug report was within minutes of the 3.0 release.  :)
