### ISSUE TITLE
Script to make streamers

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot#131]
Streamers are hard-coded in uproot, covering a superset of the types of objects we can write. (We'll never write types from Python that aren't known in C++. That wouldn't be fair: there would be no C++ classes to fill, so they'd be unusable in C++. The point of writing from uproot is to subsequently use the data in C++.)

I needs to be possible to generate this hard-coded streamer list from a script. That script would only ever be used by developers.

The script should also have a way of checking streamer version numbers because we need to generate objects according to the same streamer definitions that we put into the file. This can be manual or automatic, but the more automated, the better. It only needs to be a one-time check between the code and the generated streamers, though: no need to check anything at runtime.

**Comment by reikdas** [comment]
I have been thinking about how this streamer generating script would work. 
We do not know how to incrementally add streamers yet. 
Do we want the user of the script to supply a ROOT file which has all the streamers that we want to hardcode and this script would automatically replace the hardcoded streamers in our codebase with the streamers from this new file? - Might not be the most efficient way to do this, because the user might miss out on one of the streamers that are already present.
As for version numbers, the script could match the version numbers of the streamers already in place with the new streamers in the ROOT file supplied by the user and throw an error if they don't match.

**Comment by jpivarski** [comment]
The same way the streamers were made the first time: create a ROOT file that has one of each type of object and then extract the bytes corresponding to its streamers. This has all of them as a block— no incremental merging involved (though we now know what's involved in doing that, if we need to in the future).

A useful format to output would be a Python repr string that can replace the one in uproot/write/streamers.py (or replacing this whole file). As for versions, it would be nice to output something like a JSON file to check against the versions used in TH1.py (once).

**Comment by reikdas** [comment]
Hey @jpivarski , could you take a look at this - https://github.com/scikit-hep/uproot/blob/issue131/uproot/write/streamergen.py#L49 if you get the time? It throws an UnicodeError. I have been trying to solve it for a while now without success. 

```
with open("allstreamers.root", "rb") as binary_file:
    binary_file.seek(start)
    couple_bytes = binary_file.read(streamerlen + 1)
streamers = "streamers = b\"" + couple_bytes.decode("utf-8") + "\""
```
gives the same error.

**Comment by jpivarski** [comment]
UTF-8 has a particular format: some binary sequences are invalid. There are other encodings, like Latin-1, that use all 8 bits and have no invalid sequences, but don't use that.

What you're trying to do is "escape" or "quote" the byte string so that it becomes a valid Python string. That is, all of the bytes whose value is 0 must become `'\x00'` and the bytes whose value is 1 must become `'\x01'`, but bytes like 42 may remain as `'*'` (the corresponding ASCII value). Decoding as UTF-8 or Latin-1 will _not_ do that. If you were successful in creating the `streamers` string, it would be the wrong string. If we tried to use it, it would be garbage.

Python has a quoting function; it's `repr`. For most types, `repr` creates a string that can be literally evaluated. For byte strings, it puts the "b" prefix at the beginning and adds quotation marks.

```python
streamers = "streamers = {0}".format(repr(couple_bytes))
```

If you print this string and execute it, it returns the original bytes (tested with Numpy tostring/frombuffer).

**Comment by jpivarski** [comment]
([Quoting](http://jtra.cz/stuff/lisp/sclr/quote.html) is one of the most fundamental concepts in computer science. [LISP](https://en.wikipedia.org/wiki/Lisp_(programming_language)) is special because it's a language built from only five basic forms, and quoting is one of those five.)

**Comment by jpivarski** [comment]
(And the philosophy of computability: Gödel's incompleteness theorem relies on the ability of a mathematical expression to quote another. "This sentence is false" quotes "this sentence.")

**Comment by jpivarski** [comment]
Yes, this is solved. I did a touch-up on your PR, mostly moving the files into a `dev/` directory because it's code that would only ever be run by developers, not users. This also keeps it from being deployed when someone pip installs uproot.

Thanks!
