### ISSUE TITLE
Unit tests for writing!

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot#139]
The writing feature doesn't "fully" exist until there are unit tests. There's a stub for adding unit tests, such as the ones we've been running interactively. I'll add some, you add some, and I'll find a way to put PyROOT in the Travis tests for automatically verifying that ROOT can read what we write.

**Comment by reikdas** [comment]
root_pandas seems to have a way to put PyROOT on Travis.  https://github.com/scikit-hep/root_pandas/blob/master/ci/install.sh

**Comment by jpivarski** [comment]
We can look at that, but I've also been talking with @aperloff about how he's set up CVMFS on Travis for accessing ROOT (and many other things, like CMSSW). We should probably start by using his Docker image. If that works, he knows how to customize these images and perhaps we can get one that's more streamlined to our case. Right now, Travis spends a lot more time installing software than performing tests, especially in the PyPy case, but it wouldn't have to if these things were in the image.

There's also a divide-and-conquer aspect to this: we can write tests that only run when ROOT is installed independently of getting ROOT on Travis. That's something that I can check just by checking it out in git.

By the way, I saw your two pull requests and I'll be giving them a close look and probably merging then on Monday. Thanks!

**Comment by Justin-Tan** [comment]
Hi guys, any idea when writing functionality will be implemented? Great package by the way, the ROOT-independency makes data analysis a lot more flexible.

**Comment by reikdas** [comment]
@Justin-Tan We can already write ROOT files with TH1s (and TObjStrings). We plan to add support for TH2, TH3 and TProfile soon.

**Comment by jpivarski** [comment]
I said it doesn't "fully" exist in that sense that if it isn't tested, it's not trustworthy. But you can currently write files with uproot. Instead of opening a file with `uproot.open`, open it with `uproot.recreate` (create a file or overwrite it if it doesn't exist). Then this dict-like object can be used for assignment:

```python
file = uproot.recreate("filename.root")
file["histogram_name"] = histogram
```

Currently, only histograms can be written, though those histograms can be in a variety of formats (e.g. what you get from extracting a histogram from ROOT, what you get from `numpy.histogram`, a Pandas DataFrame with an interval index, Physt histograms, etc.).

Writing TTrees is a separate topic and could be 6 months away, if that's what you're asking.

**Comment by reikdas** [comment]
Should we close this? 
We have tests for all (working) features that were implemented. (The other tests will come in with the fixes for the pending issues.)

**Comment by jpivarski** [comment]
Yes, that's right.

**Comment by jpivarski** [comment]
Thanks!
