### ISSUE TITLE
Test Jupyter Notebooks in papermill

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/uproot#150]
The Jupyter notebooks should all be run in the CI with papermill to make sure that active development doesn't break documentation.

`pyhf` does this, so for reference see the [notebook tests that we have for `pyhf`](https://github.com/diana-hep/pyhf/blob/master/tests/test_notebooks.py).

**Comment by jpivarski** [comment]
I see, so papermill would become a `tests_require`. I'm fine with that. We'll soon be adding ROOT in the testing suite (#139), so uproot tests are about to get a lot slower. Updating uproot will become a thing we want to do less often. But that's exactly why uproot-methods was split out, because that's the part that users are likely to want to contribute to.

**Comment by matthewfeickert** [comment]
@jpivarski Would you be against me writing the tests for this in pytest instead of unittest? I find pytest way easier and versatile, and I already have generic notebook tests written in pytest + papermill.

**Comment by jpivarski** [comment]
Uhhhh... I'll have to look into pytest. I like using vanilla components and don't have unusual testing needs... until this notebook testing came up as a possibility. If it looks like it would rock the boat too much to switch from unittest to pytest, then maybe we can skip this change. (I don't want to force you to go through a major translation effort, just as I wouldn't want to go through one from unittest to pytest.)

I'll take a look.

**Comment by matthewfeickert** [comment]
I think they would be easy in any framework, so I could always just write this test in `unittest` to get them in and then later I can make a case to you on why pytest is awesome and should be used over unittest.

**Comment by jpivarski** [comment]
I've closed the PR for this, but I'm leaving the issue open because you intend to get back to it someday.

**Comment by jpivarski** [comment]
Moving forward, I'm using JupyterBooks for notebook-style documentation, which evaluate on generation (when written in Jupytext). So an extra step won't be required.
