### ISSUE TITLE
Support IPython completion 

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uproot#151]
IPython supports key completion in dictionary like objects. In order to support it, a list of possible key completions should be returned from `_ipython_key_completions_()`. If you manually hack this in a notebook:

```python
d.__class__._ipython_key_completions_ = lambda x: [x.decode() for x in x.keys()]
```

Then type:

```python
d[
```

Then press tab, you'll get `'HitStrips;1'` as a possible completion (in my case, `d` is a `TDirectory`). The ";1" could also be stripped on directories, as it's not needed as a key.

It would be nice if all dictionary-like classes supported this method in uproot.

Edit: My usage of decode in the hack is Python 3.

**Comment by jpivarski** [comment]
Fixed by #152 in uproot version 3.2.1.
