### ISSUE TITLE
Filtering pandas df

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uproot#156]
Currently, there's only one option for reading pandas DataFrames from TTrees that have JaggedArrays: `flatten=True`. However, another use case would be to have a simple way to filter JaggedArrays out.

Currently, this looks like:

```python
good_keys = [key for key in t.keys() if not isinstance(t[key].interpretation, uproot.asjagged)]
t.pandas.df(good_keys, ...)
```

This might be useful in the function call instead. Ideas: `filter=True`, `filter_jagged=True` ,`flatten=None`, `flatten='filter'`, or `jagged='filter'` (`jagged='flatten'` or `multi-index` being another policy) are some ideas.

(This is because I'm dealing with everything-but-the-kitchen-sink NTuples...)

**Comment by jpivarski** [comment]
Actually, this is broader than the DataFrame interface: it affects the set of branches that are loaded if none are specified. The `branches` parameter [already takes a number of options](https://uproot.readthedocs.io/en/latest/ttree-handling.html#arrays), one of which is a function from branch (object) to interpretation or None. You can right now do something like

```python
t.pandas.df(lambda b: b.interpretation if not isinstance(b.interpretation, uproot.asjagged) else None)
```

though this is far from obvious. Maybe there should be a shorthand object that the `branches` parameter understands to define such policies in a more user-friendly way? One I can think of: suppose any Interpretation class object like `asdtype` is taken as

```python
lambda b: b.interpretation if isinstance(b.interpretation, asdtype) else None
```

But then, you want the _inverse_ of `asjagged`.

**Comment by henryiii** [comment]
I did notice that it took a function, but I haven't taught my students lambda functions and I have taught them comprehensions, so that's why I structured my example that way.

However, `.df` already has a parameter that is designed for jagged arrays. What about having flatten take True (Current behavior), False (new: filter out jagged arrays), and None (the default, current behavior, crash)

**Comment by henryiii** [comment]
Sorry, the default is jagged=True, and the crash is not because it's not trying to flatten, it's because:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-2689fd22c539> in <module>()
----> 1 df = t.pandas.df(entrystop=100_000)

~/.local/lib/python3.6/site-packages/uproot/_connect/to_pandas.py in df(self, branches, namedecode, entrystart, entrystop, flatten, cache, basketcache, keycache, executor, blocking)
     37     def df(self, branches=None, namedecode="utf-8", entrystart=None, entrystop=None, flatten=True, cache=None, basketcache=None, keycache=None, executor=None, blocking=True):
     38         import pandas
---> 39         return self._tree.arrays(branches=branches, outputtype=pandas.DataFrame, namedecode=namedecode, entrystart=entrystart, entrystop=entrystop, flatten=flatten, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)

~/.local/lib/python3.6/site-packages/uproot/tree.py in arrays(self, branches, outputtype, namedecode, entrystart, entrystop, flatten, cache, basketcache, keycache, executor, blocking)
    517         # if blocking, return the result of that function; otherwise, the function itself
    518         if blocking:
--> 519             return wait()
    520         else:
    521             return wait

~/.local/lib/python3.6/site-packages/uproot/tree.py in wait()
    482 
    483                             df = outputtype(index=pandas.MultiIndex.from_arrays([entries, subentries], names=["entry", "subentry"]))
--> 484                             if interpretation.asdtype.todims == ():
    485                                 df[name] = array.content
    486                             else:

AttributeError: 'asjagged' object has no attribute 'asdtype'
```

**Comment by jpivarski** [comment]
That's an idea. It'll fix this bug (I wish Python was strongly but dynamically typed for booleans, as it is for all other types) and make meaningful use of three states of the parameter. That's the kind of thing that would absolutely have to be documented, though. It's on my to-do list.

**Comment by henryiii** [comment]
> I wish Python was strongly but dynamically typed for booleans, as it is for all other types

How are booleans different from other types? All types have a truthiness, that just happens to also be the main use for booleans. You can say `x is False` just like `x is None`. And nothing is special about None here other than it being a useful way to indicate to do nothing with the jagged arrays. I would not have None the default, True or False would be better (since it is would be user-unfreindly to remove the jagged columns without their asking).

**Comment by henryiii** [comment]
Currently, `False` and `None` both do not crash, and they do the same thing - they are both "falsy". My suggestion is to make them do different things, just because I'd like three behaviors. The crash occurs when `True` is passed, which is *also the current default*. So to cause the crash above, just read a TTree with jagged columns into a dataframe using `t.pandas.df()`.

Python convention for None checking is to use `is not None`; there was a long-winded PEP a while back to even add a set of operators for None checking. The convention for `if x:` replaces `if x == True`, which is uglier and can crash if x does not support comparison.

I've got several issues with booleans. True and False act like numbers to a tea; while I like to sum over booleans to count `True`s, this is really odd: `~True` is -2, and therefore truthy. But on arrays, we use `~` for `not`. However, what I'd really love to be able to do is have `not`, `and`, and `or` be overloadable to be used on arrays, which would also fix statements like `2 < array < 3`.

**Comment by henryiii** [comment]
Do you have a simple jagged example in tests/samples? I don't see one... I'd like to find a couple of normal columns and a couple of jagged ones.

**Comment by henryiii** [comment]
Nevermind, I found one: `sample-6.10.05-uncompressed.root`. Verified that it crashes when you call `.pandas.df()`. I can add a test.

**Comment by henryiii** [comment]
Can I highly recommend you use pytest? It's the gold standard for Python testing and is much easier to read and maintain. It will also read unittest style tests until tests are converted.

**Comment by jpivarski** [comment]
First PR was #157, then migrated to #160 and merged. This will be version 3.2.3 of uproot.
