### ISSUE TITLE
Issues when reading array branches from cloned trees

### ISSUE THREAD

**Issue by mverzett** [scikit-hep/uproot#161]
Dear Devs,

I am merging several files into fewer ones with the TTree::CloneTree functionality. The files outputted are still reasonable in size (few hundreds MB). The trees that I am merging contain a 7x7 "picture" in the form of a float 2D array of fixed size.
Apparently CloneTree does something weird, as I can easily read the input files, but when I try to read the merged files I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/cern.ch/user/m/mverzett/.local/lib/python2.7/site-packages/uproot/tree.py", line 412, in arrays
    futures = [(branch.name, interpretation, branch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=(flatten and not ispandas), cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=False)) for branch, interpretation in branches]
  File "/afs/cern.ch/user/m/mverzett/.local/lib/python2.7/site-packages/uproot/tree.py", line 1249, in array
    self._tryrecover()
  File "/afs/cern.ch/user/m/mverzett/.local/lib/python2.7/site-packages/uproot/tree.py", line 1544, in _tryrecover
    self._recover()
  File "/afs/cern.ch/user/m/mverzett/.local/lib/python2.7/site-packages/uproot/tree.py", line 1525, in _recover
    recoveredbaskets = [x for x in uproot.rootio.TObjArray.read(self._source, self.fBaskets._cursor, self._context, self, asclass=TBranchMethods._RecoveredTBasket) if x is not None]
  File "/afs/cern.ch/user/m/mverzett/.local/lib/python2.7/site-packages/uproot/rootio.py", line 1128, in read
    out = cls._readinto(out, source, cursor, context, parent, asclass=asclass)
  File "/afs/cern.ch/user/m/mverzett/.local/lib/python2.7/site-packages/uproot/rootio.py", line 1139, in _readinto
    _endcheck(start, cursor, cnt)
  File "/afs/cern.ch/user/m/mverzett/.local/lib/python2.7/site-packages/uproot/rootio.py", line 386, in _endcheck
    raise ValueError("object has {0} bytes; expected {1}".format(observed, cnt))
ValueError: object has 17779 bytes; expected 17427
```

This happens **only** for the array branches, the rest works perfectly.

Did you encountered this issue before? Is there a workaround it? I'll be happy to provide privately a test input file.

Thanks!

**Comment by jpivarski** [comment]
This is getting into uproot's recovery code (in the stack trace as `_recover`), so it's a file that wasn't written "normally." I should take a look at this file to see what's going wrong in its recovery attempt, but it may be solvable for your use-case by explicitly calling `TTree::Write` and then `TFile::Close` before ending the writing process. That puts the basket data in the "normal" places so that recovery isn't needed.

**Comment by jpivarski** [comment]
@mverzett Any updates?

**Comment by mverzett** [comment]
@jpivarski indeed calling
```
tree.Write()
tfile.Close()
```
Solves the issues.
For the record, I was calling
```
tree.AutoSave()
tfile.Close()
```
As seen in a issue thread, apparently that does not work :)

**Comment by jpivarski** [comment]
To be clear, ROOT files created without an explicit `Write/Close` are valid and should be recoverable. Internally, they are very different and require specialized code to read. uproot has that code— quite a few of the early issues were about getting the recovery option working on all the sample files we were presented with. If your original file was readable in ROOT and not uproot, then you found a new bug in uproot's recovery code.

I'm glad that you've solved your problem with `Write/Close`, but there's still the specter of a possible bug floating around...
