### ISSUE TITLE
Read a TArrayF

### ISSUE THREAD

**Issue by MaxNoe** [scikit-hep/uproot#166]
I have a file that contains a tree of custom Root Objects that have a `TArrayF` field.

Is it possible to read the data in those `TArrayF` fields?

I saw you have some code in rootio.py handling `TArray`s.

**Comment by MaxNoe** [comment]
I tried calling `.array()` on the element and it threw and error.

```python
import uproot

f = uproot.open('magic_test.root')
t = f['Events']
at = t['MArrivalTime.fData'].array()
```

```
Traceback (most recent call last):
  File "read_tarrayf.py", line 7, in <module>
    at = t['MArrivalTime.fData'].array()
  File "/home/maxnoe/.local/anaconda3/lib/python3.6/site-packages/uproot/tree.py", line 1290, in array
    interpretation = self._normalize_interpretation(interpretation)
  File "/home/maxnoe/.local/anaconda3/lib/python3.6/site-packages/uproot/tree.py", line 1023, in _normalize_interpretation
    raise ValueError("cannot interpret branch {0} as a Python type".format(repr(self.name)))
ValueError: cannot interpret branch b'MArrivalTime.fData' as a Python type```


Temporary link to the file:
https://nextcloud.e5.physik.tu-dortmund.de/index.php/s/DtRDpzQnCgEoxBy

**Comment by MaxNoe** [comment]
I think the Problem is, that this is not a single `TArrayF` but a Branch with leafs that are `TArrayF`

**Comment by jpivarski** [comment]
I meant to fix this with a PR but I got my git branches mixed up and it went to master. (Fortunately, it didn't break anything!) All that was needed was an association between the TArray* type (not auto-generated, unlike most types) and the appropriate uproot interpretation. You can see it here: https://github.com/scikit-hep/uproot/commit/6c6cb0942ba66cf65a590f6fa2338aeb767e245e (At the same time, I also had to remove too-strict interpretation checking, which your issue revealed.)

This will be uproot 3.2.5.

**Comment by jpivarski** [comment]
> I think the Problem is, that this is not a single `TArrayF` but a Branch with leafs that are `TArrayF`

This branch has only one `TLeaf` (since it's an object, not a primitive type). It is true that each entry can have a variable-sized array (though for the basket that I looked at, all arrays happened to have the same length).

One potentially confusing thing is that in ROOT, "branch" is a container of data or a node in a tree whose children may contain data, while "leaf" means "data type specification." ROOT's use of the word "leaf" has nothing to do with the mathematical concept of a tree. Roughly, branches store the data and leaves are metadata specifying the type. If a branch has multiple "leaves," that means that it's a record type with multiple fields, and we read those into Numpy recarrays.

**Comment by MaxNoe** [comment]
Ah ok.

The arrays are always same-length in this case because it's the data in each pixel of the camera.

**Comment by eduardo-rodrigues** [comment]
Reminds me, @jpivarski: it would be fantastic to try and know who is using the various packages; basically from which experiment/community. Any idea on how to do that? If many were using the scikit-hep-forum mailing list (not at all the case), one could prepare a tiny Google survey … Else it's trickier.

**Comment by jpivarski** [comment]
@eduardo-rodrigues I wish I knew of a good way to do that. Other than adding code that "phones home" in the startup of uproot (I didn't, by the way). I have pip statistics, but that only tells me how many people downloaded it, not whether they really use it, what they use it for, and why.

**Comment by MaxNoe** [comment]
Ah, also a side question, is there a nice way to get a 2d ndarray from a jaggedarray when I know all arrays have the same shape? `np.array(jagged.tolist())` works but feels wrong as it first converts everything to pure python types.

**Comment by jpivarski** [comment]
@MaxNoe That's a good idea: there's isn't such a function but there should be. To get you started now,

```python
length = jagged.counts[0]
assert (jagged.counts == length).all()
twod = jagged.content.reshape(-1, length)
```

(Not tested, but that is probably right.)

**Comment by jpivarski** [comment]
I was looking at this just now and in the time since I wrote the above, such a function has been written. It's `jagged.regular()`.
