### ISSUE TITLE
TypeError: 'function' object is not iterable

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/uproot#171]
Some function calls seem to be failing in the master branch -

```
>>> f = uproot.recreate("tmp.root")
>>> f["name"] = numpy.histogram(numpy.random.normal(0, 1, 100000))
>>> f["name"].show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pratyush/dev/uproot/uproot/write/TFile.py", line 181, in __getitem__
    return self._reopen()[where]
  File "/home/pratyush/dev/uproot/uproot/write/TFile.py", line 113, in _reopen
    return uproot.open(self._path, localsource=uproot.source.file.FileSource.defaults)
  File "/home/pratyush/dev/uproot/uproot/rootio.py", line 69, in open
    kwargs = dict(MemmapSource.defaults)
TypeError: 'function' object is not iterable
```
It is not a file writing issue - I read it back in ROOT. 
I tried showstreamers() as well and it gave the same error.

**Comment by jpivarski** [comment]
Some time ago, I changed `MemmapSource.defaults` (and all other `.defaults`) from being functions to being dicts. Oh— maybe the equivalent code in `uproot.write.TFile.append` has not been updated?

**Comment by reikdas** [comment]
I can take a look over the weekend. (Unless you are already working on it)

**Comment by jpivarski** [comment]
I haven't been. (I have a stack of work on awkward-array, including a paper to write.)
