### ISSUE TITLE
Can't read custom leaflist struct into Pandas

### ISSUE THREAD

**Issue by beojan** [scikit-hep/uproot#177]
My tree contains some ordinary branches, and a couple that are structs written with leaflists.

`root_pandas` converts these to separate columns for each leaf, prefixed with the branch name. Uproot generates a single column, with nothing in it.

**Comment by jpivarski** [comment]
Yes, this is simply an oversight. I'll go do that.

**Comment by jpivarski** [comment]
This is PR #178. I think it's done; I'm just waiting for continuous integration. This will go into uproot 3.2.8 shortly.

**Comment by beojan** [comment]
I see you've used a dot as the separator. It turns out the Pandas `query` and `eval` functions don't play well with this.

**Comment by jpivarski** [comment]
Oh— my first thought was to use `['fieldname']` but I thought the nested quoting would be difficult to work with. We also use square brackets in the name for splitting matrices and such, though these have integers in the square brackets.

**Comment by beojan** [comment]
It's a general problem if you use `query` or `eval` (or if you want to use the `.field` accessors).
Perhaps you could provide an option that only generates column names which are valid python identifiers.

**Comment by jpivarski** [comment]
I could build the column names entirely out of underscores, but that would introduce a danger of accidentally duplicate names. A user-controllable option sounds like a good idea (though we're starting to pile on options that only pertain to Pandas).

**Comment by beojan** [comment]
An option in `pandas.df`, I was thinking.

**Comment by jpivarski** [comment]
`tree.pandas.df` if a thin wrapper around `tree.arrays` with `outputtype=pandas.DataFrame`, so any options added to the former have to go through the later.

**Comment by jpivarski** [comment]
Since the space of possible name conflicts is complex, I've added name-expansion as a user-provided function. Array-fetching methods (including `TTree.pandas.df`) now accept a `flatname` function as an argument. The default (`None`) is:

```python
def flatname(branchname, fieldname, index):   # str or bytes, None or str, tuple of ints
    out = branchname
    if not isinstance(branchname, str):
        out = branchname.decode("utf-8")
    if fieldname is not None:
        out += "." + fieldname
    if index != ():
        out += "[" + "][".join(str(x) for x in index) + "]"
    return out
```

(Whether `branchname` is a `str` or `bytes` is controlled by `namedecode`.) You can replace this function with

```python
def flatname(branchname, fieldname, index):   # str or bytes, None or str, tuple of ints
    out = branchname
    if not isinstance(branchname, str):
        out = branchname.decode("utf-8")
    return out + ("_" + fieldname if fieldname is not None else "") + "".join("_" + str(x) for x in index)
```

to delimit everything by underscores. This is in uproot 3.2.9.
