### ISSUE TITLE
XRootD-HTTPS support

### ISSUE THREAD

**Issue by PerilousApricot** [scikit-hep/uproot#190]
Hello,

I'm working on some code to read xrootd files via HTTP(s) and have hit an error I don't get. With the following test script

```python
#!/usr/bin/env python

import uproot
f = uproot.open("https://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root")
```

with the following patch applied (to relax the SSL settings)
```diff
diff --git a/uproot/source/http.py b/uproot/source/http.py
index 4a1564a..bcc71a1 100644
--- a/uproot/source/http.py
+++ b/uproot/source/http.py
@@ -30,6 +30,7 @@
 
 import os.path
 import re
+import ssl
 try:
     from urllib.request import urlopen, Request
 except ImportError:
@@ -46,6 +47,13 @@ class HTTPSource(uproot.source.chunked.ChunkedSource):
     def __init__(self, path, *args, **kwds):
         super(HTTPSource, self).__init__(path, *args, **kwds)
         self._size = None
+        if path.startswith("http://"):
+            self._sslcontext = None
+        else:
+            # Temporarily disable server cert verfication while I work out how
+            # to always find the grid CA bundle
+            self._sslcontext = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
+            self._sslcontext.verify_mode = ssl.CERT_NONE
 
     defaults = {"chunkbytes": 16*1024, "limitbytes": 16*1024**2}
 
@@ -59,7 +67,7 @@ class HTTPSource(uproot.source.chunked.ChunkedSource):
 
     def _read(self, chunkindex):
         request = Request(self.path, headers={"Range": "bytes={0}-{1}".format(chunkindex * self._chunkbytes, (chun
-        handle = urlopen(request)
+        handle = urlopen(request, context=self._sslcontext)
         data = handle.read()
         if self._size is None:
             m = self._contentrange.match(handle.headers.get("content-range", ""))
```

I get the error
```
Traceback (most recent call last):
  File "./test.py", line 4, in <module>
    f = uproot.open("https://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root")
  File "/home/meloam/projects/uproot/uproot/rootio.py", line 80, in open
    return http(path, httpsource)
  File "/home/meloam/projects/uproot/uproot/rootio.py", line 101, in http
    return ROOTDirectory.read(openfcn(path), **options)
  File "/home/meloam/projects/uproot/uproot/rootio.py", line 164, in read
    streamerkey = TKey.read(source, Cursor(fSeekInfo), streamercontext, None)
  File "/home/meloam/projects/uproot/uproot/rootio.py", line 842, in read
    out = cls._readinto(out, source, cursor, context, parent)
  File "/home/meloam/projects/uproot/uproot/rootio.py", line 864, in _readinto
    self._fNbytes, self._fVersion, self._fObjlen, self._fDatime, self._fKeylen, self._fCycle, self._fSeekKey, self._fSeekPdir = cursor.fields(source, self._format_small)
  File "/home/meloam/projects/uproot/uproot/source/cursor.py", line 70, in fields
    return format.unpack(source.data(start, stop))
  File "/home/meloam/projects/uproot/uproot/source/chunked.py", line 102, in data
    raise IndexError("indexes {0}:{1} are beyond the end of data source {2}".format(gstart + len(chunk), stop, repr(self.path)))
IndexError: indexes 29630001:29630027 are beyond the end of data source 'https://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root'
```

Though the file contains `29635611` bytes. I can verify that's what seen by HTTP as well:
```
$ curl -L -k -vvv https://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root -o out.txt
$ ls -l out.txt 
-rw-r--r--. 1 meloam cms 29635611 Dec 11 21:08 out.txt
```

I'm not exactly sure of what's going on -- the same file opens fine from the local filesystem -- is it possible there's a silly bug in the chunked source I'm missing? I'm gonna leave this as a placeholder while I try to solve it

**Comment by PerilousApricot** [comment]
Ahh, I see now -- This is a bug in xrootd - it returns the following for context range `context-range: bytes 0-16384/16385`, which makes uproot think that the whole file is 16k bytes. Is there a reason that you didn't parse `content-length`, which should also provide the length of the file?

**Comment by jpivarski** [comment]
It is utterly possible that I parsed the wrong header, but I'm surprised that you're the first to notice if it's taking the file size to be 16 kB. I'm sure we've opened much bigger files.

I can't remember what we'd lose by not knowing the total size at all.

**Comment by PerilousApricot** [comment]
Actually, content-length is supposed to be the length of the returned range, so it doesn't help. Xrootd has the wrong behavior here, the number after the slash in content-range is supposed to be the total length of the document:

https://tools.ietf.org/html/rfc7233#page-12

**Comment by PerilousApricot** [comment]
I have a workaround, but it's somewhat annoying to use with urllib(2) .. how much do you oppose adding a dep to the requests library? In particular, it handles HTTP keepalive, which is a pretty huge win for making multiple requests to the same TLS-encapsulated connection

**Comment by sbinet** [comment]
but... shouldn't it be:
```python
import uproot
f = uproot.open("root://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root")
```

_i.e._ explicitly use the `xrootd` protocol?

**Comment by PerilousApricot** [comment]
Xrootd (with the correct server-side configuration) supports HTTP(s) access, obviating the need to link the xrootd C++ library, and letting regular HTTP(s) clients transfer files to/from xrootd endpoints

https://twiki.cern.ch/twiki/bin/view/Main/XRootDoverHTTP

You can see where I explicitly curl the file in my previous post:
```
$ curl -L -k -vvv https://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root -o out.txt
$ ls -l out.txt 
-rw-r--r--. 1 meloam cms 29635611 Dec 11 21:08 out.txt
```

**Comment by sbinet** [comment]
ah!

```
$> go get -u go-hep.org/x/hep/xrootd/cmd/xrd-ls
$> xrd-ls https://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root
xrd-ls: could not list "https://xrootd.accre.vanderbilt.edu:1094/store/data/Run2017E/SingleMuon/NANOAOD/31Mar2018-v1/710000/5400FB33-0A47-E811-AE48-0023AEEEB703.root" content: could not create client: xrootd: could not authorize:
[xrootd: could not authorize using gsi: provider was not found]
```

(well, the GSI thing is xrootd/xrootd#757, but other than that, it's indeed working...)

**Comment by PerilousApricot** [comment]
well, the bigger point is that you don't have to get any special XRootD clients at all - the server supports bog-standard HTTP, so you can access it like any other HTTP host. There is one small extension that's used to enable 3rd party transfers between two different XRootD endpoints, but in particular for uproot, it supports what you want -- reading byte ranges out of files, and the ability to upload files back

**Comment by jpivarski** [comment]
I would not be opposed to adding improvements in this area that I know little about if you provide it as a pull request. I also wouldn't mind adding the `requests` library as a strict dependency if it's pure Python or easy to install with pip. If it's the sort of thing that's only easy to install with something like conda, then I'd prefer to make it an optional dependency like `pyxrootd` and `backports.lzma` are now.

If it's possible to drop `pyxrootd` entirely, that would be a win. This package has no easy install method (I resort to CMake) and has been a considerable source of bugs. Also, I'm not using it any differently than HTTP: both the XRootD and HTTP backends use the same chunk-loading routines. (I don't use XRootD as a replacement for `fread`, as that would be too many small requests.) So if the solution is to translate "root://" URLs into their "http(s)://" equivalents, that would be great on many levels!

I'm planning a new semi-major release soon, and that would be a good time to change the dependencies.

**Comment by jpivarski** [comment]
@PerilousApricot I'd like to release 3.3.0 today to require upstream changes from awkward and uproot-methods. Is there something simple that I can add now that will improve this situation? Should I try to determine if I can ignore the output from "content-length"? I think it's only used to make that error message. Without it, users would just get more confusing error messages in the case of an actual error, which is better than getting wrong error messages when things aren't in error.

**Comment by PerilousApricot** [comment]
TBH, trying to eyeball it, I'm not quite following how the size is being
passed between source <-> chunked <-> HTTP and if that would fix it.

>
In either case, even fixing the length mismatch doesn't make us able to
read from xrootd hosts -- because we use non-standard CAs, urllib will
cowardly fail the TLS handshake.

I realistically won't have time to polish up this until Monday, so I'd say
to just leave it as-is and I'll try to get in on the next release.

Cheers
Andrew

**Comment by PerilousApricot** [comment]
as an aside, don't you want to call super here?
https://github.com/scikit-hep/uproot/blob/master/uproot/source/chunked.py#L40

**Comment by jpivarski** [comment]
I put in exactly one change that will propagate to 3.3.0: uproot no longer trusts the `"content-range"` length if it is not longer than the fragment. That should solve your original issue, though we've talked about a lot more than that here. I've checked and this size is not very important at all: _if_ the file size is known and there's an attempt to read beyond the file size, then uproot raises an exception. If the file size is not known, there's no immediate exception, but reading is very likely to fail soon thereafter.

**Comment by PerilousApricot** [comment]
That's helpful, but to be clear, urllib wont work with any existing CMS
xrootd server because the SSL certs are signed by custom CAs. (Eg don't
announce it as a new feature!)
-- 
It's dark in this basement.

**Comment by jpivarski** [comment]
I won't announce it. I also haven't applied your patch, which I guess is about certificates. I'm willing to consider depending on the requests library, but not for this release.

About the call to `super`, I haven't been following a style that requires it in each `__init__`. I can see that being a good discipline to impose on class inheritance, but actually, I've never heard of it as a rule. (I call `super` when I explicitly need it.)

**Comment by PerilousApricot** [comment]
No, I don't think that patch was ready, it was just to show a reproducer.

Not passing super up the class hierarchy is what confused me trying to
eyeball the code, but you do you :)
-- 
It's dark in this basement.

**Comment by jpivarski** [comment]
There are still open issues in this discussion, but I'm confused about where they are. Therefore, I'll close this (because the original issue was fixed) and you can reopen when you're ready to propose something concrete. Thanks!
