### ISSUE TITLE
Improve help() output for uproot

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#191]
I installed `uproot` fresh with pip. Doing `help()` and then `uproot`, I see
```
NAME
    uproot

FILE
    /Users/hdembins/Library/Python/2.7/lib/python/site-packages/uproot/__init__.py

DESCRIPTION
    # Copyright (c) 2017, DIANA-HEP
    # All rights reserved.
    #
    # Redistribution and use in source and binary forms, with or without
    # modification, are permitted provided that the following conditions are met:
    #
    # * Redistributions of source code must retain the above copyright notice, this
    #   list of conditions and the following disclaimer.
    #
    # * Redistributions in binary form must reproduce the above copyright notice,
    #   this list of conditions and the following disclaimer in the documentation
    #   and/or other materials provided with the distribution.
    #
    # * Neither the name of the copyright holder nor the names of its
    #   contributors may be used to endorse or promote products derived from
    #   this software without specific prior written permission.
    #
    # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    # AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    # DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
    # FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
    # DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    # SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    # CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
    # OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
    # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PACKAGE CONTENTS
    _connect (package)
    _help
    cache
    const
    interp (package)
    rootio
    source (package)
    tree
    version
    write (package)

DATA
    __version__ = '3.2.14'
    asdebug = asjagged(asdtype('uint8'))

VERSION
    3.2.14
```

It would be nice if there was some basic overview was displayed instead of the license, similar to what happens when you look at `numpy` in `help()`. I also think that the saying "this code is released under the BSD-3-Clause license" followed by an url to the license text would be better than quoting the license.

I am confused about the DATA field `asdebug`. Shouldn't this be a bool? Is this DATA field really intentionally visible or should it rather be hidden?

**Comment by jpivarski** [comment]
I didn't know that help(uproot) would give you anything. I'll look into changing it. It should probably be a summary of the top-level functions.

The uproot Interpretations all begin with "as" and there are a lot of them at the top level (uproot.__all__). asdebug is an Interpretation that shows you raw bytes separately for each entry in a TTree, which is in the border between public and private. I have used it in debugging sessions with users— it's not a "deeply internal" thing to do. So I'm on the fence about putting an underscore in front of it.

Anyway, a proper listing of the top-level objects would show a dozen things that start with "as", with asdebug being only one of them.

**Comment by jpivarski** [comment]
I'm putting a lot of updates into branch [prepare-330](https://github.com/scikit-hep/uproot/tree/prepare-330). One of them is that

```python
help(uproot)
```

now gives a usage cheat-sheet as a starting point for finding options.

**Comment by HDembinski** [comment]
Cool, thanks :)
