### ISSUE TITLE
Allow to read TNonSplitBrowsable objects

### ISSUE THREAD

**Issue by moritzhuetten** [scikit-hep/uproot#197]
Hi,
I am trying to read in an array from a TNonSplitBrowsable class object, as shown below:
![tnonsplitbrowsable](https://user-images.githubusercontent.com/6513799/50008194-b5418900-ffb3-11e8-9e63-b06d24c3bb02.png)

Apparently, uproot can't yet handle this type,

`>>> input_file['Branch']['Tree.fArray.fInfo'].show()`
`Tree.fArray.fInfo (no streamer)      None`

Would it be possible to include in uproot? That would be amazing (and very helpful for our use case)!

Thanks a lot.

**Comment by jpivarski** [comment]
I don't know anything about this type of object, but from the name it's doubtful: unsplit objects are not uproot's strong point. Sometimes they can be read, like TH1 for people who put histograms inside TTrees, but only by dropping from Numpy performance down to Python performance.

If that doesn't matter to you, I can take a look at an example file. If it's just some streamer type I haven't implemented, then it may be simple. However, there have been a few examples (#185 recently) when I simply haven't been able to figure out the structure. So send me a file and I'll let you know. If it's small enough and can be public, I'd make it a unit test.

**Comment by moritzhuetten** [comment]
Thanks for the swift response! In fact, I am actually able to provide an example file, I put it here: https://owncloud.cta-observatory.org/index.php/s/Iw1F7dZj5Sj61qr/download. It is the RunHeaders/MBadPixelsCam.fArray.fInfo.fArray object. No worries if the performance may be suboptimal for these objects (we can't change it anyway). I'll provide you with a cropped (smaller) version later, if it works out. Thanks a lot again for your support.

**Comment by moritzhuetten** [comment]
Hi Jim, thanks a ton again - This explanation of how to use uproot as it is already is sufficient to read my data (it works, thanks!), so yes, no urgent need to implement a new streamer for the time being. I guess we can close this issue for now?

**Comment by jpivarski** [comment]
I was thinking about keeping it open to remind me to do steps 2 and 3. It's the Right Thing To Do. But there's no reason to keep you from being productive by giving you a recipe now.
