### ISSUE TITLE
TH2 variances returned as a list not a 2 by 2 array 

### ISSUE THREAD

**Issue by alasfar-lina** [scikit-hep/uproot#200]
It is not possible to use the variances method  effectivly for TH2 histograms ...  as it does not return an array with the correct dimensions

**Comment by jpivarski** [comment]
This belongs to [uproot-methods](https://github.com/scikit-hep/uproot-methods/issues). It could be because `uproot_methods.classes.TH2` inherits an unshaped array from `uproot_methods.classes.TH1`.
