### ISSUE TITLE
Iterate method now works, but fails when branch has 0 baskets

### ISSUE THREAD

**Issue by HealthyPear** [scikit-hep/uproot#205]
Dear Developer,

I confirm that the previous issue with the iterate method (failing when key missing from 1 file of the "TChain") now works.

While testing, I stumbled in an additional problem.

I have N files on which I iterate to print the "TChain" of branch X leaf Y.

The method fails on one of them with the message:

Traceback (most recent call last):
  File "/Users/WWW/Documents/Research/DataAnalysis/research-codes/ZZZ/loadData.py", line 31, in <module>
    for arrays in uproot.iterate(dataFiles, treeName, [varX, varY]):
  File "/Users/WWW/Library/Python/2.7/lib/python/site-packages/uproot/tree.py", line 126, in iterate
    for start, stop, arrays in tree.iterate(branches=newbranches, entrysteps=entrysteps, outputtype=outputtype, namedecode=namedecode, reportentries=True, entrystart=0, entrystop=tree.numentries, flatten=flatten, flatname=flatname, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking):
  File "/Users/WWW/Library/Python/2.7/lib/python/site-packages/uproot/tree.py", line 576, in iterate
    for start, stop in entrysteps:
  File "/Users/WWW/Library/Python/2.7/lib/python/site-packages/uproot/tree.py", line 401, in clusters
    leadingstart = max(cursor.entrystart for cursor in cursors)
  File "/Users/WWW/Library/Python/2.7/lib/python/site-packages/uproot/tree.py", line 401, in <genexpr>
    leadingstart = max(cursor.entrystart for cursor in cursors)
  File "/Users/WWW/Library/Python/2.7/lib/python/site-packages/uproot/tree.py", line 393, in entrystart
    return self.branch.basket_entrystart(self.basketstart)
  File "/Users/WWW/Library/Python/2.7/lib/python/site-packages/uproot/tree.py", line 1012, in basket_entrystart
    raise IndexError("index {0} out of range for branch with {1} baskets".format(i, self.numbaskets))
IndexError: index 0 out of range for branch with 0 baskets

If I open the file on which the iterate method crashes using a TBrowser from ROOT, I can see that such file does have branch X (so this problem does not revert to the previous one), does have leaf Y, but when double clicking on it I don't get any output (i.e. histogram).
Same thing for all the other leaves in branch X (this means that the subsystem was alive enough to generate its TTree in the file, but not enough to generate data...).

Best regards

**Comment by jpivarski** [comment]
Hi! I was about to fix this when I realized that I don't have an example file. I could try generating an example file, but there are too many variables: like, are there baskets but they're empty or are the baskets non-existent? So, could you send me that file? And since the file is probably small and containing no secrets (being empty), could I include it as a unit test? Thanks!

**Comment by jpivarski** [comment]
@HealthyPear Hello? I'd like to fix this— I just need an example to look at. Thanks!

**Comment by HealthyPear** [comment]
Hello! Unfortunately, the file I am using is part of an experiment with non-published data, and I am not currently allowed to share it...is there any way one can create a dummy ROOT file that behaves as I described?

**Comment by jpivarski** [comment]
Understood— you can't share non-published data. However, I don't want to artificially make a dummy ROOT file because I want to see how this issue comes up naturally.

Even with private experimental data, if one of the N files in the dataset is empty, then it doesn't convey any unpublished secrets, right? If the TTree in question the only TTree in the file? One branch has empty baskets; are the other branches empty as well? Do any names reveal collaboration secrets?

Considering the sensitive nature of the data, I can definitely avoid using it as a unit test. But if it also satisfies the above— a single file with zero events— then wouldn't it also be safe to share with me because I can't learn anything about the data from a zero-event file?

**Comment by HealthyPear** [comment]
Unfortunately, the empty leaf is just one of many non-empty ones in one of many sub-systems TTrees, along with the actual events of the scientific target...

**Comment by jpivarski** [comment]
Oh, okay. I could put in a trial fix and let you test it. I could just look for all the places where I've assumed that the number of baskets is not zero and patch them. It might be a day or two before I can apply those fixes to give you a candidate to test.

**Comment by HealthyPear** [comment]
No problem, is not super urgent since it's not recent data but you never know, it may happen anytime :)

Thanks for your work,
Best regards

**Comment by jpivarski** [comment]
The issue was less pervasive than I was worried about: it's not in any reading code, just the function that generates places to start and stop in `iterate`. Therefore, I'm feeling pretty confident about the fix. However, it would be great to check with your files that actually have a branch with no baskets.

It's [branch issue-205](https://github.com/scikit-hep/uproot/tree/issue-205) in pull request #215. If it passes its own tests and you give me the okay, I'll deploy it as uproot version 3.3.4. Thanks!

**Comment by HealthyPear** [comment]
Hello!
I created a virtual environment in which I have modified the file uproot/tree.py as in your commit for pull request #215: unfortunately it's still not working, though I get a slightly different error which I report here,

`
Traceback (most recent call last):
  File "loadData.py", line 224, in <module>
    x, y, z = loadDataShorter(dataFiles, varX, varY, varZ)
  File "loadData.py", line 67, in loadDataShorter
    for arrays in uproot.iterate(dataFiles, treeX, [varX]):
  File "/Users/HealthyPear/.local/share/virtualenvs/prova-fL596tBI/lib/python2.7/site-packages/uproot/tree.py", line 126, in iterate
    for start, stop, arrays in tree.iterate(branches=newbranches, entrysteps=entrysteps, outputtype=outputtype, namedecode=namedecode, reportentries=True, entrystart=0, entrystop=tree.numentries, flatten=flatten, flatname=flatname, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking):
  File "/Users/HealthyPear/.local/share/virtualenvs/prova-fL596tBI/lib/python2.7/site-packages/uproot/tree.py", line 591, in iterate
    basket_entryoffset = branch._basket_entryoffset(basketstart, basketstop)
  File "/Users/HealthyPear/.local/share/virtualenvs/prova-fL596tBI/lib/python2.7/site-packages/uproot/tree.py", line 1242, in _basket_entryoffset
    for i in range(basketstart, basketstop):
TypeError: range() integer end argument expected, got NoneType.
`

If can be of any help, I also report here the function mentioned in the log:

    def loadDataShorter(files, varX, varY = None, varZ = None):
        
        treeX = getTreeName(varX)
        treeY = getTreeName(varY)
        treeZ = getTreeName(varZ)

        x = numpy.array([])
        for arrays in uproot.iterate(dataFiles, treeX, [varX]):
            x0 = arrays[varX]
            x = numpy.concatenate([x, x0])

        if varY != None:
            y = numpy.array([])
            for arrays in uproot.iterate(dataFiles, treeY, [varY]):
                y0 = arrays[varY]
                y = numpy.concatenate([y, y0])
        else:
            y = None

        if varZ != None:
            z = numpy.array([])
            for arrays in uproot.iterate(dataFiles, treeZ, [varZ]):
                z0 = arrays[varZ]
                z = numpy.concatenate([z, z0])
        else:
            z = None

        return x, y, z


then I just do,

`x, y, z = loadDataShorter(dataFiles, varX, varY, varZ)`

**Comment by jpivarski** [comment]
Thanks for all the information. There was, as I originally feared, a zero-basket bug related to reading, but you didn't reach that bug until the first was cleared up (hence the new error message).

Could you try it now? I just put another correction into the pull request.

**Comment by HealthyPear** [comment]
Thank for this fixes, now it seems to work! At least on the file I have :)

Would it be possible to add a feature to the iterate method (or an option to it) in order to print the (list of) file(s) which either do not have a TTree or have empty baskets?
This would be useful in order to treat separately in an analysis the data for which a particular observable is not available.

Best regards

**Comment by jpivarski** [comment]
Thanks for testing!

What you're asking for as a feature is something I'd rather have the user do manually:

```python
file = uproot.open("samplefile.root")
"treename" in file                               # True if the TTree exists
file["treename"].numentries != 0                 # True if the TTree has entries
file["treename"]["branchname"].numbaskets != 0   # True if the TBranch has baskets
```

The information you want can be accessed, but you have to "build" it from the basic pieces. If we had special parameters for these things, it would convenience the users who know the parameter names, but would quickly run up a very large number of parameters.

**Comment by HealthyPear** [comment]
I understand your point, it makes perfect sense.

Though it is not straightforward to me how to access sequentially the file in the “TChain” - done this, one can certainly apply the checks you suggest.

Is there already a way to access the *current* file used by uproot.iterate at each step?

Cheers

**Comment by jpivarski** [comment]
There isn't, and that might be what you're looking for. The `reportentries=True` parameter adds to the output at each step (start and stop numbers), so an additional `reportfile=True` to give you the file would make your task easier. The trick would be handling both: which one comes first if both are requested, and how to communicate that to the user?

Fortunately, `uproot.iterate` places firm boundaries between each file, so on a particular iteration, there's only one file.
