### ISSUE TITLE
read password protected fileover http

### ISSUE THREAD

**Issue by noahhdf** [scikit-hep/uproot#210]
I'm trying to read a file via http:
```python
file = uproot.open("http://data.magic.pic.es/Data/SuperStar/v1/CrabNebula/2014_01_01/20140101_05032025_S_CrabNebula-W0.40+035.root")
```
I get the following error:
```python
HTTPError: HTTP Error 401: Unauthorized
```
Which is basically what I'm expecting, because if I try to download it directly with my browser, I'm prompted
> http://data.magic.pic.es is requesting your username and password. The site says: “Authenticated proxy”

Is there a way to read a file via http on a server which is password protected?

**Comment by jpivarski** [comment]
It's not currently a feature of uproot. I bet there's a way to pass this information through Python's HTTP handlers, and that would be an improvement. If you figure out how to do that, I'd be open to incorporating it.
