### ISSUE TITLE
Problem adding jagged TLorentzVectors

### ISSUE THREAD

**Issue by areinsvo** [scikit-hep/uproot#212]
I'm getting an error when trying to add jagged TLorentzVectors. The physics use case is that we need to calculate recoil, which equals met in the signal region and equals met+leading photon pt for a control region. The code snippet below reproduces the error.

Error: `TypeError: (arrays of) TLorentzVector can only be added to/subtracted from other (arrays of) TLorentzVector`

import awkward
import uproot, uproot_methods

offsets=[0,1,3,5]
pts = [50,60,70,80,90,100]
phis = [0.4,0.5,0.6,0.1,0.2,0.3]
etas = [1,2,3,4,5,6]
jagged_pt=awkward.JaggedArray.fromoffsets(offsets,pts)
jagged_phi=awkward.JaggedArray.fromoffsets(offsets,phis)
jagged_eta=awkward.JaggedArray.fromoffsets(offsets,etas)
phos= uproot_methods.TLorentzVectorArray.from_ptetaphi(jagged_pt,jagged_eta,jagged_phi,0)

offsets2=[0,1,2,3]
met_pt = [20,30,40]
met_phi = [0.1,0.2,0.3]
jagged_met_pt = awkward.JaggedArray.fromoffsets(offsets2,met_pt)
jagged_met_phi = awkward.JaggedArray.fromoffsets(offsets2,met_phi)
met = uproot_methods.TLorentzVectorArray.from_ptetaphi(jagged_met_pt,0,jagged_met_phi,0)

highest_pt_pho=phos[phos.pt.argmax()]
recoil = met.zeros_like()
recoil = recoil.cross(highest_pt_pho,nested=True)
recoil = (recoil.i0 + recoil.i1).sum()
recoil += met

**Comment by jpivarski** [comment]
Given how quickly I'm responding, you know that I haven't looked deeply into this or reproduced it, but the first warning bell is that you're attempting to change a jagged array in place with `+=`. Although a change like `+=` sounds benign, in general the consequences of changing awkward-arrays in place get too complicated to consider, so there's a blanket rule against it. I thought I put in a better error message explaining this when an in-place operation is attempted...

So do `recoil = recoil + met`.

**Comment by nsmith-** [comment]
Indeed that works, so I guess the error message isn't clear enough

**Comment by jpivarski** [comment]
I have a label for that!

**Comment by jpivarski** [comment]
In fact, I can't reproduce it. Maybe you just need to upgrade?

(Upgrade to get a shiny new error message! The bottom line is the same: don't use in-place operations like `+=`.)
