### ISSUE TITLE
Problem with TVector3

### ISSUE THREAD

**Issue by daria137** [scikit-hep/uproot#213]
I'm getting an error when trying to read TVector3. The code below reproduce the problem:

import uproot
file=uproot.open("test.root")["T"]
T.show()
T["fMCHits.fPosition"].array()
ValueError: cannot interpret branch 'fMCHits.fPosition' as a Python type

Can I somehow use array(interpret) to force the TVector3 structure there?

uproot: 3.3.2
uproot-methods: 0.3.3
[test.zip](https://github.com/scikit-hep/uproot/files/2772582/test.zip)

**Comment by jpivarski** [comment]
You can, by building an `asjagged(asobj(uproot_methods.classes.TVector3.Methods))` Interpretation object, but you don't need to because your example file helped me fix it:

```python
>>> t.show()
...
fMCHits.fTime              TStreamerBasicType         asjagged(asdtype('>f4'))
fMCHits.fPosition          TStreamerInfo              asjagged(asobj(<uproot_methods.classes.TVector3.Methods>))
fMCHits.fPolarizationIn    TStreamerInfo              asjagged(asobj(<uproot_methods.classes.TVector3.Methods>))
fMCHits.fPolarizationOut   TStreamerInfo              asjagged(asobj(<uproot_methods.classes.TVector3.Methods>))
fMCHits.fMomentumIn        TStreamerInfo              asjagged(asobj(<uproot_methods.classes.TVector3.Methods>))
fMCHits.fMomentumOut       TStreamerInfo              asjagged(asobj(<uproot_methods.classes.TVector3.Methods>))
```

This will be in the next release (currently testing).
