### ISSUE TITLE
Option in iterate method to access the current file used by uproot.iterate at each step

### ISSUE THREAD

**Issue by HealthyPear** [scikit-hep/uproot#217]
I open first an issue (actually more of a feature request) instead of directly create a new pull request, so we can discuss first.

I created a virtual environment with _pipenv_ to play a bit with the source code - this is my proposal:

1. make __iterate_ function return by default also the file path from line 162 `for path in paths:`, modifying line 183 as follows,
`yield tree, newbranches, globalentrystart ---> yield tree, newbranches, globalentrystart, path`
2. add a new _reportfile_ argument defaulting to _False_ to the definition of _iterate_,
3. retrieve _path_ from __iterate_, modifying line 125 as follows,
    `for tree, newbranches, globalentrystart in _iterate(.....): ---> for tree, newbranches, globalentrystart, path in _iterate(.....):`
4. add a check to the existing one on `reportentries` in order to take into account all 4 possibilities (both True, only one True and both False), modifying lines from 130 to 133 as follows,
```
    if reportentries:
        yield globalentrystart + start, globalentrystart + stop, arrays
    else:
        yield arrays
```
--->
```
    if reportentries:
        if reportfile:
             yield globalentrystart + start, globalentrystart + stop, arrays, path
        else:
             yield globalentrystart + start, globalentrystart + stop, arrays
    else:
       if reportfile:
             yield arrays, path
       else:
             yield arrays
```
so path will always be the last argument.

I tested such proposed solution successfully on my setup using Python2.

**Comment by jpivarski** [comment]
Wow, you did nearly all the work on this— I had mentally filed it away as future work to do.

I'm going to ask, though, that you turn it into a pull request:

1. [Fork](https://help.github.com/articles/fork-a-repo/) the uproot repo in GitHub.
2. Make the changes in [a new branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/) of your repository, using your virtualenv to check that they're properly applied.
3. [Pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) your fork to my repo, which I can then use to integrate them into a new version.

A pull request is an easier and safer way to communicate code changes (and you'll probably use it on other projects, if you're not already). If you do the pull request from a non-master branch of your repo, I can send my edits back, so we can converge on it. The pull request will also trigger the full testing matrix, so it will be tested by Travis for all versions of Python and all versions of Numpy. It's a good habit to get into.

Then we can get this done by the end of the day.

**Comment by HealthyPear** [comment]
Ok, done!
I hope I did everything right, it was my first public pull request :)

Cheers

**Comment by jpivarski** [comment]
Let me know on the pull request (#218) if you're happy with my counter-edits. It has implications for your scripts (tuple order is a little different). Once you give me the go-ahead, I'll merge in the changes and publish it as uproot 3.3.5. The tests have already passed.
