### ISSUE TITLE
Asseration error while reading TBranchElement

### ISSUE THREAD

**Issue by thomaskeck** [scikit-hep/uproot#231]
Hi,

I encounter the same error as in this earlier issue (https://github.com/scikit-hep/uproot/issues/198) but the proposed workaround does not work in this situation. And maybe this is caused by something entirely different. So I'm opening a new issue here.

Here is a minimal example of the issue.

```
> import uproot
> file = uproot.open("09D95BE7-23C8-5542-9FA4-102E3FEDB7A2.root")
> file["Events"].array("SimVertexs_g4SimHits__SIM.obj")
---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)
<ipython-input-190-4eb779d53508> in <module>()
----> 1 file["Events"].array("SimVertexs_g4SimHits__SIM.obj")

/home/thomaskeck/venc/local/lib/python2.7/site-packages/uproot/tree.pyc in array(self, branch, interpretation, entrystart, entrystop, flatten, flatname, awkwardlib, cache, basketcache, keycache, executor, blocking)
    440 
    441     def array(self, branch, interpretation=None, entrystart=None, entrystop=None, flatten=False, flatname=None, awkwardlib=None, cache=None, basketcache=None, keycache=None, executor=None, blocking=True):
--> 442         return self.get(branch).array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=flatten, flatname=flatname, awkwardlib=awkwardlib, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
    443 
    444     def arrays(self, branches=None, outputtype=dict, namedecode=None, entrystart=None, entrystop=None, flatten=False, flatname=None, awkwardlib=None, cache=None, basketcache=None, keycache=None, executor=None, blocking=True):

/home/thomaskeck/venc/local/lib/python2.7/site-packages/uproot/tree.pyc in array(self, interpretation, entrystart, entrystop, flatten, flatname, awkwardlib, cache, basketcache, keycache, executor, blocking)
   1292             keycache = {}
   1293 
-> 1294         basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
   1295         basket_entryoffset = self._basket_entryoffset(basketstart, basketstop)
   1296 

/home/thomaskeck/venc/local/lib/python2.7/site-packages/uproot/tree.pyc in _basket_itemoffset(self, interpretation, basketstart, basketstop, keycache)
   1249         for j, key in enumerate(self._threadsafe_iterate_keys(keycache, True, basketstart, basketstop)):
   1250             i = basketstart + j
-> 1251             numitems = interpretation.numitems(key.border, self.basket_numentries(i))
   1252             basket_itemoffset.append(basket_itemoffset[-1] + numitems)
   1253         return basket_itemoffset

/home/thomaskeck/venc/local/lib/python2.7/site-packages/uproot/interp/jagged.pyc in numitems(self, numbytes, numentries)
     86 
     87     def numitems(self, numbytes, numentries):
---> 88         return self.content.numitems(numbytes - numentries * self.skipbytes, numentries)
     89 
     90     def source_numitems(self, source):

/home/thomaskeck/venc/local/lib/python2.7/site-packages/uproot/interp/objects.pyc in numitems(self, numbytes, numentries)
    140 
    141     def numitems(self, numbytes, numentries):
--> 142         return self.content.numitems(numbytes, numentries)
    143 
    144     def source_numitems(self, source):

/home/thomaskeck/venc/local/lib/python2.7/site-packages/uproot/interp/numerical.pyc in numitems(self, numbytes, numentries)
    170         dtype, shape = _dtypeshape(self.fromdtype)
    171         quotient, remainder = divmod(numbytes, dtype.itemsize)
--> 172         assert remainder == 0
    173         return quotient
    174 

AssertionError: 

```

What makes this different from the previous issue is that the interpretation is a jaggedarray
```
> file["Events"]["SimVertexs_g4SimHits__SIM.obj"].interpretation
asjagged(astable(asdtype("[('id_', '>u4'), ('fX', '>f8'), ('fY', '>f8'), ('fZ', '>f8'), ('fT', '>f8'), ('itrack', '>i4'), ('vtxId', '>u4'), ('procType', '>u4')]")), 10)
```
I'm not familiar with the ROOT format, but after some investigation it seems like the basket contains an extra 49 bytes (maybe a class header?) in front of the entire table (not in front of each element, hence the previous workaround does not work).

I'm using uproot version 3.4.5, uproot-methods version 0.4.2 and python 2.7.

The file can be found here (2.9GB!):
https://eospublichttp.cern.ch/eos/opendata/cms/MonteCarloUpgrade/RunIIAutumn18DR/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/GEN-SIM-RAW/PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/110000/09D95BE7-23C8-5542-9FA4-102E3FEDB7A2.root

**Comment by jpivarski** [comment]
Yes, the workaround in #198 is peculiar to the structure of that file. My failure there was not finding a way to get uproot to detect the layout from the metadata it provides; your file presumably provides different metadata for this different layout. I'll take a look as soon as I can.

**Comment by jpivarski** [comment]
I've taken a look at the data and I'm _thoroughly_ perplexed. If the basket data just had an excess 49 bytes at the beginning, we'd be able to take care of that easily (assuming that we aren't demanding uproot to have discovered this—49 bytes is a lot of extra header!):

```python
b = file["Events"]["SimVertexs_g4SimHits__SIM.obj"]
reinterpret = uproot.asjagged(b.interpretation.content, 49)   # or 49 + 10
b.array(reinterpret)
```

The `asjagged` interpretation has a `skipbytes` parameter (uproot believes it should be 10 in your case, as it is in all the examples of STL vectors I've been able to generate), so I just unwrapped the original `asjagged` and created a new one with the bytes skipped. That doesn't help.

But just looking at the raw data, it doesn't look like there's anything there. `asdebug` is a special interpretation that I use to diagnose these things: it's `asjagged(asdtype("uint8"))`, using knowledge of the entry/event boundaries from ROOT (`asjagged`) but displaying only the raw bytes in each entry/event. The first 5550 bytes are extremely regular:

```python
>>> b.array(uproot.asdebug)[0][:500]
array([ 64,   0, 160,  44,  64,   9,   0,  12,   0,   0,   2,  42,  64,
         0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,
         0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,
         0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,
        64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,
         6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,
         0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,
         0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,
         0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,
        10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,
         0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,
         0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,
         0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,
         0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,
        64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,
         6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,
         0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,
         0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,
         0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,
        10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,
         0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,
         0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,
         0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,
         0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,
        64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,
         6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,
         0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,
         0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,
         0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,
        10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,
         0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,
         0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,
         0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,
         0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,
        64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,   0,
         6,   0,  10,   0,   0,   0,   0,  64,   0,   0,   6,   0,  10,
         0,   0,   0,   0,  64,   0,   0,   6,   0,  10,   0,   0,   0,
         0,  64,   0,   0,   6,   0,  10,   0,   0,   0,   0,  64,   0,
         0,   6,   0,  10,   0,   0], dtype=uint8)
>>> b.array(uproot.asdebug)[0][:500].view(">i4")
array([1073782828, 1074331660,        554, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360,
            16384,     393226,          0, 1073741830,     655360],
      dtype=int32)
```

There's no way these fit into a structure like

```python
>>> b.interpretation
asjagged(astable(asdtype("[('id_', '>u4'), ('fX', '>f8'), ('fY', '>f8'), ('fZ', '>f8'), ('fT', '>f8'), ('itrack', '>i4'), ('vtxId', '>u4'), ('procType', '>u4')]")), 10)
```

None of those first (very repetitive) 5550 bytes looks anything like a big-endian double-precision floating point number, for instance. Also, the data we're expecting has a data type that repeats every 48 bytes, but the data we see repeats every 20 bytes. There's no way they can line up.

So I'm baffled. Can you read these data in ROOT?

**Comment by thomaskeck** [comment]
@jpivarski thanks for your analysis of the issue!

This looks strange indeed! I did not create the files myself, and currently have not setup root.
I will install ROOT, check the file and report back here.

**Comment by thomaskeck** [comment]
I cannot read the data in ROOT because I'm missing the dictionaries.
Explicitly defining the class SimVertex also does not help.

> 
> tkeck@localhost:~$ root -l 09D95BE7-23C8-5542-9FA4-102E3FEDB7A2.root 
> root [0] 
> Attaching file 09D95BE7-23C8-5542-9FA4-102E3FEDB7A2.root as _file0...
> Warning in <TClass::Init>: no dictionary for class edm::EventAuxiliary is available
> Warning in <TClass::Init>: no dictionary for class edm::Hash<2> is available
> Warning in <TClass::Init>: no dictionary for class edm::EventID is available
> Warning in <TClass::Init>: no dictionary for class edm::Timestamp is available
> [...]
root [3] float test;
root [4] Events->SetBranchAddress("SimVertexs_g4SimHits__SIM.obj", &test)
Error in <TTree::SetBranchAddress>: The pointer type given "Float_t" (5) does not correspond to the type needed "vector<SimVertex>" by the branch: SimVertexs_g4SimHits__SIM.obj
(int) -2
> root [12] class SimVertex {
> root (cont'ed, cancel with .@) [13]public:
> root (cont'ed, cancel with .@) [14]unsigned int id_;
> root (cont'ed, cancel with .@) [15]double fX;
> root (cont'ed, cancel with .@) [16]double fY;
> root (cont'ed, cancel with .@) [17]double fZ;
> root (cont'ed, cancel with .@) [18]double fT;
> root (cont'ed, cancel with .@) [19]int itrack;
> root (cont'ed, cancel with .@) [20]unsigned int vtxId;
> root (cont'ed, cancel with .@) [21]unsigned int procType;
> root (cont'ed, cancel with .@) [22]}
> root [24] std::vector<SimVertex> test3;
> root [25] Events->SetBranchAddress("SimVertexs_g4SimHits__SIM.obj", &test3)
> Error in <TTree::SetBranchAddress>: The class requested (vector<SimVertex>) for the branch "SimVertexs_g4SimHits__SIM.obj" is an instance of an stl collection and does not have a compiled CollectionProxy. Please generate the dictionary for this collection (vector<SimVertex>) to avoid to write corrupted data.
> (int) -3
> 

So I guess this is an issue with the ROOT files themselves, rather than with uproot.

I close the issue for now and check back with the people who provided the files.
Thanks for your help (in particular the uproot.asdebug is very handy)!
