### ISSUE TITLE
Issue with JaggedArray

### ISSUE THREAD

**Issue by fmazzasc** [scikit-hep/uproot#232]
Hi, I have troubles in dealing with this tree using the latest version of uproot:
https://drive.google.com/open?id=1KWrBm_4UuEBNtgV1A8HZXooK4x8cM6RB
I don't know the reason why if I try to convert the variable : 'fDcaPos2PrimaryVertex'  I have success only if i type flatten=False. Otherwise the error message is: 'IndexError: index 431 is out of bounds for axis 1 with size 421' . 
This doesn't happen with other variables like 'fNsigmaHe3Pos'. 
For instance:
datatree=uproot.open('V0treeLocal.root')['fTreeV0']
df1=datatree.pandas.df(branches=['V0Hyper.fNsigmaHe3Pos'],flatten=True) #it works
df2=datatree.pandas.df(branches=['V0Hyper.fDcaPos2PrimaryVertex'],flatten=False) #it works
df3=datatree.pandas.df(branches=['V0Hyper.fDcaPos2PrimaryVertex'],flatten=True)  #Doesn't work

**Comment by jpivarski** [comment]
Thanks for pointing this out! It has been fixed by #233 and will be uproot 3.4.6, as soon as all tests pass.
