### ISSUE TITLE
reading/interpret std::map<std::string, double> 

### ISSUE THREAD

**Issue by Lucas-Borgna** [scikit-hep/uproot#243]
reading a branch that contains a std::map<std::string, double> element returns empty array with .allkeys() and error when accessing array values with .array()

ValueError: cannot interpret branch b'triggerMap' as a Python type

**Comment by jpivarski** [comment]
Yes, I haven't handled `std::map`, so this is the correct error: it doesn't know how to interpret the branch. If you give me a copy of the file, I can look into it, but I'll be busy for the next few weeks with a string of conferences. I can also guide you through the process, if you're up for it.

The first step is to look at the branch with `uproot.asdebug` as an interpretation. This shows you the bytes for each event. You might see your data in

```python
tree["triggerMap"].array(uproot.asdebug)[0].tostring()
```

If it looks fairly regular, it might be a short project. I've heard offhand that `std::map<K, V>` are encoded in ROOT as `std::vector<std::pair<K, V>>`, and `std::vector` is a 6-byte header, 4-byte size, and then the data. I don't know how `std::pair` is encoded.

**Comment by Lucas-Borgna** [comment]
you can find an example dataset here: 
https://cernbox.cern.ch/index.php/s/v9jYQNdrnljjw3o

I had a look at the debug stream and it does look like there is some regularity. I've attached text file with the output. It seems that the data comes in 3 cases: no strings passed, 1 string passed or both strings passed. 

[output.txt](https://github.com/scikit-hep/uproot/files/2932792/output.txt)

**Comment by jpivarski** [comment]
See PR #245; when all tests pass, I'll merge it and deploy it as uproot 3.4.11.

As it turns out, this was pretty easy. The layout is simply: 6-byte header, 4-byte size, alternation between key and value until we reach the total size. This fits well within the established framework, so I just had to introduce a class that knows about the alternation between key and value.

**Comment by Lucas-Borgna** [comment]
Hi @jpivarski. It seems that the new root version has broken the reading of the std::map from uproot. 
Here is an example file. I'm not really sure what the problem is but i can't seem to find the data with the asdebug key. Do you have any suggestions?

**Comment by jpivarski** [comment]
In this new version of ROOT, `std::map` has been split into a key branch and a column branch.

**Old:**

```
>>> t.show()
triggerMap                 TStreamerSTL             asgenobj(STLMap(STLString(),
                                                             asdtype('>f8')))
runNumber                  (no streamer)            asdtype('>i4')
eventNumber                (no streamer)            asdtype('>i8')
```

**New:**

```
>>> t.show()
triggerMap                 (no streamer)            asdtype('>i4')
triggerMap.first           (no streamer)            asgenobj(SimpleArray(STLString()))
triggerMap.second          (no streamer)            asjagged(asdtype('>f8'))

runNumber                  (no streamer)            asdtype('>i4')
eventNumber                (no streamer)            asdtype('>i8')
mcEventWeight              (no streamer)            asdtype('>f4')
```

PR #325 adds a rule to identify the first half of a split map as an array of strings (which is how it's laid out), so now `triggerMap.first` is essentially a jagged array of strings and `triggerMap.second` is a jagged array of values. You can turn any one of them into a map with

```python
>>> first = t["triggerMap.first"].array()
>>> second = t["triggerMap.second"].array()
>>> i = -1
>>> dict(zip(first[i], second[i]))

{b'HLT_2j35_bmv2c2060_split_2j35_L14J15.0ETA25': 1.0,
 b'HLT_j100_2j55_bmv2c2060_split': 1.0}
```

Maybe that's inconvenient? You could make them all be dicts-on-demand with

```python
>>> import awkward
>>> awkward.ObjectArray(awkward.JaggedArray.zip(awkward.fromiter(first), second),
                        lambda x: dict(zip(x.i0, x.i1)))

<ObjectArray [{} {} {} ... {} {} {b'HLT_2j35_bmv2c2060_split_2j35_L14J15.0ETA25': 1.0,
              b'HLT_j100_2j55_bmv2c2060_split': 1.0}] at 0x7f3c99777e80>
```

Or maybe you prefer accessing the keys and values independently.

**Comment by jpivarski** [comment]
This is now uproot 3.9.1.
