### ISSUE TITLE
problem in converting ROOT file to CSV

### ISSUE THREAD

**Issue by cleonido** [scikit-hep/uproot#248]
I am having problems converting this ROOT file:
http://cleonido.home.cern.ch/cleonido/private/nu_numu_1000_CCQE_12in_energy_studies_recoquant_tree_NEWlookupsB_for_training.root (about 100 MB)

to CSV with the attached python file: Only one row is saved in the output CSV file.

Any idea what I am doing wrong?

```
import numpy as np
import pandas as pd
import uproot

fname = 'nu_numu_1000_CCQE_12in_energy_studies_recoquant_tree_NEWlookupsB_for_training.root'
fileIn = fname
fileOut = fname
treename = 'nu_eneNEW'

print "Reading tree {} in file {}".format(treename, fileIn)
data = uproot.open(fileIn)[treename]

names = data.keys()

print ("Tree has the following branches:")
print ("  [{}]".format(', '.join(names)))

#data.arrays(names)
dfObj = pd.DataFrame.from_dict(data.arrays(names))
outfilename = fileOut.replace('.root', '.csv')
dfObj.to_csv(outfilename)
```

**Comment by jpivarski** [comment]
To understand that, you should print out the intermediate steps (and if you have, tell me the intermediate result, not the final result). Does `dfObj` have only one row? Or none? By "one row in the CSV", do you mean the names of the branches but not any of the data?

`pd.DataFrame.from_dict` has some limitations with regards to jagged data. You can make DataFrames directly with uproot, which works around some of these limitations:

```python
dfObj = data.pandas.df()
```

instead of

```python
dfObj = pd.DataFrame.from_dict(data.arrays(names))
```

**Comment by cleonido** [comment]
The ROOT file contains a tree that has 15 leaves, with 1762 entries (ie. events) per leaf. I don't think this counts as jagged data, but I could be wrong (I did not create the ROOT file btw).

dfObj has indeed one row with 26,430 columns (=15 x 1762), instead of 1762 rows and 15 columns, as expected. It seems that the last entry in the ROOT tree is repeated 1762 times in the CSV file.

Variable "names" has the same 15 names repeated 1762 times. 

Does this give you any hints?

**Comment by sbinet** [comment]
it would seem ROOT agrees with uproot (and groot):

```
root [1] auto t = (TTree*)_file0->Get("nu_eneNEW")
(TTree *) @0x7ffdd25715f0
root [2] t->GetEntries()
(long long) 1762
root [3] t->GetListOfBranches()->GetSize()
(int) 26430

```

**Comment by cleonido** [comment]
Not sure if there is something wrong with the ROOT file I am dealing with. I was able to write out a CSV file by unpacking the leaves and writing them out in a text file with an event loop.

Please feel free to close this issue.

**Comment by jpivarski** [comment]
It may be working, but it sounds like the file is not what you want. If ROOT, uproot, and groot all agree that the number of branches is 26430, somebody's making the file incorrectly. The fact that you can get the data you're looking for by iterating over all those branches doesn't mean this will still work when it scales up. Contact the author of that ROOT file.
