### ISSUE TITLE
Best way to produce an awkward.Table of tree arrays?

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/uproot#251]
I'm wondering what the best way to get a bunch of arrays from a tree and into an awkward.Table is?  

I can do:
```python
data = tree.arrays(branches, outputtype=awkward.Table)
```
but this produces column names of "0", "1", "2", etc, rather than the original branch names.

Alternatively, I can alternatively do:
```python
    data = tree.arrays(branches, outputtype=tuple)                                 
    data = awkward.Table({b: col for b, col in zip(branches, data)})
```
which gives me more meaningful column names, but it's an extra step, and somewhat unsightly.   

Is there any other option that I've missed?

**Comment by jpivarski** [comment]
duplicate!

**Comment by benkrikler** [comment]
Oh sorry! Github told me it hadn't gone through the first time!  Sorry!

**Comment by matthewfeickert** [comment]
@jpivarski You can actually [delete](https://help.github.com/en/articles/deleting-an-issue) these now as well if you want.

**Comment by jpivarski** [comment]
I saw how you rewrote the text from scratch.

**Comment by jpivarski** [comment]
> @jpivarski You can actually [delete](https://help.github.com/en/articles/deleting-an-issue) these now as well if you want, assuming you have admin control over scikit-hep.

Apparently, I don't have that power, though it doesn't matter to me.
