### ISSUE TITLE
Writing with uproot

### ISSUE THREAD

**Issue by beojan** [scikit-hep/uproot#255]
Is there any documentation anywhere on how to write trees with uproot? Both completely new trees, and simply adding branches to existing trees?

**Comment by jpivarski** [comment]
The ability to write trees is a feature to be added this summer. @reikdas is the developer, and many of the writing-related milestones are in the issues list; they're the oldest open issues labeled "writing-improvements."

**Comment by beojan** [comment]
Writing trees isn't already in that list. Maybe it should be?

**Comment by jpivarski** [comment]
Oh, those were clean-up things before the main summer project. "Add the ability to write TTrees" might be too large of an item for a single GitHub issue. Reik has a roadmap (submitted to IRIS-HEP, not GitHub) that we could perhaps split up into issues, but it would probably clutter the issue list.

This feature won't be forgotten about. It's a major project.
