### ISSUE TITLE
Index of tree.pandas.df doesnt use entrystart for flat arrays

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/uproot#256]
If `tree.pandas.df` is used with `entrystart > 0` and a jagged-array is one of the requested branches, then the resulting index (with the default `flatten=True` option) is a multindex with entry and subentry columns and entry values ranging  from `entrystart` to `entrystop`.  This is different to if only flat branches are requested, however, the index is just the row number going from `0` to `entrystop - entrystart`:

```python
In [0]: 
import uproot
tree = uproot.open("CMS_HEP_tutorial_ww.root")["events"]
```
```python
In [1]: tree.pandas.df(["NMuon", "NElectron"], entrystart=100, entrystop=200).head()
Out[1]: 
   NMuon  NElectron
0      1          0
1      1          0
2      1          0
3      1          0
4      1          0
```
```python
In [2]: tree.pandas.df(["NMuon", "Muon_Px"], entrystart=100, entrystop=200).head()
Out[2]: 
                NMuon    Muon_Px
entry subentry                  
100   0           1.0 -45.877728
101   0           1.0 -47.455692
102   0           1.0  54.362259
103   0           1.0 -30.484287
104   0           1.0   6.948876
```

I was wondering if we could be an optional argument that makes the index numbering the same in both cases?

I've had a look, and I think it would just require a couple of lines of extra code above [Line 109 of _connect/to_pandas.py](https://github.com/scikit-hep/uproot/blob/master/uproot/_connect/to_pandas.py#L109), using [pandas.RangeIndex.from_range](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.RangeIndex.from_range.html#pandas.RangeIndex.from_range) along the lines of:
```python
index = pandas.RangeIndex.from_range(range(startentry, stopentry))
```

If you think this would be reasonable to add, I'd be happy to put together a PR along these lines.

**Comment by jpivarski** [comment]
Thank you—that would be great. This definitely looks like an oversight. (The Pandas output code was revamped several times; it took us a while to learn how to use it properly.)

**Comment by benkrikler** [comment]
That was fast :zap: !  I'll try and open something.

**Comment by jpivarski** [comment]
You fixed this, I merged it, so I'll close this issue.
