### ISSUE TITLE
Uninterpreted fields in the CMS dark matter search dataset

### ISSUE THREAD

**Issue by imandr** [scikit-hep/uproot#26]
the following fields can not be interpreted in the "good old" CMS dark energy search dataset:

leaf element Info.triggerBits can not be interpreted
leaf element Electron.hltMatchBits can not be interpreted
leaf element Muon.hltMatchBits can not be interpreted
leaf element Tau.hltMatchBits can not be interpreted
leaf element Photon.hltMatchBits can not be interpreted
leaf element AK4CHS.hltMatchBits can not be interpreted
leaf element AK8CHS.hltMatchBits can not be interpreted
leaf element CA15CHS.hltMatchBits can not be interpreted
leaf element AK4Puppi.hltMatchBits can not be interpreted
leaf element CA8Puppi.hltMatchBits can not be interpreted
leaf element CA15Puppi.hltMatchBits can not be interpreted

uproot version is 2.3.3.
File is /data/ivm/root_data/MC/WZ_13TeV_pythia8/WZ_13TeV_pythia8_1.root

**Comment by jpivarski** [comment]
Right. I'm leaving this open because it's due to the fact that I haven't implemented the `std::bitset` interpretation yet, but intend to. We never managed to convert that to Avro, either.

**Comment by jpivarski** [comment]
Version 2.6.8 can read the `std::bitset<N>` and therefore everything from the old CMS dark energy search dataset. It's going through deployment now.
