### ISSUE TITLE
Underscores in branch/leaf names are not accepted

### ISSUE THREAD

**Issue by wdconinc** [scikit-hep/uproot#28]
It appears that underscores in branch names are not accepted. One tree I am trying to use uproot on has a field "run_data" which causes the error:  
```
/usr/local/lib/python3.5/dist-packages/uproot-2.4.1-py3.5.egg/uproot/rootio.py in <genexpr>(.0)
    554 
    555 def _safename(name):
--> 556     out = re.sub(b"[^a-zA-Z0-9]+", lambda bad: b"_" + b"".join(b"%02x" % ord(x) for x in bad.group(0)) + b"_", name).decode("ascii")
    557     if keyword.iskeyword(out):
    558         out = out + "__"

TypeError: ord() expected string of length 1, but int found
```

It seems to be caused by name = b"run_data". That indeed causes
```
In [16]: name = b"run_data"

In [17]: re.sub(b"[^a-zA-Z0-9]+", lambda bad: b"_" + b"".join(b"%02x" % ord(x) for x in bad.group(0)) + b
    ...: "_", name).decode("ascii")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-3b7fca76a1b8> in <module>()
----> 1 re.sub(b"[^a-zA-Z0-9]+", lambda bad: b"_" + b"".join(b"%02x" % ord(x) for x in bad.group(0)) + b"_", name).decode("ascii")
```
(etc)

A suggested fix is to add the underscore to the matching string, e.g.
```
re.sub(b"[^_a-zA-Z0-9]+", lambda bad: b"_" + b"".join(b"%02x" % ord(x) for x in bad.group(0)) + b"_", name).decode("ascii")
```

I am not sure, however, whether the underscore is also used for token separation within the ROOT file format.

Relevant line in rootio.py is https://github.com/scikit-hep/uproot/blob/8eabb7ccc6de7f9ac87c9a4f6141de1c318736a6/uproot/rootio.py#L556

**Comment by jpivarski** [comment]
Could you try this again? I just released the fix for #30 on [PyPI as 2.5.2](https://pypi.python.org/pypi/uproot/). (pip install or git clone)

**Comment by wdconinc** [comment]
This particular error appears resolved (but another exception raised, NotImplementedError: 7). I suspect it is unrelated and I will file a different report. If you think so too, please go ahead and close.

**Comment by jpivarski** [comment]
Yes, that's unrelated: open a new issue.

Would it be possible to make a test file? I left a few streamer interpretation cases unimplemented because I needed to see an example of how it should be interpreted before proceeding.

The test file can contain a single-event TTree if the data are sensitive. That should hide the physics content pretty well and keep the file size small enough to post.

Thanks!
