### ISSUE TITLE
Interpret std::vector<std::string>

### ISSUE THREAD

**Issue by kpedro88** [scikit-hep/uproot#32]
Can provide example ROOT file on request, but at the moment don't have one that I'd like to post publicly.

**Comment by jpivarski** [comment]
It looks like I already have an example to use for testing:

```python
uproot.open("tests/samples/small-evnt-tree-fullsplit.root")["tree"]["StlVecStr"]
```

So I won't need a specially prepared file. Thanks!

**Comment by jpivarski** [comment]
Done (in 2.6).
