### ISSUE TITLE
Issues reading some TRef arrays

### ISSUE THREAD

**Issue by HenryDayHall** [scikit-hep/uproot#329]
To start with thank you so much for implementing TRef reading, it's been amazing. 
I have almost finished refactoring to get rid of all my previous work arounds.

One thing that doesn't quite work yet is the TRefs that appear in Towers.
One Tower is created by the energy deposits of multiple particles, so each tower gets a list of references (might be a TRefArray object, not quite sure...).

In the same root file as last time (https://mega.nz/#F!afB2SSwC!3C8bp5xY_d01VvXmkh1nJQ);
event_n|tower_n|particle_n
0|0|[1413, 1417, 1470, 1570]
0|1|[1446]
0|2|[1571]
0|3|[1763]
0|4|[1568]
...
As you can see the first tower is linked to 4 particles.

A minimal broken example of this would be;
```
import uproot
file_name = "/path/to/h1bBatch2.root"
root_file = uproot.open(file_name)['Delphes']
problem_array = root_file.array('Tower.Particles')
print(problem_array)  # expected a list of TRef objects. Possibly a TRefArray?
# error! see below
```
The error message I get from this is at the bottom (but I'm not sure how informative it is).

Thanks again for all your work on this.
- Henry

P.S. the error message;
```
Traceback (most recent call last):
  File "minimal_error.py", line 5, in <module>
    print(problem_array)  # expected a list of TRef objects. Possibly a TRefArray?
  File "/usr/local/lib/python3.6/dist-packages/awkward/array/base.py", line 103, in __str__
    return "[{0} ... {1}]".format(" ".join(self._util_arraystr(x) for x in first), " ".join(self._util_arraystr(x) for x in last))
  File "/usr/local/lib/python3.6/dist-packages/awkward/array/base.py", line 103, in <genexpr>
    return "[{0} ... {1}]".format(" ".join(self._util_arraystr(x) for x in first), " ".join(self._util_arraystr(x) for x in last))
  File "/usr/local/lib/python3.6/dist-packages/awkward/array/objects.py", line 178, in __iter__
    yield self.generator(x, *self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/uproot/interp/objects.py", line 298, in __call__
    return self.cls.read(source, cursor, self.context, None)
  File "/usr/local/lib/python3.6/dist-packages/uproot/interp/objects.py", line 28, in read
    out.append(self.cls.read(source, cursor, context, parent))
  File "/usr/local/lib/python3.6/dist-packages/uproot/rootio.py", line 867, in read
    out = cls._readinto(out, source, cursor, context, parent)
  File "<generated from TStreamerInfo b'TRefArray' at 0x7fe2004b4b00>", line 29, in _readinto
  File "<generated from TStreamerInfo b'TSeqCollection' at 0x7fe200497eb8>", line 25, in _readinto
  File "/usr/local/lib/python3.6/dist-packages/uproot/rootio.py", line 1418, in read
    out = cls._readinto(out, source, cursor, context, parent)
  File "/usr/local/lib/python3.6/dist-packages/uproot/rootio.py", line 1428, in _readinto
    raise TypeError("cannot read objects of type {0} and cannot even skip over this one (returning Undefined) because its size is not known\n  in file: {1}".format("???" if self._classname is None else self._classname.decode("ascii"), context.sourcepath))
TypeError: cannot read objects of type ??? and cannot even skip over this one (returning Undefined) because its size is not known
  in file: /home/henry/lazy/dataset2/h1bBatch2.root
```

**Comment by jpivarski** [comment]
See PR #303, to be uproot 3.9.3.

I've added an explicit `TRefArray` implementation so that you can do this:

```
>>> t["Tower.Particles"].array()
<ObjectArray [[[1414, 1418, 1471, 1571], [1447], [1572],
              ...,
              [864, 1325], [992, 1437], [1262, 1501]]] at 0x7f5a6f1f3b00>
```

Note that this is an `ObjectArray` (of `TRefArray` objects, which inherit from Python's `list` class) because of the way that ROOT serializes doubly nested lists of things. For the selection-with-square-brackets that makes TRefs useful, you might need this to be a `JaggedArray` of `JaggedArrays`.

To do that, pass it through `awkward.fromiter`:

```
>>> import awkward
>>> a = awkward.fromiter(t["Tower.Particles"].array())
<JaggedArray [[[1414 1418 1471 1571] [1447] [1572] 
               ...
               [864 1325] [992 1437] [1262 1501]]] at 0x7f5a6a014ef0>
```

Since `TRefArray` inherits from `list`, you'd be able to use it as a selection in square brackets, but only in a loop over events. With a `JaggedArray` of `JaggedArrays`, you might be able to avoid the event loop.

But given that you have a large number of particles in each event ("wider" data, rather than "taller"), you might not care. Anyway, the tools are now at your disposal.

Cheers!
