### ISSUE TITLE
NameError: global name 'data' is not defined

### ISSUE THREAD

**Issue by kpedro88** [scikit-hep/uproot#34]
In these two histogram functions, the argument is `datum` but the code inside refers to `data`:
https://github.com/scikit-hep/uproot/blob/8032dae00c89e643690dbf9dc22913e75331db39/uproot/hist.py#L123-L143

It should be made consistent to avoid undefined variable errors.

**Comment by jpivarski** [comment]
It's consistent now: `datum` is always one scalar value and `data` is always a collection of them (usually Numpy array).
