### ISSUE TITLE
Masking of JaggedArray does not seem to work

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#349]
I have a simple tree with two levels.
```
******************************************************************************
*Tree    :ana       : Units: mm and GeV                                      *
*Entries :   691422 : Total =       328096439 bytes  File  Size =  251965226 *
*        :          : Tree compression factor =   1.30                       *
******************************************************************************
*Br    0 :evt_bxtype : evt_bxtype/B                                          *
*Entries :   691422 : Total  Size=     692797 bytes  File Size  =      90391 *
*Baskets :       11 : Basket Size=      78848 bytes  Compression=   7.66     *
*............................................................................*
*Br    1 :vtx_len   : vtx_len/S                                              *
*Entries :   691422 : Total  Size=    1384362 bytes  File Size  =     290897 *
*Baskets :       13 : Basket Size=     157696 bytes  Compression=   4.76     *
*............................................................................*
*Br    2 :vtx_x     : vtx_x[vtx_len]/F                                       *
*Entries :   691422 : Total  Size=    4919576 bytes  File Size  =    1877942 *
*Baskets :       44 : Basket Size=     574976 bytes  Compression=   2.62     *
*............................................................................*
*Br    3 :vtx_y     : vtx_y[vtx_len]/F                                       *
*Entries :   691422 : Total  Size=    4919576 bytes  File Size  =    1915784 *
*Baskets :       44 : Basket Size=     574976 bytes  Compression=   2.57     *
*............................................................................*
*Br    4 :vtx_z     : vtx_z[vtx_len]/F                                       *
*Entries :   691422 : Total  Size=    4919576 bytes  File Size  =    2664929 *
*Baskets :       44 : Basket Size=     574976 bytes  Compression=   1.85     *
*............................................................................*
```
There are branches like `evt_bxtype`, which have one value per event. And there are Branches with VLEN arrays, which contain a variable number of values per event.

A typical use-case is to do something with the contents of a branch with VLEN arrays, but only for events which pass some condition on `evt_bxtype`. In ROOT, one does something like this:
```
tree->Draw("vtx_z", "evt_bxtype==3")
```

When I try this with uproot, I find that JaggedArrays cannot be masked along the first dimension.

```
f = uproot.open(somefile)
tree = f["tree"]
vtx_z = tree["vtx_z"].array() # a JaggedArray
evt_bxtype = tree["evt_bxtype"].array() # normal array

vtx_z[evt_bxtype == 3] # does not work
```
Is there a way to achieve this that I missed?

**Comment by HDembinski** [comment]
This works as a workaround, but it would be nice if masking was supported directly in JaggedArray.
```
def select(jarray, mask):
    @njit
    def impl(starts, stops, data, mask):
        result = []
        for i, m in enumerate(mask):
            if m:
                for j in range(starts[i], stops[i]):
                    result.append(data[j])
        return np.array(result)

    return impl(jarray.starts, jarray.stops, jarray.content, mask)
```

**Comment by jpivarski** [comment]
```python
vtx_z[evt_bxtype == 3]
```

is how you're supposed to do it and that absolutely should work.  I see that the number of entries is the same in `vtx_z` and `evt_bxtype`, so there is no reason this shouldn't work. What's the error message? Can you give me these arrays so I can try it?

**Comment by HDembinski** [comment]
# Example to reproduce

[tree.zip](https://github.com/scikit-hep/uproot/files/3662578/tree.zip)
```
import uproot
import numpy as np
import sys

f = uproot.open("tiny_sample.root")
ana = f["ana"]

evt_bxtype = ana["evt_bxtype"].array()
vtx_z = ana["vtx_z"].array()

np.histogram(vtx_z[evt_bxtype == 3])
```

```
Traceback (most recent call last):
  File "bar.py", line 11, in <module>
    np.histogram(vtx_z[evt_bxtype == 3])
  File "<__array_function__ internals>", line 6, in histogram
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/histograms.py", line 785, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/histograms.py", line 419, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/histograms.py", line 314, in _get_outer_edges
    first_edge, last_edge = a.min(), a.max()
  File "/usr/local/lib/python3.7/site-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: operands could not be broadcast together with shapes (0,) (3,)
```

**Comment by HDembinski** [comment]
Could be related to #323

**Comment by jpivarski** [comment]
I'll try it, but I think that `vtx_z[evt_bxtype == 3]` works: try it outside the call to `numpy.histogram`.

`numpy.histogram` takes a flat array; `vtx_z[evt_bxtype == 3]` gives you a jagged array of tracks with some events dropped. The way to turn it into a flat array for histogramming is to pass `.flatten()`. So the full example should be:

```python
np.histogram(vtx_z[evt_bxtype == 3]).flatten()
```

(I don't want jagged arrays to implicitly lose their structure when passed through `__array__`. There are too many ways that could go wrong. Therefore, the explicit flattening is needed.)

**Comment by HDembinski** [comment]
You are right, that makes sense. Could an example which illustrates this point be added to the tutorial?

**Comment by HDembinski** [comment]
> (I don't want jagged arrays to implicitly lose their structure when passed through __array__. There are too many ways that could go wrong. Therefore, the explicit flattening is needed.)

Although the Numpy approach seems to be: "convert as much as needed to make the call work".

**Comment by jpivarski** [comment]
The uproot tutorial would get out of hand if it covered awkward-array as well. Do you know about the [awkward-array tutorial](https://github.com/scikit-hep/awkward-array#readme)?

I need to find a better solution for documentation. The reason these two projects have exceedingly long pages is that information distributed throughout readthedocs was rarely found by users. One long page is searchable with command-F. But there has to be some scope limit—we can't put everything about everything on one page.

At PyHEP, I'm going to try to start a movement to posting questions on StackOverflow, where I'll monitor a set of tags like "uproot" and "awkward". For non-HEP things, I've found that to be the best way to find information (usually better than any project's own documentation).

About the Numpy approach: there are a few things we need to break with. Awkward-arrays can be trees of records with fields like `pt` and `eta`—it would be confusing if that somehow turned into an array. In fact, I have a counterexample: I was just working with Pandas in another window and it complained when I wanted to make a histogram of dates because some of the dates (the ones I had masked out) were `None` and therefore the array dtype was `O`. I had to explicitly convert it. It's not unheard-of, once you start working with non-numeric data.

**Comment by HDembinski** [comment]
I like the docs in the README.md, even if the page is long. It is simple and effective.

I am not saying you should repeat the full awkward array tutorial, but my use case is common and therefore I think the tutorial for uproot should include this point. Also, the error message when you do it wrong is very unhelpful and doesn't point to the root cause.

**Comment by HDembinski** [comment]
I would suggest to either produce a better error message (if possible) or to include an example in the tutorial.

**Comment by jpivarski** [comment]
I'm now working on a bunch of uproot/awkward issues; this among them. There will be an example in the README about histogramming and a mention of TChain.
