### ISSUE TITLE
Write TTrees with Jagged Array data

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/uproot#354]

**Comment by HDembinski** [comment]
Hi, I am currently working on a project where we need this functionality, so I am very interested in this feature. Is it possible to give an estimate when this will be available?

**Comment by reikdas** [comment]
I started looking at it today. I am not very good at estimating how difficult something is to implement, but this feature shouldn't be too hard. So.. perhaps in a week.

**Comment by HDembinski** [comment]
Cool!

**Comment by jpivarski** [comment]
I'm going to deploy this feature in Uproot 3.11.4 as soon as the tests are done.
