### ISSUE TITLE
Reading TEfficiency objects

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot#364]
Currently, there's a `NotImplementedError` (untested by me; need to triage).

**Comment by jpivarski** [comment]
Nobody has asked for it.

**Comment by jbeirer** [comment]
Hi @jpivarski,

are there any plans on implementing this?

Cheers,
Joshua

**Comment by jpivarski** [comment]
There aren't any plans as yet, but if there were, it would be in Uproot 4.

You can help me enormously by supplying a small, public file with a TEfficiency in it that has all the features that you need (title, special metadata, etc.), then open it in Uproot 4:

```python
import uproot4
file = uproot4.open("the-file.root")
teff = file["path/to/teff"]
print(teff.all_members)
print(teff.member("fWhatever")
```

Let me know if it's unreadable at this level, because that would be a bug (Uproot 4 GitHub Issues). If it can be read, but the only way to get at the data of interest is through `teff.member("fWhatever")`, let me know which members are important to you and we can add special accessor methods and properties like the ones here:

https://github.com/scikit-hep/uproot4/blob/master/uproot4/behaviors/TH2.py

The general strategy will be to add methods that _extract_ data, rather than making an `uproot4.behavior.TEfficiency.TEfficiency` a generally useful object in itself. The appropriate target for conversion may be in the [boost-histogram](https://github.com/scikit-hep/boost-histogram) library or the [hist](https://github.com/scikit-hep/hist) library.

Thanks!

**Comment by jbeirer** [comment]
Hi @jpivarski,

indeed this does not seem to be readable at this point so I opened an issue [here](https://github.com/scikit-hep/uproot4/issues/209).

Cheers,

Joshua
