### ISSUE TITLE
Problems with identifying the type of a ROOT object

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/uproot#376]
It seems unnecessarily difficult to figure out what an object's type is once read from a ROOT file. I often want to open a ROOT file and then scan across the TKeys to find the one(s) that corresponds to a TTree, for example. But this is what I run into with uproot:

```python
>>> import uproot
>>> file = uproot.open('run0.root')
>>> tree = file.values()[0]
>>> type(tree)
<class 'uproot.rootio.TTree'>
>>> isinstance(tree, uproot.rootio.TTree)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'uproot.rootio' has no attribute 'TTree'
```

I can do this:

```python
>>> isinstance(tree, uproot.tree.TTreeMethods)
True
```

but there's no intuitive reason to check TTreeMethods unless I dig into the documentation and eventually find that TTrees are a subclass of it.

It would be slightly better if I could do this:

```python
>>> tree._classname == 'TTree'
False
```

...but that also fails because I need to check against a byte literal:

```python
>>> tree._classname           
b'TTree'
>>> tree._classname == b'TTree'
True
```

which is also very non-intuitive.

Is there a way to make something like `isinstance(tree, uproot.TTree)` work, or to make `tree._classname == 'TTree'` work, or both? Why doesn't `uproot.open()` have a `namedecode` option like `arrays()`?

**Comment by jpivarski** [comment]
It's also important to be able to identify the type of an object without reading it (i.e. to decide whether you want to read it). For that, there's `classes` as an alternative to `items`.

The Python class ones for each C++ class might already have a type name string (attached to the object itself), though I hadn't thought that it should be user-accessible. Maybe that should be exposed as a `classmethod` (what should the name be?).

The bytes-to-Unicode conversion and C++-to-Python name conversion are done at the same time—C++ names (with possible `[<>:]` characters) are raw bytes read from the ROOT file and Python names (pure `[a-zA-Z_][a-zA-Z_0-9]` and `str` type) are used as actual class names, converting `[<>:]` to distinct sequences (by losing `_` as an unencoded character). It sounds like you want Unicode names without the `[<>:]` translation.

Suggest an economic solution as a PR.

**Comment by masonproffitt** [comment]
I think all I really want is `._classname`, but without having to worry about byte literals (and maybe being able to drop the underscore). Is there any reason why the class name shouldn't just always be a normal string? A further frustrating thing is that some classes give a byte literal and some give a string:
```python
>>> import uproot
>>> file = uproot.open('run0.root')
>>> file._classname
b'TDirectory'
>>> file.values()[0]._classname
b'TTree'
>>> file.values()[1]._classname
'TNamed'
```

**Comment by jpivarski** [comment]
This still requires you to read an object before knowing what type it is, which I consider to be a liability.

But anyway, I am suggesting that you make the interface you would like to see as a PR. To get `classname` as a no-underscore string, add a property that does the encoding to `uproot.rootio.ROOTStreamedObject`. Don't change the underscored member—it's needed internally, just as a property or method view.

**Comment by jpivarski** [comment]
I think this is done. I see a merged PR here. Let me know if I'm wrong.
