### ISSUE TITLE
Default output types of arrays() and lazyarrays() are different

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/uproot#377]
Example:
```python
>>> import uproot
>>> file = uproot.open('run0.root')
>>> tree = file.values()[0]
>>> type(tree.arrays())
<class 'dict'>
>>> type(tree.lazyarrays())
<class 'awkward.array.table.Table'>
```

This is quite surprising and confusing. They should both return the same type. It doesn't matter as much to me which one, although I'd have a preference for `Table` since it can also be subscripted by row.

**Comment by jpivarski** [comment]
This is the way it's supposed to be. `arrays` should return minimal custom types, and it gives the user control over the container (`containertype`). `lazyarrays`, however, already assumes custom types (lazy arrays) and if we returned it with something that calls `__repr__` on the contents when printing itself—true for nearly every container type in Python—then the lazy arrays would be materialized just by looking at them.

That wasn't a historical accident or a design gaffe—it was intended. I believe there are real differences in user-friendliness on a large scale, but when you get down to a small scale of difference, the relative choices get lost in the noise of subjectivity.
