### ISSUE TITLE
Convert a table into a dict of Jagged arrays

### ISSUE THREAD

**Issue by nfoppiani** [scikit-hep/uproot#378]
This issue is mainly a question.
I would like to know how I can convert a table
obtained with this code `uproot.open(root_filename)[tree].lazyarrays()` 
into a dict of Jagged arrays
obtained normally with this code `uproot.open(root_filename)[tree].arrays()`.
This is because I would like to consider a table, compute a function that produces a mask (a vector of True or False with length equal to the number of rows of the table), and then create a dict of Jagged arrays without the masked rows.

This is because I need to run functions that would produce new jagged arrays (or new columns, if we think about tables), which are not applicable on all rows but only on those for which the mask is True.

Additionally, I also realised that executing operations with the dict of arrays is faster than with the table, is it expected?

**Comment by jpivarski** [comment]
You can do this:

```python
{n: a[n] for n in a.columns}
```

for some jagged array `a` containing a `Table`. Each `a[n]` is a zero-cost projection through the structure (one of the advantages of a columnar format).

There are also `MaskedArray` techniques to produce filtered arrays that have the same length as the original, but maybe try this first.

**Comment by jpivarski** [comment]
If I remember right, ufuncs applied to a MaskedArray are only computed for the unmasked elements. They're less often used than jagged arrays and tables, but @nsmith- has had some success with them.

**Comment by nsmith-** [comment]
For example, this emits no `RuntimeWarning`s:
```python
import awkward, numpy as np
a = np.random.normal(size=100)
ma = awkward.MaskedArray(a<0, a)
np.sqrt(ma)
```
However, it copies the (valid subset) array under-the-hood.  An old issue is to use the (somewhat new) numpy ufunc where argument: https://github.com/scikit-hep/awkward-array/issues/110

**Comment by jpivarski** [comment]
I think this is done and can be closed. Let me know if I'm wrong!
