### ISSUE TITLE
Possible bug in uproot.iterate

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#394]
I noticed in a script of mine that `uproot.iterate` to iterate over some files twice in a row in the same script does not work. The second time it does not actually iterate. I am not sure how to make a minimal example to demonstrate this.

**Comment by HDembinski** [comment]
Pseudo code:
```
import uproot

files = ...

for data in uproot.iterate(files, "tree", ["branch1"]):
    # do something

# the second for loop does not actually iterate
for data in uproot.iterate(files, "tree", ["branch1"]):
    # do something again

```

**Comment by HDembinski** [comment]
Never mind, this looks like my mistake. I accidentally used a generator to create `files`, which obviously is exhausted when called a second time.

**Comment by jpivarski** [comment]
Okay, good—that had me baffled for a second.
