### ISSUE TITLE
error in the docs

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#395]
https://uproot.readthedocs.io/en/latest/opening-files.html#uproot-pandas-iterate

The :py:func\`uproot.pandas.iterate <uproot.pandas.iterate>\` function is like the above, except that it iterates over Pandas DataFrames (as though you passed outputtype=pandas.DataFrame and changed some defaults).

**Comment by jpivarski** [comment]
Noted! I had intended to deal with this earlier, but haven't. Thanks for raising it.

**Comment by HDembinski** [comment]
It just came to my attention... if you find mistakes in my docs, please point them out, too :)
