### ISSUE TITLE
Reading data using lazyarray()

### ISSUE THREAD

**Issue by zinebaly** [scikit-hep/uproot#398]
Data file from issue #390 

I was able to access data from hits as a jagged array, while for 'trks' it is not possible for some specific cases. Here is how I proceed for these cases: 
    
    tree = uproot.open(my_file)['E']
    tree["trks.rec_stages"].interpretation

the output is:
    asjagged(asdtype('>i4'), 10)

then:

    tree.array("trks.rec_stages")

I get the following error:

    ValueError: could not broadcast input array from shape (15713) into shape (15711)

I always get the error above with ('trks.rec_stages', 'trks.error_matrix', 'trks.fitinfo') using tree.array() .

But when I try this:

    lazy_rec_stages = tree.lazyarray("trks.rec_stages")

I get my data as the following: 

    <ChunkedArray [[1 3 5 ... 1 1 1] [1 3 5 ... 1 1 1] [1 3 5 ... 1 1 1] ... [1 3 5 ... 1 1 1] [1 3 5 ... 1 1 1] [1 3 5 ... 1 1 1]] at 0x7f4dabe12450>

Except that data in each array of lazy_rec_stages read with uproot doesn't seem to have conserved the "structure" of data from the original root file. To illustrate this, I will use the following example:
if we look at an event, for each event we have an associated number of tracks, each track has reconstruction stages info stored in rec_stages and a likelihood stored in trks.lik: 

    event       trks         trks.rec_stages        trks.lik
     0           0            "1 2 3"                 10
                 1            "4 5"                   20   
                 2            "6 7 8 9"               30

So one would expect: 

    tree.lazyarray("trks.rec_stages")[0][0]
    Output: "1 2 3 5 4" 
    tree.lazyarray("trks.lik")[0][0] 
    Output: 10

But I am not sure that it is the case, here is what I get:

    tree.lazyarray("trks.rec_stages")[0][0]
    Output: [1 2 3 4 5 6 7 8 9]

Which makes it difficult to associate which rec_stages corresponds to which trks. Could you please tell me what I am doing wrong here? 

When I try the following for "trks.error_matrix", I get the following: 

    tree.lazyarray("trks.error_matrix")
    AssertionError: 

PS: I think I am using the latest version of uproot.

Thank you for your time and consideration.
@tamasgal

**Comment by jpivarski** [comment]
**Can't reproduce:** I did a fresh install of [uproot 3.10.10](https://pypi.org/project/uproot/3.10.10/) and accessed [issue390.root](https://github.com/scikit-hep/uproot/blob/master/tests/samples/issue390.root) with no issues:

```python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> f = uproot.open("~/irishep/uproot/tests/samples/issue390.root")
>>> t = f["E"]
>>> t["trks.rec_stages"].interpretation         # it's important that this is different from what you see!
asgenobj(SimpleArray(STLVector(asdtype('>i4'))))
>>> t.array("trks.rec_stages")                  # array or lazyarray; I'm looking at the simpler one first
<ObjectArray [[[1, 3, 5, 4], [1, 3, 5], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3]
...
```

The uproot version is the key thing. You're reporting the error that I discovered when first looking at your file. It was an error in interpreting vectors within the vector of split objects; your earlier PR prompted me to fix it then.
