### ISSUE TITLE
uproot.iterate over file containing TBranchElements fails with Attribute Error

### ISSUE THREAD

**Issue by rprechelt** [scikit-hep/uproot#406]
I have a ROOT file that contains a class (consisting of basic types) that I can access with uproot just fine. The class is called `event` and stored in an `eventTree` TTree.

    # this works perfectly to access the `eventNumber` attribute of `event`
    >>> f = uproot.open('events.root')
    >>> f['eventTree']
    <TTree b'eventTree' at 0x7f6b92e96048>
    >>> f['eventTree/event']
    <TBranchElement b'event' at 0x7f6c20e97a20>
     >>> f['eventTree/event/eventNumber']
     <TBranchElement b'eventNumber' at 0x7f6c20e979b0>
     >>> f['eventTree/event/eventNumber'].array()
     array([14402301, 14402302, 14402303, ..., 14627676, 14627677, 14627678],
               dtype=uint32)

However, I am trying to repeat this using `uproot.iterate` to iterate over a large number of files and am getting an error. 

My first attempt was:

    for _ in uproot.iterate(['events.root'], treepath='eventTree/event', branches=[b'eventNumber']:
         pass

which gives an `AttributeError`

```
~/.local/lib/python3.6/site-packages/uproot/tree.py in iterate(path, treepath, branches, entrysteps, outputtype, namedecode, reportpath, reportfile, reportentries, flatten, flatname, awkwardlib, cache, basketcache, keycache, executor, blocking, localsource, xrootdsource, httpsource, **options)
    110 def iterate(path, treepath, branches=None, entrysteps=float("inf"), outputtype=dict, namedecode=None, reportpath=False, reportfile=False, reportentries=False, flatten=False, flatname=None, awkwardlib=None, cache=None, basketcache=None, keycache=None, executor=None, blocking=True, localsource=MemmapSource.defaults, xrootdsource=XRootDSource.defaults, httpsource=HTTPSource.defaults, **options):
    111     awkward = _normalize_awkwardlib(awkwardlib)
--> 112     for tree, newbranches, globalentrystart, thispath, thisfile in _iterate(path, treepath, branches, awkward, localsource, xrootdsource, httpsource, **options):
    113         for start, stop, arrays in tree.iterate(branches=newbranches, entrysteps=entrysteps, outputtype=outputtype, namedecode=namedecode, reportentries=True, entrystart=0, entrystop=tree.numentries, flatten=flatten, flatname=flatname, awkwardlib=awkward, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking):
    114 

~/.local/lib/python3.6/site-packages/uproot/tree.py in _iterate(path, treepath, branches, awkward, localsource, xrootdsource, httpsource, **options)
    162         except KeyError:
    163             continue
--> 164         listbranches = list(tree._normalize_branches(branches, awkward))
    165 
    166         newbranches = OrderedDict((branch.name, interpretation) for branch, interpretation in listbranches)

AttributeError: 'TBranchElement' object has no attribute '_normalize_branches'
```
The next method was: 

    for _ in uproot.iterate(['events.root'], treepath='eventTree', branches=[b'event/eventNumber']:
         pass

which returns `KeyError: not found: b'event/eventNumber'`.

Is this possible? If not, it might be worth adding a catch/check in iterate to avoid presenting a mysterious `_normalize_branches` to the user.

**Comment by jpivarski** [comment]
You using it in a different way than I had imagined, so now I have to decide whether it should be allowed. When you said

```python
>>> f['eventTree/event']
<TBranchElement b'event' at 0x7f6c20e97a20>
```

I wondered, you can get a branch as though a tree where a subdirectory? Then I thought about it, about how get item has been implemented, and I guess that would work by unintended duck typing.

It's used in the iterate function is not as lenient. The `treepath` string should be a path through subdirectories only (no slash in your case). The branch names that you put in the list of branches don't have to be at top level, it can be any descendants of branch. Therefore, you should be able to do this:

```python
for _ in uproot.iterate(['events.root'], treepath='eventTree', branches=[b'eventNumber']:
    pass
```

Recursively nested branches sometimes have their parent names prefixed with a dot, so try that. As long as you're starting from the tree object, the same thing will work in the `arrays` method as the `iterate` function.

**Comment by rprechelt** [comment]
Thanks for the incredibly quick response! 

Your recommended method of just specifying the branch name (as opposed to the full path) worked perfectly.

Thanks for your help!
