### ISSUE TITLE
Trouble with reading data in one shot -> ValueError: entries in recovered baskets ... don't add up to total number of entries

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/uproot#407]
I am about to finalise a library which uses `uproot` to read all of our ROOT formats (both DAQ and MC!) and only a few things are missing. Many thanks for your help so far!

One of the trickiest ones was reading the events, but with your help and fixes it works nicely and I wrapped it into a user-friendly API: https://github.com/scikit-hep/uproot/issues/124#issuecomment-423316496

Now I am struggling with reading the remaining parts of the DAQ dataformat, namely timeslices and summary slices (allow me to open separate issues if needed) which are stored in this file: https://github.com/KM3NeT/km3io/blob/master/tests/samples/jpp_v12.0.0.root (open access)

I am quite confused about the long chain of lookups I need to make, because I find repeated data, but anyways, this is how it looks like when I try to read timeslice data, which basically consists of `n` headers, `n` superframes and `m` frames in each superframe. In the sample file `n=3` and `m=69`. The superframe contains the hit-level data:

Here I am just trying to read the header:

```
>>> f = uproot.open("jpp_v12.0.0.root")
>>> tree = f["KM3NET_TIMESLICE_L1"]
>>> tree.keys()
[b'km3net_timeslice_L1']
>>> tree[b'km3net_timeslice_L1'][b'KM3NETDAQ::JDAQTimeslice'].keys()
[b'KM3NETDAQ::JDAQPreamble',
 b'KM3NETDAQ::JDAQTimesliceHeader',
 b'vector<KM3NETDAQ::JDAQSuperFrame>']
>>> tree[b'km3net_timeslice_L1'][b'KM3NETDAQ::JDAQTimeslice'][b'KM3NETDAQ::JDAQTimesliceHeader'][b'KM3NETDAQ::JDAQHeader'][b'KM3NETDAQ::JDAQChronometer'].keys()
[b'detector_id',
 b'run',
 b'frame_index',
 b'timeslice_start.UTC_seconds',
 b'timeslice_start.UTC_16nanosecondcycles']
```

This looks a bit weird, but I get access to the data!

```
>>> tree[b'km3net_timeslice_L1'][b'KM3NETDAQ::JDAQTimeslice'][b'KM3NETDAQ::JDAQTimesliceHeader'][b'KM3NETDAQ::JDAQHeader'][b'KM3NETDAQ::JDAQChronometer'][b'frame_index'].array()
array([512, 509, 514], dtype=int32)
```

Funnily, I get access to the same data when I directly query `b['frame_index']` on `tree[b'km3net_timeslice_L1']`:

```
>>> tree[b'km3net_timeslice_L1'][b'frame_index'].array()
array([512, 509, 514], dtype=int32)
```

**My first question is**: how do I get an  `ndarray` of this headers in one-shot? I mean, I can read every "sub"-array manually and compose a `recarray` or so, but I am sure there is a trick to read it in whole.

I first tried with:

```
>>> tree[b'km3net_timeslice_L1'].array()
...
ValueError: entries in recovered baskets (offsets [0]) don't add up to total number of entries (3)
```

I also tried to understand what you did in the previous issue and passed in the dtypes, but I get the same error, things like this (and different variations, also providing the full "path"):

```
>>> tree[b'km3net_timeslice_L1'].array(
    uproot.asdtype(
        [("det_id", "i4"),
         ("run", "i4"),
         ("frame_index", "i4"),
         ("seconds", "i4"),
         ("ns_cycles", "i4")]
    )
)
)))
```

**My second question (might be another issue, but it's basically the same problem) targets the frames themselves, the actual frames data:**

```
>>> frames = tree[b'km3net_timeslice_L1'][b'KM3NETDAQ::JDAQTimeslice'][b'vector<KM3NETDAQ::JDAQSuperFrame>']
>>> frames.keys()
[b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQPreamble',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.detector_id',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.run',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.frame_index',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.timeslice_start.UTC_seconds',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.timeslice_start.UTC_16nanosecondcycles',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.daq',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.fifo',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status_3',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status_4',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.numberOfHits',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer']
```

That's already nice and I can access most of them easily, but also here only in parts:

```
>>> frames[b'vector<KM3NETDAQ::JDAQSuperFrame>.numberOfHits'].array()
<JaggedArray [[984 1004 251 ... 863 809 726] [1004 1074 231 ... 886 949 738] [976 902 321 ... 865 825 732]] at 0x7f0ede7d5d10>
```

When I try to read everything as a big array (I'd prefer a lazy ragged one, but here I only tried `array`):

```
>>> frames.array()
[60]:
array([69, 69, 69], dtype=int32)
```

I get the lengths of the superframes. Maybe it's also related, I have troubles reading `b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier',`:

```
>>> frames[b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier'].array()
...
ValueError: cannot interpret branch b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier' as a Python type
```

I tried to use the `interpret` but it yields the same error:

```
>>> frames[b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier'].array(
                uproot.interpret(frames[b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier'],
                                 cntvers=True))
...
ValueError: cannot interpret branch b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier' as a Python type
```

And one big issue is still: I could not find the actual hit data yet. There has to be some (in this case 69) vectors of `snapshotHits` or alike in each superframe, with fields `tdc`, `tot` etc... 😕

**Comment by jpivarski** [comment]
This is a lot of questions—hard to know where to begin. First, the error message quoted in the title: it's misleading and I've been thinking of going in and preventing it from being shown. There's a technical issue in which some ROOT files have baskets in a different place because they were closed early; this correction happens without telling the user. After "recovering" these baskets, the number of entries in all the discovered baskets should add up to the number of entries in the branch. However, for non-data branches, this doesn't happen because non-data branches have no baskets and yet have the same "number if entries" as the other branches. Hence the error, but the error should be suppressed if `interpretation` is `None` (always the case for non-data branches).

Your other question about getting data as separate arrays and wanting them as a record array: there is no function to do this automatically. The branch data are separate in the file, so they're returned to you as separate arrays. You could copy them into a record array, and there's a trick to do this zero-copy, but it's tricky (a recent issue tried to do that, but it doesn't play well with `iterate`). If you just want the interface of a record array but don't care if the data are contiguous in memory as a NumPy record array, then consider `awkward.Table`. If you have jagged arrays, you can combine them with `awkward.zip`.

Most of the other questions seem to be about the content of this kind of file, but I'm unfamiliar with that.

Good luck on your framework!

**Comment by tamasgal** [comment]
Thanks Jim, that all makes sense. Sorry for the bloated issue.

Alright, I'll read the arrays separately then, that's not a big deal. I'll try to make it efficient.

Now the only thing which I could not manage (and I assume that the data I am searching for somewhere there), is to read this:

```
>>> tree[b'km3net_timeslice_L1'][b'KM3NETDAQ::JDAQTimeslice'][b'vector<KM3NETDAQ::JDAQSuperFrame>'][b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier'].array()
...
ValueError: cannot interpret branch b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier' as a Python type
```

Any idea how to interpret it correctly? It's `.interpretation` is `None`

**Comment by tamasgal** [comment]
So basically I am left with the following two things:

The `.JDAQModuleIdentifier`, which only has a field `.id` somehow is not parsed or showing up in `uproot`:

```c++
    class JDAQModuleIdentifier
    {
    public:
      JDAQModuleIdentifier() :
        id(-1)
      {}
```

I tried with `.id` or `[b'id']` etc, but no luck:

```
tree[b'km3net_timeslice_L1'][b'KM3NETDAQ::JDAQTimeslice'][b'vector<KM3NETDAQ::JDAQSuperFrame>'][b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier.id']
KeyError: not found: b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier.id'
```

And the second, the hit data, which is "hidden" in the `.buffer` array, is a `vector` of `JDAQHit`:

```c++
  class JDAQHit
  {
  public:

    typedef  unsigned char             JPMT_t;    //!< PMT channel in FPGA
    typedef  unsigned int              JTDC_t;    //!< leading edge [ns]
    typedef  unsigned char             JTOT_t;    //!< time over threshold [ns]
```

This `.buffer` array shows up in

```
>>> frames = tree[b'km3net_timeslice_L1'][b'KM3NETDAQ::JDAQTimeslice'][b'vector<KM3NETDAQ::JDAQSuperFrame>']
>>> frames.keys()
[b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQPreamble',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.detector_id',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.run',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.frame_index',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.timeslice_start.UTC_seconds',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.timeslice_start.UTC_16nanosecondcycles',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.daq',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.fifo',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status_3',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status_4',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.numberOfHits',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer']
```

but I need to pass it the correct `dtype`, but don't know how:

```
>>> frames[b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer'].array(
                uproot.asjagged(uproot.astable(
                    uproot.asdtype([("pmt", "u1"),
                                    ("tdc", "u4"),
                                    ("tot", "u1")])),
                                skipbytes=10))
...
...
...
~/modules/software/python/3.7.5/lib/python3.7/site-packages/uproot/interp/objects.py in numitems(self, numbytes, numentries)
    172 
    173     def numitems(self, numbytes, numentries):
--> 174         return self.content.numitems(numbytes, numentries)
    175 
    176     def source_numitems(self, source):

~/modules/software/python/3.7.5/lib/python3.7/site-packages/uproot/interp/numerical.py in numitems(self, numbytes, numentries)
    150         dtype, shape = _dtypeshape(self.fromdtype)
    151         quotient, remainder = divmod(numbytes, dtype.itemsize)
--> 152         assert remainder == 0
    153         return quotient
    154 

AssertionError: 
```

**Comment by jpivarski** [comment]
The `id` is not split out into its own branch. It's inside `"vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier"`:

```python
>>> tree["vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier"]._fClassName
b'KM3NETDAQ::JDAQSuperFrameHeader'
>>> f._context.streamerinfosmap[b"KM3NETDAQ::JDAQSuperFrameHeader"].show()
StreamerInfo for class: KM3NETDAQ::JDAQSuperFrameHeader, version=2, checksum=0x986543d2
  KM3NETDAQ::JDAQHeader BASE            offset=  0 type= 0 
  KM3NETDAQ::JDAQModuleIdentifier BASE            offset=  0 type= 0 
  KM3NETDAQ::JDAQFrameStatus BASE            offset=  0 type= 0 

>>> f._context.streamerinfosmap[b"KM3NETDAQ::JDAQModuleIdentifier"].show()
StreamerInfo for class: KM3NETDAQ::JDAQModuleIdentifier, version=1, checksum=0x5e342f35
  id              int             offset=  0 type= 3 
```

and unfortunately something (probably that complicated branch name) is preventing this branch from being associated with its streamer:

```python
>>> tree["vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier"].show()
vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier
                           (no streamer)              None
```

The `buffer` is described by a type of streamer I've never seen before: `TStreamerLoop`.

```python
>>> tree[b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer'].show()
vector<KM3NETDAQ::JDAQSuperFrame>.buffer
                           TStreamerLoop              None
```

The way I reverse engineer each of these types is by looking at the raw bytes, preferably with a notion of what the data are _supposed_ to mean. The `uproot.asdebug` interpretation splits raw bytes up by entries, so that I can look at one entry at a time. The following looks at the first 100 bytes in the first entry, then looks at them as a bytestring to try to catch any strings by eye:

```python
>>> tree[b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer'].array(uproot.asdebug)[0][:100]
array([ 64,   4, 130,  36,   0,   9,   9,  80, 108,   7,   0,  27,  28,
        90, 108,   7,   0,  24,   4, 141, 211,  10,   0,   5,   4, 150,
       211,  10,   0,   7,   9, 254, 104,  12,   0,  23,   0, 239, 104,
        12,   0,  21,   8, 139, 134,  12,   0,  26,  17, 169, 134,  12,
         0,  32,  14, 145,  12,  14,   0,   8,  14, 158,  12,  14,   0,
        29,  24, 243, 223,  14,   0,  29,  29, 244, 223,  14,   0,  24,
        25,  31,  18,  16,   0,  24,  14,  16,  18,  16,   0,  34,   1,
       238,  90,  18,   0,  25,   5, 220,  90,  18], dtype=uint8)
>>> tree[b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer'].array(uproot.asdebug)[0][:100].tostring()
b'@\x04\x82$\x00\t\tPl\x07\x00\x1b\x1cZl\x07\x00\x18\x04\x8d\xd3\n\x00\x05\x04\x96\xd3\n\x00\x07\t\xfeh\x0c\x00\x17\x00\xefh\x0c\x00\x15\x08\x8b\x86\x0c\x00\x1a\x11\xa9\x86\x0c\x00 \x0e\x91\x0c\x0e\x00\x08\x0e\x9e\x0c\x0e\x00\x1d\x18\xf3\xdf\x0e\x00\x1d\x1d\xf4\xdf\x0e\x00\x18\x19\x1f\x12\x10\x00\x18\x0e\x10\x12\x10\x00"\x01\xeeZ\x12\x00\x19\x05\xdcZ\x12'
```

No such luck. The first 6 bytes is probably a header; a high byte of `64` is very common in ROOT headers. So then I look at the streamers for a hint.

```python
>>> f._context.streamerinfosmap[b"KM3NETDAQ::JDAQFrame"].show()
StreamerInfo for class: KM3NETDAQ::JDAQFrame, version=1, checksum=0xc27d4b39
  numberOfHits    int             offset=  0 type= 6 following comment line is used by rootcint
  buffer          KM3NETDAQ::JDAQHit* offset=  0 type=501 [numberOfHits]
>>> f._context.streamerinfosmap[b"KM3NETDAQ::JDAQHit"].show()
StreamerInfo for class: KM3NETDAQ::JDAQHit, version=1, checksum=0x530441c9
```

but that's the end of the road. Does `JDAQHit` have a custom streamer?

I hope these hints help your investigation.

**Comment by tamasgal** [comment]
Thanks for the investigations!

It's probably a dumb question, but how do I get an array of the `id`s then? Should I somehow pass the correct `dtype`?

Regarding the `JDAQHit`, there is actually a weird hint in the source code of `JDAQHit.hh`:

```c++
  /**
   * Hit data structure.
   *
   * N.B.
   * The size of this data structure (i.e. the value obtained with the <tt>sizeof()</tt> operator 
   * should exactly match the preset number of bytes from the DAQ system. 
   * The <tt>pragma</tt> statement is necessary to ensure the correct size of this object.
   * Furthermore, this data structure should have no virtual methods and no virtual destructor.
   * Consequently, the standard ROOT <tt>CLassDef()</tt> macro is replaced by
   * the designated <tt>ClassDefNV()</tt> macro.
   */
#pragma pack(push,1)
  class JDAQHit
...
...
...
   ClassDefNV(JDAQHit,1);
...
...
```

And all I could found in the source code regarding `ClassDev*` is this:

```c++
#define ClassDef(name, version)      static const char* Class_Name() { return #name; }
#define ClassDefNV(name, version)    static const char* Class_Name() { return #name; }
```

I am playing around with `uproot.asdebug` which is very helpful.
The size of the array of the first frame (which is the first timeslice hit vector) is

```python
>>> len(tree[b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer'].array(uproot.asdebug)[0])
295464
```

For this particular file, I know that the first timeslice has 49243 hits, and each hit is 6 bytes (1byte ToT, 4 bytes tdc time, 1byte PMT channel). A bit of fiddling with the numbers gives that `295464 mod 49243 == 6` which means that skipping the first 6 bytes should be parsable as a vector of hits?

Well, the data seems incorrect unfortunately, but I am starting to be really confused, why are those number repeating? 😕 

```
>>> tree[b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer'].array(uproot.asdebug)[0].astype(
    [("pmt", "u1"), ("tdc", "u4"), ("tot", "u1")]
)
array([( 64,  64,  64), (  4,   4,   4), (130, 130, 130), ...,
       (237, 237, 237), (  5,   5,   5), ( 30,  30,  30)],
      dtype=[('pmt', 'u1'), ('tdc', '<u4'), ('tot', 'u1')])
```

**Comment by tamasgal** [comment]
Aaah, I think the hit stuff is now solved:

```
frames[b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer'].array(
                uproot.asjagged(uproot.astable(
                    uproot.asdtype([("pmt", "u1"),
                                    ("tdc", "u4"),
                                    ("tot", "u1")])),
                                skipbytes=6))
```

**Comment by tamasgal** [comment]
I think I should open a new issue regarding the `JDAQHit` situation. I am now able to read the data and still did not manage to get it into the right shape.

**Comment by jpivarski** [comment]
Okay, open a new issue, but make the questions focused. You're clearly in the middle of development, so you're following a lot of loose threads simultaneously, but when you express it all here, I can't follow it all.

Maybe what we need to do is a bit of pair programming, so that we have a broader band of communication. Some of these things should be improvements to uproot itself, such as adding an implementation for `TStreamerLoop` or passing the appropriate streamer down to `"vector<KM3NETDAQ::JDAQSuperFrame>.KM3NETDAQ::JDAQModuleIdentifier"` (in which the `id` values are embedded). You're working with a more complex class hierarchy than uproot is usually applied to—it's either something that should be declared out of scope or new ground for expansion.

A method that has worked for me to do remote pair programming is to use Skype/Vidyo/whatever for voice and Atom with TeleType to work on the same source code. Atom's TeleType extension is essentially a Google Doc for source code. When coupled with Atom's Hydrogen extension, we can evaluate the same document as though we were sharing a Jupyter notebook (but it's the original source code, not a notebook). I used this in last year's GSoC.

If you're still working on this on Monday, we can try that then. (I'm required to not work on weekends... not much, anyway.) Until then, I can give you general pointers like `uproot.asdebug`.

**Comment by tamasgal** [comment]
I will work on this I/O framework as long as I manage to read events (done), timeslices (almost there) and summary slices (not looked at it yet) 😆

Many thanks, that's definitely an awesome offer! I'll try out Atom's Teletype to get used to it and we can have PP on Monday, whenever you have time. I'll try to boil down things as much as possible.

**Comment by tamasgal** [comment]
OK, I've got some news. The application which I used to convert the created a "corrupt" ROOT file (I know, this is really annoying). I used the original file which I used to extract the small data subset and some of the problems are solved!
So basically you were right that it could be something with a wrongly closed ROOT file or so...

For the sake of completeness, this is the corrected version of the sample file (I'll update the link in the OP to point to the broken one, as I have overwritten that file): https://github.com/KM3NeT/km3io/blob/master/tests/samples/jpp_v12.0.0.root

This is how the frames are parsed now, notice that all fields are basic types:

```
>>> frames.keys()
[b'vector<KM3NETDAQ::JDAQSuperFrame>.length',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.type',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.fUniqueID',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.fBits',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.detector_id',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.run',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.frame_index',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.timeslice_start.UTC_seconds',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.timeslice_start.UTC_16nanosecondcycles',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.id',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.daq',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.fifo',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status_3',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.status_4',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.numberOfHits',
 b'vector<KM3NETDAQ::JDAQSuperFrame>.buffer']
```

So now the module IDs are correct and accessible:

```
>>> frames[b'vector<KM3NETDAQ::JDAQSuperFrame>.id'].array()[0]
array([806451572, 806455814, 806465101, 806483369, 806487219, 806487226,
       806487231, 808432835, 808435278, 808447180, 808447186, 808451904,
       808451907, 808469129, 808472260, 808472265, 808488895, 808488990,
       808489014, 808489117, 808493910, 808946818, 808949744, 808951460,
       808956908, 808959411, 808961448, 808961480, 808961504, 808961655,
       808964815, 808964852, 808964883, 808964908, 808969848, 808969857,
       808972593, 808972598, 808972698, 808974758, 808974773, 808974811,
       808974972, 808976377, 808979567, 808979721, 808979729, 808981510,
       808981523, 808981672, 808981812, 808981864, 808982005, 808982018,
       808982041, 808982066, 808982077, 808982547, 808984711, 808996773,
       808997793, 809006037, 809007627, 809503416, 809521500, 809524432,
       809526097, 809544058, 809544061], dtype=int32)
```


The only issue currently is the ragged hits array, which is stored in `buffer`, but I'll try harder and if I fail I'll open an issue tomorrow.

**Comment by jpivarski** [comment]
That's great! About everything except the `buffer`... When I looked into that, I saw that the streamer gave no information about what was in it (follow it yourself—it's presented as an empty class, though the branch is not empty).

Do you have external information about what the exact values are supposed to be? From the original framework, for example? That can be very helpful. Particularly with small integers bigger than 0 or 1, you can manually search for those values because they show up in the raw bytes pretty clearly. Or with a little more difficultly, floating point values because they are unmistakable when you find them. (Just remember that all the values are big endian, so interpret those bytes with `>` in the format string!)

**Comment by tamasgal** [comment]
Yep of sure! I am in full control of the original framework and I'll prepare a detailed structure including the correct values. I am working with this kind of data for a couple of years but not with its binary ROOT structure. I actually work on the low-end DAQ part for real-time analysis and there I parse the binary streams from the detector via the network with my own Python and Julia frameworks. That stream has a well specified data format, in contrast to the ROOT counterpart which we use to actually store the data on disk ;)

Actually the shape and values of `numberOfHits` attribute basically provide the substructure of `buffer`, it's a ragged array of `JDAQHits` (1byte-ToT, 4bytes-PMT_channel, 1byte-time with 6byte offset). Maybe I can even figure it out tomorrow, otherwise I stick to the plan to provide a focussed issue!
