### ISSUE TITLE
Too many indices for array with lazyarrays

### ISSUE THREAD

**Issue by beojan** [scikit-hep/uproot#412]
When I run a selection using lazy arrays, I get the error `Too many indices for array`.

```python
tree = up.open('data17-slim.root')['low'].lazyarrays(namedecode='utf8')
tree['m_dj_min'][tree['ntag'] == 2]
```

I get no error if I convert the index array to a Numpy array:
```python
tree['m_dj_min'][np.array(tree['ntag'] == 2)]
```

**Comment by jpivarski** [comment]
This isn't enough information for me to diagnose the error; you'll have to send an example file. (Thanks!)

**Comment by beojan** [comment]
Attached, though it doesn't seem to matter what file I use. In this file, the tree is called 'test' and the branches are `b1` (integers) and `b2` (floats).
[test.root.gz](https://github.com/scikit-hep/uproot/files/3879799/test.root.gz)

**Comment by jpivarski** [comment]
Oh, I get it now. Yeah, that's an awkward bug: see scikit-hep/awkward-array#216. I'll start a new deployment, so when this is through the machinery, it will be `awkward==0.12.17`.

**Comment by jpivarski** [comment]
The fix is up on PyPI (`pip install -U awkward`). Thanks for pointing it out!
