### ISSUE TITLE
Add the ability to read data compressed by zstd

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot#415]
ROOT is introducing a new compression method, zstd ("z-standard"), which will need to be explicitly handled like the others (zlib, lzma, and lz4). There is surely a Python library for this compression method, though it will take some investigation to discover what the new two-character identifier for zstd is, what kind of header it has, how to access the right decompression function in the Python library (i.e. block vs. frame). One of us should do this soon after the ROOT version with zstd is released.

**Comment by oshadura** [comment]
Hi Jim! I will be happy to pick up this item, if nobody is working on it :)

**Comment by reikdas** [comment]
@jpivarski Perhaps another open issue as a stub to also write zstd compressed ROOT files? (But maybe we should wait for this till the ROOT Pro release adds zstd compression)

**Comment by jpivarski** [comment]
@oshadura Thanks for the offer! I added some open issues last night because @Arpita-Seksaria is looking for a project, but I'm open to help from the compression expert, if you're willing.  :)

@reikdas That's a good idea. As soon as the zstd-reading is understood (particularly, which function to call in its Python library and what the header looks like), it should be rather easy to add writing capability.

I'm unclear on the schedule for the release of this feature in ROOT, but I know that it's soon.

**Comment by Arpita-Seksaria** [comment]
Hey,

Thank you Jim.

Regards



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
30/11/19,
10:51:50

**Comment by oshadura** [comment]
> I'm unclear on the schedule for the release of this feature in ROOT, but I know that it's soon.

ZSTD will be released in 6.20 so it is expected ~ in January..

**Comment by reikdas** [comment]
@jpivarski Can we close this?

**Comment by jpivarski** [comment]
Yes, this is done.

Thanks again, @oshadura!
