### ISSUE TITLE
Accessing custom class methods

### ISSUE THREAD

**Issue by soleti** [scikit-hep/uproot#418]
Hello, sorry if this issue is a duplicate, but I am trying to access the values returned by some methods of a custom class. This is what I have in the TBrowser:

![TBrowser screenshot](https://i.imgur.com/hGfwKF8.png)

But when I try to access it with uproot I get

``` >>> import uproot
>>> file = uproot.open("output.root")
>>> pos = file["SCHD"]["chdiag"]["pos"]
>>> pos.show()
pos                        TStreamerInfo              None
fCoordinates               TStreamerObjectAny         None
fCoordinates.fX            TStreamerBasicType         asdtype('>f4')
fCoordinates.fY            TStreamerBasicType         asdtype('>f4')
fCoordinates.fZ            TStreamerBasicType         asdtype('>f4')

```

So basically I can access only fCoordinates and not e.g. mag2 or perp2. Another problem is that, since this class is used more than once in the tree, if I convert the tree to a pandas dataframe I get columns with the same name (e.g. `fCoordinates.fX`). I can rename them but I need to do it manually by inspecting their order in the columns list, so I know who is who. It would be helpful if they could automatically be called e.g. `pos.fCoordinates.fX`.

Is there a way to do both things with uproot? I uploaded a small example file here: https://drive.google.com/open?id=1ChG6nDEUgVa09ro9zgpCfwEAnlXIbgdN

**Comment by jpivarski** [comment]
Short answer: no, there isn't a way to do that with uproot. The reason is that these methods are defined on the C++ classes that are loaded into ROOT, and those C++ classes aren't in the ROOT file. Uproot only looks at the ROOT file—it can't compute `X()` because it doesn't have the code. (You or I could guess what such a function does, but there's no AI in uproot!)

The second point is similar: when you look at a raw ROOT file, the class hierarchy is gone; you just have the branches that are attached to the TTree. Uproot shows you those branches as they are. You might find that you can do

```python
>>> tree = file["SCHD"]
>>> tree["fCoordinates.fZ"]
```

instead of

```python
>>> tree = file["SCHD"]
>>> tree["chdiag"]["pos"]["fCoordinates.fZ"]
```

because the `tree.__getitem__` (what is called when you use square brackets) recursively walks down all the branches, assuming that what you want is unambiguous. Whether or not there is a dotted path like `pos.fCoordinates.fX` depends on ROOT settings while writing the file: those are hard-coded branch names. It looks like your file doesn't have full paths written on its branch names.

**Comment by soleti** [comment]
Thank you very much for your quick reply. Regarding the first point I think I see what you mean, but then why in the TBrowser I am able to plot those variables? For example

``` 
root [2] chdiag->Scan("pos.mag2()")
************************
*    Row   * pos.mag2( *
************************
*        0 * 2566924.2 *
*        1 * 2626867.5 *
*        2 * 2456775.5 *
...
```

**Comment by jpivarski** [comment]
Because the `TBrowser` is in ROOT, and ROOT has loaded the C++ classes. `TTree::Scan` is a ROOT function, too. Neither of these exist in uproot.

**Comment by soleti** [comment]
I am aware that `TBrowser` is in ROOT and `TTree::Scan` is a ROOT function. What I don't understand is what you mean by "ROOT has loaded the C++ classes". I just load the ROOT file with

``` root output.root 
```

Are you saying that the C++ classes are somehow stored in the .root file and that ROOT is able to load them? Thank you and sorry if the question seems dumb.

**Comment by jpivarski** [comment]
Sorry to be short (I'm split between several different things—didn't check the tone of my answer).

I was saying the opposite of that: the C++ classes are not in the ROOT file. There are, however, "streamers" that _name_ the C++ classes, so ROOT knows what to look for. Somehow, ROOT finds those classes and loads them in your case. I usually get warnings about ROOT being unable to load a set of classes and then I can't use functions like `X()`. Maybe those `.so` files are on your path, or in some setup script?

Anyway, the ROOT file itself contains nothing except for the private member data and the names of the classes they belong to.

**Comment by soleti** [comment]
No problem at all. I indeed get in ROOT
``` 
Warning in <TClass::Init>: no dictionary for class CLHEP::Hep3Vector is available
```
however I am still able to plot the various functions. I don't think I have any particular class in my setup. These files are produced on an entirely different machine and read on a machine that has only vanilla ROOT installed. In any case, it doesn't seem to be strictly a `uproot` issue, so feel free to close the issue.

**Comment by sbinet** [comment]
ROOT locates the dictionaries (ie: shared libraries that are linked against the C++ code of a given class, and containing reflection code) via `.rootmap` files.
`.rootmap` files are discovered via either `LD_LIBRARY_PATH` and/or `ROOTMAPPATH` (IIRC).
`.rootmap` files contain the association `"class-name" <--> "libFoo.so"`.

that's how ROOT used to (circa 2010-2015) discover C++ code and invoke it.

**Comment by jpivarski** [comment]
Thanks, @sbinet! It was really weird that ROOT seemed to be finding these classes even though it raised a warning saying that it couldn't. I guess one mechanism failed and another succeeded?

Anyway, the question we're discussing here is how ROOT works, not how to use uproot, so I'll close it.
