### ISSUE TITLE
Error while reading vector

### ISSUE THREAD

**Issue by ram1123** [scikit-hep/uproot#42]
Hi,

I am trying to read a branch of type vector but I am getting some error. Below I described what I did:

```
>>> import uproot
>>> f = uproot.open("/eos/uscms/store/user/rasharma/LHE_GEN_Analyzer_Output/WPlepWMhad_aQGC.root")["otree"]
>>> a = f.array("LHEWeights")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uproot/tree.py", line 347, in array
    return self.get(branch).array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
  File "uproot/tree.py", line 960, in array
    destination = interpretation.destination(basket_itemoffset[-1], basket_entryoffset[-1])
  File "uproot/interp/jagged.py", line 88, in destination
    contents = self.asdtype.destination(numitems, numentries)
  File "uproot/interp/numerical.py", line 123, in destination
    return numpy.empty((numitems // product,) + self.todims, dtype=self.todtype)
MemoryError
```

Please let me know, how I can read the branch of type vector?

Thanks,
Ram

**Comment by jpivarski** [comment]
This one isn't about the data type: MemoryError means that you don't have enough memory to load the whole thing at once.

Try selecting a smaller range of events with the `entrystart` and `entrystop` parameters, or iterate over it with `tree.iterate`, optionally setting `entrysteps` to control the number of entries per iteration.

If that doesn't help, go ahead and reopen this issue.
