### ISSUE TITLE
Creating new trees with cycles in the name breaks write-ability

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/uproot#424]
The basic usage works fine

```python
import uproot
import numpy

with uproot.recreate("example.root") as f:
    f["t"] = uproot.newtree({"branch": "int32"})
    f["t"].extend({"branch": numpy.array([1, 2, 3, 4, 5])})
```

however, once you get to using a cycle like so

```
import uproot
import numpy

with uproot.recreate("example.root") as f:
    f["t;1"] = uproot.newtree({"branch": "int32"})
    f["t;1"].extend({"branch": numpy.array([1, 2, 3, 4, 5])})
```

this crashes as `f["t;1"]` stops becoming a `uproot.write.objects.TTree.TTree` and becomes a `uproot.rootio.TTree` instead. This means, among other things, we lose the `extend()` functionality.

**Comment by jpivarski** [comment]
I see: the writable `TTree`'s `__getitem__` needs to be cycle-aware (it needs to pass that on to its readable `TTree` view).

**Comment by kratsg** [comment]
> I see: the writable `TTree`'s `__getitem__` needs to be cycle-aware (it needs to pass that on to its readable `TTree` view).

What line are you looking at here for that?

**Comment by reikdas** [comment]
I'll take a look at this today.

**Comment by reikdas** [comment]
@kratsg Can you confirm if branch `write-tree-cycle` fixes the issue?
