### ISSUE TITLE
Fail to construct JaggedArray

### ISSUE THREAD

**Issue by vkuznet** [scikit-hep/uproot#43]
Jim,
I got this error while reading one of the root files:
```
  File "build/bdist.macosx-10.13-x86_64/egg/uproot/tree.py", line 450, in iterate
  File "build/bdist.macosx-10.13-x86_64/egg/uproot/tree.py", line 433, in <lambda>
  File "build/bdist.macosx-10.13-x86_64/egg/uproot/tree.py", line 1032, in <lambda>
  File "build/bdist.macosx-10.13-x86_64/egg/uproot/interp/jagged.py", line 66, in empty
TypeError: __init__() takes exactly 4 arguments (3 given)
```

Turns out it is a bug here:
https://github.com/scikit-hep/uproot/blob/master/uproot/interp/jagged.py#L66
since JaggedArray ctor requires 3 parameters
https://github.com/scikit-hep/uproot/blob/master/uproot/interp/jagged.py#L224

So, there is a missing stops parameter in L66.

**Comment by jpivarski** [comment]
You're right. JaggedArrays used to be defined by "contents" and "offsets", now they're defined by "contents", "starts", and "stops" for more flexibility, and this function was never updated. Thanks for catching it.

Release 2.5.16 fixes this and is going through the pipeline from GitHub to PyPI.

**Comment by vkuznet** [comment]
Jim, now with 2.5.16 this error is gone, but I got another one:
```
  File "build/bdist.macosx-10.13-x86_64/egg/uproot/tree.py", line 450, in iterate
  File "build/bdist.macosx-10.13-x86_64/egg/uproot/tree.py", line 433, in <lambda>
  File "build/bdist.macosx-10.13-x86_64/egg/uproot/interp/jagged.py", line 102, in finalize
AttributeError: 'JaggedArray' object has no attribute 'sizes'
```

**Comment by jpivarski** [comment]
I was trying to focus on another project and didn't look closely enough: this `empty` function is supposed to make a `JaggedArray._Prep`, rather than a `JaggedArray`. (When filling in parallel, you have to use a `counts` array instead of `offsets` or `starts`/`stops` so that sections can be filled in any order, thus preparatory JaggedArrays are different from JaggedArrays. I forgot that.)

If you have access to git master, try it now.

**Comment by jpivarski** [comment]
(I don't have a good source of data that produces an empty JaggedArray, so we'll have to debug through commits to master.)

**Comment by vkuznet** [comment]
ok, it works now in master.

**Comment by jpivarski** [comment]
Okay, good. I'll release a version.
