### ISSUE TITLE
uproot.rootio.TTree.arrays omitting variables

### ISSUE THREAD

**Issue by kreczko** [scikit-hep/uproot#447]
### Summary
In the case of multiple branches with identical variable (sub-branch/leaf?) names the [`uproot.rootio.TTree.arrays`](https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L502) will hide variables.

As en example, see http://fast-hep-data.web.cern.ch/fast-hep-data/cms/L1T/CMS_L1T_study.root where the tree `'l1CaloTowerEmuTree/L1CaloTowerTree'` has the structure:

```bash
CaloTP                     TStreamerInfo              None
nHCALTP                    TStreamerBasicType         asdtype('>i2')
hcalTPieta                 TStreamerSTL               asjagged(asdtype('>i2'), 10)
hcalTPiphi                 TStreamerSTL               asjagged(asdtype('>i2'), 10)
hcalTPCaliphi              TStreamerSTL               asjagged(asdtype('>i2'), 10)
hcalTPet                   TStreamerSTL               asjagged(asdtype('>f4'), 10)
hcalTPcompEt               TStreamerSTL               asjagged(asdtype('>i2'), 10)
hcalTPfineGrain            TStreamerSTL               asjagged(asdtype('>i2'), 10)
nECALTP                    TStreamerBasicType         asdtype('>i2')
ecalTPieta                 TStreamerSTL               asjagged(asdtype('>i2'), 10)
ecalTPiphi                 TStreamerSTL               asjagged(asdtype('>i2'), 10)
ecalTPCaliphi              TStreamerSTL               asjagged(asdtype('>i2'), 10)
ecalTPet                   TStreamerSTL               asjagged(asdtype('>f4'), 10)
ecalTPcompEt               TStreamerSTL               asjagged(asdtype('>i2'), 10)
ecalTPfineGrain            TStreamerSTL               asjagged(asdtype('>i2'), 10)

L1CaloTower                TStreamerInfo              None
nTower                     TStreamerBasicType         asdtype('>i2')
ieta                       TStreamerSTL               asjagged(asdtype('>i2'), 10)
iphi                       TStreamerSTL               asjagged(asdtype('>i2'), 10)
iet                        TStreamerSTL               asjagged(asdtype('>i2'), 10)
iem                        TStreamerSTL               asjagged(asdtype('>i2'), 10)
ihad                       TStreamerSTL               asjagged(asdtype('>i2'), 10)
iratio                     TStreamerSTL               asjagged(asdtype('>i2'), 10)
iqual                      TStreamerSTL               asjagged(asdtype('>i2'), 10)
et                         TStreamerSTL               asjagged(asdtype('>f4'), 10)
eta                        TStreamerSTL               asjagged(asdtype('>f4'), 10)
phi                        TStreamerSTL               asjagged(asdtype('>f4'), 10)

L1CaloCluster              TStreamerInfo              None
nCluster                   TStreamerBasicType         asdtype('>i2')
ieta                       TStreamerSTL               asjagged(asdtype('>i2'), 10)
iphi                       TStreamerSTL               asjagged(asdtype('>i2'), 10)
iet                        TStreamerSTL               asjagged(asdtype('>i2'), 10)
iqual                      TStreamerSTL               asjagged(asdtype('>i2'), 10)
et                         TStreamerSTL               asjagged(asdtype('>f4'), 10)
eta                        TStreamerSTL               asjagged(asdtype('>f4'), 10)
phi                        TStreamerSTL               asjagged(asdtype('>f4'), 10)
```

Here, `L1CaloTower` and `L1CaloCluster` have a few variables in common, e.g. `et`, `eta`, `phi`.
However, when calling `tree.arrays(namedecode="utf-8")`, these variables are only present once, which leads to a total of 7 missing variables:
```bash
array keys dict_keys(['nHCALTP', 'hcalTPieta', 'hcalTPiphi', 'hcalTPCaliphi', 'hcalTPet', 'hcalTPcompEt', 'hcalTPfineGrain', 'nECALTP', 'ecalTPieta', 'ecalTPiphi', 'ecalTPCaliphi', 'ecalTPet', 'ecalTPcompEt', 'ecalTPfineGrain', 'nTower', 'ieta', 'iphi', 'iet', 'iem', 'ihad', 'iratio', 'iqual', 'et', 'eta', 'phi', 'nCluster'])

33 variables across 3 branches but 26 variables in array dict
```

### Request
Would it be possible to adjust the `arrays` method or add an option to the `arrays` method to produce unique keys for all variables?
e.g. `L1CaloCluster.et` and `L1CaloTower.et`?

The workaround at the moment is to convert each variable independently, e.g. `array = t1['L1CaloTower']['et'].array()`

### Full example code
```python
import uproot

f = uproot.open('http://fast-hep-data.web.cern.ch/fast-hep-data/cms/L1T/CMS_L1T_study.root')
t1 = f['l1CaloTowerEmuTree/L1CaloTowerTree']

t1.show()

arrays = t1.arrays(namedecode="utf-8")
print('array keys', arrays.keys())
n_array_vars = len(arrays.keys())

n_branches = len(t1.keys())
n_vars = sum([len(t1[k].keys()) for k in t1.keys()])
print(f'{n_vars} variables across {n_branches} branches but {n_array_vars} variables in array dict')
```

**Comment by jpivarski** [comment]
This is related to #444, which proposes a way to request nested branches with non-unique names with a `/` token. In your request, you want nested branches with non-unique names to be distinguished by some token, and it should probably be the same token because these are inverses of each other.

As a token, `/` is a better choice than `.` because `.` can already be used in branch names and is often auto-generated. As described in [this roottalk from 2004](https://root.cern.ch/root/roottalk/roottalk04/2592.html), naming a branch `"something."` causes any automatically-generated subbranches to be named `"something.x"`, `"something.y"`, `"something.z"`, etc. This is why names separated by dots appear so often in branch names. But once generated, the file simply has that as part of the string. Using `.` as a delimiter token would be a disaster.

I _believe_ that `/` is not allowed in branch names because it's part of the leaf type syntax (e.g. `"myleaf/F"`) but maybe that only applies to leaves. It also has the nice feature that subbranches are kinda like subdirectories, and you'd be able to say

```python
file["mydirectory/mytree/branch/subbranch"]
```

in #444.

**Comment by kreczko** [comment]
Thanks for the quick response and explanation.

You are right, `/` is better than `.`. I like the 
```python
file["mydirectory/mytree/branch/subbranch"]
```
example as it looks very natural.

Internally we are translating all `/` to `.` for [numexpr](https://github.com/pydata/numexpr), so either works for us.

**Comment by jpivarski** [comment]
I should mention, though, that I'm not available to work on this. (At the moment, I'm just trying to answer all these emails, which is like running the wrong way up an escalator!) I'm pointing out a change that would make sense and its connection with another issue. If somebody has enough need for it that they'll implement it, I'm in favor of the change and will help with hints.

Having just looked into it, here are a couple:

First of all, this is a surface-level thing—it doesn't get deep into any deserialization; it would just be a parameter (e.g. `recursive={False, True, "/"}`, default is the current behavior, `True`) to `TTree.arrays` that passes into `TTree._normalize_branches`:

https://github.com/scikit-hep/uproot/blob/ced6380f7dcf558f7d7f20a5673514479bd37efa/uproot/tree.py#L502-L504

that `TTree._normalize_branches` [passes down](https://github.com/scikit-hep/uproot/blob/ced6380f7dcf558f7d7f20a5673514479bd37efa/uproot/tree.py#L771-L851) to `TTree.iteritems` and `TBranch.iteritems`:

https://github.com/scikit-hep/uproot/blob/ced6380f7dcf558f7d7f20a5673514479bd37efa/uproot/tree.py#L344-L350

https://github.com/scikit-hep/uproot/blob/ced6380f7dcf558f7d7f20a5673514479bd37efa/uproot/tree.py#L951-L957

which already has a `recursive` parameter. When its value is `"/"`, it would recurse _and_ prepend parent names, delimited by whatever the string is. (So if you're brave, you the user could pass `"."`, though `"/"` would be recommended.)

**Comment by kreczko** [comment]
Thanks for the pointers, this is really useful. I will try to make some time for this.
For testing,  
 - do you already have a test file with a similar structure?
 - if not, would be OK in using the mentioned file via HTTP?
 - if not, would you like a small test file with such structure?

**Comment by jpivarski** [comment]
A small test file is preferred. A few of the tests depend on HTTP (I put them in github.io: https://github.com/scikit-hep/uproot/tree/gh-pages/examples, so still smallish), and these are the most likely to break for irrelevant reasons. I have to manage these failures by manually re-starting a test.

I don't have any files with this structure because I didn't even know, at first, that it's possible to create ambiguities. I had thought that they were always written in dotted-form, but that's just because most ROOT file writers take advantage of the trailing-dot trick.

On the plus side, testing this doesn't require any data, so whatever you have for the regular file can write 1 or even 0 events and it would be a fair test. The branches don't have to have data to be searched in this way.

Also, I want to be sure @ast0815 knows about this because getting dictionaries from `arrays()` that are full of slashed names really is the inverse of requesting deep branches with slashed names. The two features bring value to each other.

**Comment by kreczko** [comment]
So the test I have for this is
```python
def test_issue447_tree_arrays_omitting_variables():
    with uproot.open("tests/samples/issue447.root") as f:
        t1 = f['l1CaloTowerEmuTree/L1CaloTowerTree']
        arrays = t1.arrays()
        n_array_vars = len(arrays.keys())
        n_tree_vars = sum([len(t1[k].keys()) for k in t1.keys()])
        assert n_tree_vars == n_array_vars
```
However, by default `TTree._normalize_branches` goes the
```python
if allownone and arg is None:                      # no specification; read all branches
            for branch in self.allvalues():                # that have interpretations
                interpretation = interpret(branch, awkward)
                if interpretation is not None:
                    yield branch, interpretation
```
route, not `TTree.iteritems` or`TBranch.iteritems` as `allownone` is True and `arg` is empty (list of branches passed to TTree.arrays())`.

Once things arrive at
https://github.com/scikit-hep/uproot/blob/ced6380f7dcf558f7d7f20a5673514479bd37efa/uproot/tree.py#L517
neither `branches` nor `futures` contain any information to construct the "lineage".

To modify `itervalues` I would add a new variable, e.g. `provenance` or `lineage` (i.e. a list of parents) to `TBranch` as `_fParent` has a different meaning. Then `TTree.array` or any other function can choose on how to interpret that information

**Comment by jpivarski** [comment]
Do you mean adding upward-pointing links from each TBranch to its parent TBranch or TTree?

In another issue, we were just talking about trying to _remove_ cyclic references, and here's a reason to add new ones. I guess if this application needs it, let's add those upward-pointing links and give up on the hope of removing all cyclic references. (The other discussion died out, anyway.)

**Comment by kreczko** [comment]
> Do you mean adding upward-pointing links from each TBranch to its parent TBranch or TTree?

In a way, yes - unless there is a better option.
In my example I have
```
# <directory>/<tree>/<branch>/<subbranch>
```
&rarr;
```
subbranch.provenance = [<directory>.name,<tree>.name,<branch>.name]
