### ISSUE TITLE
Retrieve dict of branch names and types for an existing tree

### ISSUE THREAD

**Issue by beojan** [scikit-hep/uproot#454]
Basically, I'd like to use uproot to copy `TTree`s, because I have some `TTree`s that are each one giant cluster, and I'd like to split them into multiple clusters.

To create a new tree with the same branches as an existing one, a `TTreeMethods` method that provided the branch dict needed would be helpful.

**Comment by jpivarski** [comment]
That would be a good convenience function. Since Uproot can only write non-jagged numeric type branches, should such a function skip or complain about branches that don't fit that description?

**Comment by beojan** [comment]
I would go with warn and skip as a default, with the ability to choose to make it an error (as with numerical errors in NumPy, for instance).

**Comment by jpivarski** [comment]
How about this (for some TTree named `tree`; can become `self`).?

```python
{n: x.interpretation.todtype for n, x in tree.allitems() if isinstance(x.interpretation, uproot.asdtype)}
```

or

```python
{n: x.interpretation.todtype.type for n, x in tree.allitems() if isinstance(x.interpretation, uproot.asdtype)}
```

**Comment by beojan** [comment]
I think that's fine, thanks.

**Comment by jpivarski** [comment]
In fact, Uproot 4 has this:

```python
>>> import uproot4
>>> t = uproot4.open("../uproot/tests/samples/sample-6.16.00-uncompressed.root:sample")

>>> t.typenames()
{'n': 'int32_t', 'b': 'bool', 'ab': 'bool[]', 'Ab': 'bool[]', 'i1': 'int8_t', 'ai1': 'int8_t[]', 'Ai1': 'int8_t[]', 'u1': 'uint8_t', 'au1': 'uint8_t[]', 'Au1': 'uint8_t[]', 'i2': 'int16_t', 'ai2': 'int16_t[]', 'Ai2': 'int16_t[]', 'u2': 'uint16_t', 'au2': 'uint16_t[]', 'Au2': 'uint16_t[]', 'i4': 'int32_t', 'ai4': 'int32_t[]', 'Ai4': 'int32_t[]', 'u4': 'uint32_t', 'au4': 'uint32_t[]', 'Au4': 'uint32_t[]', 'i8': 'int64_t', 'ai8': 'int64_t[]', 'Ai8': 'int64_t[]', 'u8': 'uint64_t', 'au8': 'uint64_t[]', 'Au8': 'uint64_t[]', 'f4': 'float', 'af4': 'float[]', 'Af4': 'float[]', 'f8': 'double', 'af8': 'double[]', 'Af8': 'double[]', 'str': 'char*'}

>>> t.typenames(filter_name=["Ai*", "Af*"])
{'Ai1': 'int8_t[]', 'Ai2': 'int16_t[]', 'Ai4': 'int32_t[]', 'Ai8': 'int64_t[]', 'Af4': 'float[]', 'Af8': 'double[]'}
```

Equivalent to `file.classnames(filter_name=...)` on TDirectories.
