### ISSUE TITLE
ROOT-6.12.04 support: issue with new ROOT::TIOFeatures field in TTree

### ISSUE THREAD

**Issue by sbinet** [scikit-hep/uproot#46]
hi,

trying to read a ROOT file generated w/ `ROOT-6.12.04`, I get:

```py
>>> import uproot
>>> uproot.__file__
'/home/binet/tmp/uproot/uproot/build/lib/uproot/__init__.py'
>>> uproot.open("/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/testdata/stdvec-bool.root")
<ROOTDirectory b'stdvec-bool.root' at 0x7fca9a156b38>
>>> f=_
>>> f.get("tree")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/binet/tmp/uproot/uproot/build/lib/uproot/rootio.py", line 315, in get
    return key.get()
  File "/home/binet/tmp/uproot/uproot/build/lib/uproot/rootio.py", line 803, in get
    return self._context.classes[classname].read(self._source, self._cursor.copied(), self._context)
  File "/home/binet/tmp/uproot/uproot/build/lib/uproot/rootio.py", line 741, in read
    out = cls._readinto(out, source, cursor, context)
  File "<generated from TStreamerInfo b'TTree' at 0x7fca9a150b00>", line 19, in _readinto
  File "/home/binet/tmp/uproot/uproot/build/lib/uproot/rootio.py", line 741, in read
    out = cls._readinto(out, source, cursor, context)
  File "<generated from TStreamerInfo b'ROOT::TIOFeatures' at 0x7fca9b0d9048>", line 9, in _readinto
ValueError: attempting to read ROOT_3a3a_TIOFeatures object version 0 with a class generated by streamer version 1
```

the input file is available there:

- https://cern.ch/binet/go-hep/rootio/stdvec-bool.root

**Comment by jpivarski** [comment]
This TIOFeatures class seems to break pattern with the others. I've put in a special-case streamer because it comes in a critical spot— right before the TBranches in a TTree— but I'm unsatisfied with that. Surely there would be other classes following this pattern.

The test with this file is conclusive in that all of the number of bytes "checksums" match. However, it's an example of unsplit data, which uproot doesn't handle yet. However, there is reasonable-looking data there, as I can see with the special `asdebug` Interpretation.

Did you have any issues with TIOFeatures in go-hep?

**Comment by pcanal** [comment]
This must be the checksum.  TIOFeatures does not (yet?) have a class version.  See TBufferFile::ReadVersion

**Comment by PerilousApricot** [comment]
I just hit something similar in my [java implementation](https://github.com/PerilousApricot/spark-ttree). It appears the streamers call for 7 bytes to be read from ROOT::TIOFeatures, but the byteCountMask thinks there should be 11 bytes. Is there anything of value in this class, or can it just be ignored?

**Comment by jpivarski** [comment]
The main feature this currently provides (it exists to provide more features in the future) is to specify when offsets aren't explicitly given for jagged branches with a counter branch. In principle, if you have a counter branch, then you never need the offsets in each individual branch.

Early runs with CMS NanoAOD found a 20% savings in disk space with this technique. However, only ROOT readers with `TIOFeatures` handling (i.e. recent versions) can read such files—it breaks forward compatibility. I don't know whether standard NanoAOD is using this feature, given that trade-off. If not, then handling it could be put off for later. If so, then none of the NanoAOD would be readable without it.

**Comment by PerilousApricot** [comment]
Makes sense -- but I'm a bit confused about why (deep down) ROOT's streamers say it's only a uchar instead of the actual length. I'm implementing the same one-off hardcoding of the handling for that class (like uproot, which is how I got here), but the less special-casing the better
