### ISSUE TITLE
Uproot cannot recover the content of a non properly closed ROOT file.

### ISSUE THREAD

**Issue by DanielLopezCoto** [scikit-hep/uproot#472]
I realized that if a ROOT file has to be recovered (because it was not closed properly for any reason), uproot is not able to read its content, and returns an empty list when doing:
```
 in: file = uproot.open("random_file.root")
 in: list_of_keys = file.keys()
 in: list_of_keys
out: [ ]
```
Is there actually a way to recover those files contents just like ROOT does when loading such files?

Thank you!
Daniel.

**Comment by tamasgal** [comment]
Can you somehow upload that file so we can have a look? If it's too big, I can take care of it, just let me know...

**Comment by DanielLopezCoto** [comment]
I can give you the path in the Cluster where it is... I am afraid that if I upload it won't worth it, because I have my RAM in bad state and every time I copy any file from the Cluster to my laptop the file gets corrupted.

**Comment by jpivarski** [comment]
There's a recovery procedure for TBaskets in a TTree, when the TTree is in a partially written state.

For named objects that aren't listed in a TDirectory, there isn't a recovery procedure in Uproot. It's likely they're simply not in the file to be recovered. I suppose there's a chance that the object might have been written without updating the TDirectory, so it would be physically in the file but nothing points to it, and in that case it would be in principle recoverable if the object could be found among all those raw bytes, but scanning to find such a thing would be pretty expensive. (Regex for `"TKey"` on raw bytes and deal with the false matches? It sounds brittle, and only handles a corner case of "object written, but TDirectory not updated.")

**Comment by DanielLopezCoto** [comment]
Ok, I solved the issue re-making the files.
Maybe it could have been solved using what you said, but really I don't know how.

Thanks anyway!

**Comment by jpivarski** [comment]
You're welcome; glad you have a solution!
