### ISSUE TITLE
Fast-forward with uproot.iterate() for debuging purpose

### ISSUE THREAD

**Issue by zhenbinwu** [scikit-hep/uproot#479]
I am current using the uproot.iterate() to read and process a list of NanoAOD files. For debugging purpose, I need to read directly Nth group of the iterator. This was implemented using `if continue`. But it seems the reading and unpacking still taking a long time. Is there a better way to handle this with iterate()? I am expecting lazyarray could provide an alternative solution, but it require some heavy modification of my current code. Thanks

**Comment by jpivarski** [comment]
If you are reading multiple files with `uproot.iterate` and `entrysteps` has the default value of `np.inf` (see [documentation](https://uproot.readthedocs.io/en/latest/opening-files.html#uproot-iterate)), then the Nth step of iteration is the Nth file. The `entrysteps` is the number of chunks per file, so setting it to infinity means one step per file.

If you set `entrysteps` manually to a number of entries, you can use `entrystart` and `entrystop` to jump to that location in [tree.arrays](https://uproot.readthedocs.io/en/latest/ttree-handling.html#arrays). If you set it to a memory size (e.g. `entrysteps="100 MB"`), then there's a [tree.mempartitions](https://uproot.readthedocs.io/en/latest/ttree-handling.html#uproot.tree.TTreeMethods.mempartitions) function you can use to find out what this corresponds to in terms of entries.

**Comment by jpivarski** [comment]
I'm guessing I can close this? Let me know if I'm wrong.
