### ISSUE TITLE
Key not found error when key is there

### ISSUE THREAD

**Issue by sarah-alam-malik** [scikit-hep/uproot#484]
Hi, 

I'm trying to read a root file and get an exception when reading a particular variable (Muon_tunepRelPt)- I've checked that this key is present in the root file and I have the correct name etc. 
What else should I look at? 

Thanks!

Sarah

File "/vols/build/cms/samalik/miniconda2/envs/zinv37new2/lib/python3.7/site-packages/uproot/tree.py", line 391, in get
    raise uproot.rootio._KeyError("not found: {0}\n in file: {1}".format(repr(name), self._context.sourcepath))
KeyError: not found: b'Muon_tunepRelPt'  in file: root://xrootd-cms.infn.it///store/mc/RunIISummer16NanoAODv4/DYJetsToLL_Pt-250To400_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/PUMoriond17_Nano14Dec2018_102X_mcRun2_asymptotic_v6-v1/10000/3A4FF9EE-E857-2046-AFB7-B5AF9077D05F.root

**Comment by jpivarski** [comment]
I can't access this file. Could you make a copy accessible so that I can try it and find out what's wrong?

(Dropbox, CERNBox, attach to this issue in GitHub, send me an email, etc. If this file can't be made public, email or Google Drive can be private. I'm a CMS member, but I haven't updated my VO certificates in a long time.)

Thanks!

**Comment by sarah-alam-malik** [comment]
Thanks. The file is 1 GB so not easy to upload anywhere - I'm trying to figure out how to skim a relevant event (not all events in the file have this variable I'm interested in) and then send it - I can get a skimmed root file but it only has the first event. Will get back to you.

**Comment by jpivarski** [comment]
The skimmed file might not have the same problem. As a quick check, could you show me a log of all the steps you took, including printing out the `tfile.keys()` and `ttree.keys()` (maybe also the `allkeys()`) to see what the inconsistency is?

**Comment by sarah-alam-malik** [comment]
the uproot package is invoked as part of a much larger and quite dense framework so it's not easy to see exactly what steps are taken. When I try a simple import uproot and ask for the tfile.keys() etc I can see this variable is there. However, when I run on this file as part of the larger analysis framework then I get the above error (it only seems to be for this variable and not others). 
I thought there might be something obvious that I need to look at, but likely I'll have to go through the steps of the full framework to see why this is happening.

**Comment by jpivarski** [comment]
If you can see it and access it from Uproot directly, then whatever is happening is not an error in Uproot. That's valuable information for tracking it down.

**Comment by sarah-alam-malik** [comment]
ok, great, thanks!

**Comment by jpivarski** [comment]
I'm guessing I can close this? Let me know if I'm wrong.
