### ISSUE TITLE
Writing a TH2 into file

### ISSUE THREAD

**Issue by xaratustrah** [scikit-hep/uproot#488]
In the [readme section](https://github.com/scikit-hep/uproot#writing-histograms), there is an example of writing a TH1 histogram created entirely in Python. This example works very well. I am now trying to do the same thing using a TH2, which I posted [here on StackOverflow](https://stackoverflow.com/q/61752417/5177935), still without success.

On *line 135* in function `allvalues` in file `~/Library/anaconda3/lib/python3.7/site-packages/uproot_methods/classes/TH2.py` I see:

```
v = v.reshape(self.ynumbins + 2, self.xnumbins + 2)
``` 

I don't understand the addition of +2 here? Or if this is OK, how is the proper way to fill the histogram?

thanks.

**Comment by sbinet** [comment]
it's for the under- and over-flow bins.

**Comment by xaratustrah** [comment]
OK that sounds plausible. Keeping that in mind, do you have any ideas how to correctly fill the histogram? please have a look at [the StackOverflow post](https://stackoverflow.com/q/61752417/5177935).

**Comment by xaratustrah** [comment]
ok, small progress: if I now consider the under and overflow bin, then instead of 4 x 6 = 24, I need 6 x 8 = 48 data points. If I give this to the class, then it creates the TH2 histogram. Here is the code:

```
import types
import uproot
import uproot_methods.classes.TH2
import numpy as np

class MyTH2(uproot_methods.classes.TH2.Methods, list):
    def __init__(self, xlow, xhigh, xnbins, ylow, yhigh, ynbins, values, title=""):
        self._fXaxis = types.SimpleNamespace()
        self._fXaxis._fNbins = xnbins
        self._fXaxis._fXmin = xlow
        self._fXaxis._fXmax = xhigh
        self._fYaxis = types.SimpleNamespace()
        self._fYaxis._fNbins = ynbins
        self._fYaxis._fXmin = ylow
        self._fYaxis._fXmax = yhigh
        for x in values:
            self.append(float(x))
        self._fTitle = title
        self._classname = "TH2F"

th2 = MyTH2(-5, 5, 6, -8, 8, 4, np.random.rand(48), title='')
file = uproot.recreate("tmp3.root", compression=uproot.ZLIB(4))
file["th2"] = th2
```

A histogram is actually created. But if I open the histogram with `TBrowser()`, it just shows a blank canvas. If I hover the mouse over its canvas, then I see different bins and their values change in the status bar. These are the same values one gets with `th2.values`. So the histogram is there, and has values but it doesn't show any bars / colors, etc.

Also the fact that one needs to include the underflow and overflow bin, makes filling the histogram more difficult specially in the 2D case.

or maybe the histogram should be filled differently?

**Comment by jpivarski** [comment]
I found an example of writing 2D histograms with Uproot:

https://nbviewer.jupyter.org/github/jpivarski/2019-07-29-dpf-python/blob/master/04-uproot.ipynb#Writing-to-ROOT-files

This example uses `np.histogram2d` as a source. If you're building the TH2 manually, you might be setting the style parameters to invisible values: this `np.histogram2d` example chooses reasonable defaults that you can port over to your procedure.

This is the code that creates the TH2 from the NumPy source:

https://github.com/scikit-hep/uproot-methods/blob/16feba9f7bee365b6113d6af029e6a9364c74ece/uproot_methods/classes/TH2.py#L226-L272

**Comment by sbinet** [comment]
the mechanics of creating a TH2x that ROOT correctly reads *and* displays are... interesting. (for some definition of _interesting_.)

if you want some inspiration, you can have a look at the equivalent `groot` code:
- https://github.com/go-hep/hep/blob/master/groot/rhist/h2_gen.go#L35
- https://github.com/go-hep/hep/blob/0f7b59f24c5e4473d8c4cee5ebe436249a05384b/groot/rhist/hist.go#L256
- https://github.com/go-hep/hep/blob/0f7b59f24c5e4473d8c4cee5ebe436249a05384b/groot/rhist/hist.go#L47

(especially the last one that creates the expected default values for TH2x that TBrowser expects)

**Comment by xaratustrah** [comment]
> I found an example of writing 2D histograms with Uproot:
> 
> https://nbviewer.jupyter.org/github/jpivarski/2019-07-29-dpf-python/blob/master/04-uproot.ipynb#Writing-to-ROOT-files
> 
> This example uses `np.histogram2d` as a source. If you're building the TH2 manually, you might be setting the style parameters to invisible values: this `np.histogram2d` example chooses reasonable defaults that you can port over to your procedure.
> 
> This is the code that creates the TH2 from the NumPy source:
> 
> https://github.com/scikit-hep/uproot-methods/blob/16feba9f7bee365b6113d6af029e6a9364c74ece/uproot_methods/classes/TH2.py#L226-L272

yes, indeed it works and is displayed properly in `TBrowser`. So I have to see what is the difference in this case, with the case of a TH2 histogram with bars / colours, i.e. what should I write into the file using `uproot`, so that later it is later recognized by TBrowser as a proper TH2. Currently, if I open the chart editor it does not offer me the options like "3D LEGO" etc... like it usually does it with other TH2 histograms. Some value must be set somewhere in the file structure, I guess this was the core of the hint @sbinet provided in their reply.

**Comment by jpivarski** [comment]
I don't know anything about how the TBrowser decides what to show, but everything that defines the TH2 is in the attributes with names that begin with `_f`, including nested ones, like `_fXaxis` (which has its own nested attributes). The difference between the one you're making and the one that the `np.histogram2d` → `TH2` is making (see code link above) is in those attributes.

**Comment by jpivarski** [comment]
I'm guessing I can close this? Let me know if I'm wrong.
