### ISSUE TITLE
Request for nested array support

### ISSUE THREAD

**Issue by chamindu123** [scikit-hep/uproot#489]
Hello!
In this previous [issue](https://github.com/scikit-hep/uproot/issues/39) it looked like support for doubly nested jagged data was on the roadmap. Is this still the case? 
I've been resorting to using `fromiter()` to convert the the `arrays()` output of type `ObjectArray` to a jagged arrays. I wonder if this is still the best way?
Thanks.

**Comment by jpivarski** [comment]
It's still the best way.

It will become automatic in [Uproot4](https://github.com/scikit-hep/uproot4), which uses [Awkward1](https://github.com/scikit-hep/awkward-1.0)'s more efficient [ak.from_iter](https://awkward-array.readthedocs.io/en/latest/_auto/ak.from_iter.html) or even more efficient [ak._io.fromroot_nestedvector](https://awkward-array.readthedocs.io/en/latest/ak._io.fromroot_nestedvector.html) for the special case of `std::vector^N<number>`, which is what was shown in the last slide of [this talk](https://indico.cern.ch/event/773049/contributions/3473258/) ([proceedings](https://arxiv.org/abs/2001.06307)).

I'm working on this right now, in fact.

**Comment by chamindu123** [comment]
Great, thanks for developing these useful programs!
