### ISSUE TITLE
uproot: read performances -- official benchmark

### ISSUE THREAD

**Issue by sbinet** [scikit-hep/uproot#490]
hi there,

I vaguely remember Jim showing reading performances of uproot _wrt_ ROOT/C++ (and/or PyROOT?).

I've recently quite improved (x3!) the read performances of groot (beating ROOT C++ w/ SetBranch and TTreeReader) and I would like to get some more perf ground covered.

are the bench scripts from uproot still available somewhere?

**Comment by jpivarski** [comment]
That's fantastic! Congratulations!

I don't remember which test that was, but it's probably not something that could be easily revived. But this is a well-known set of benchmarks:

https://indico.cern.ch/event/567550/contributions/2628878/

This study was from 2017 (it was intended to compare ROOT against a variety of industry formats), but it's still widely quoted, so it's a well-known target. The one thing that it lacks, however, is jagged structure: there are nested structs here, but all fixed-size records.

Try that!

**Comment by tamasgal** [comment]
Ah nice and congrats @sbinet !

I will certainly look at those benchmarks. Currently I occasionally compare my Julia library to `uproot` as reference, just to see if I am on the right path :)

**Comment by sbinet** [comment]
yeah, @jblomer was next on my list of people to bother. (I remember him showing a couple of slides of ROOT `TTree` _vs_ `RNtuple` performances)

**Comment by jblomer** [comment]
A newer set of benchmarks that include the 2017 LHCb open data one can be found here: https://github.com/jblomer/iotools/tree/calibration

They include the (jagged) sample analyses based on CMS and the old H1 data formats, too.  I just added another one using the 2020 ATLAS open data (https://github.com/jblomer/iotools/tree/parallel-decompression).

The corresponding presentation looking at TTree and RNTuple for the first three benchmarks is https://indico.cern.ch/event/773049/contributions/3474746/attachments/1937507/3211341/rntuple-chep19.pdf

**Comment by sbinet** [comment]
FYI, here is what I came up with:
- https://root-forum.cern.ch/t/gohep-groot-v0-27-0-root-split-groot-faster-than-root/39609
- https://github.com/go-hep/groot-bench

```
name                               time/op
ReadCMS/GoHEP/Zlib-8               19.2s ± 1%
ReadCMS/ROOT-TreeBranch/Zlib-8     37.5s ± 1%
ReadCMS/ROOT-TreeReader/Zlib-8     26.1s ± 3%
ReadCMS/ROOT-TreeReaderMT/Zlib-8   25.6s ± 5%  (ROOT::EnableImplicitMT())

ReadScalar/GoHEP/None-8            737ms ± 3%
ReadScalar/GoHEP/LZ4-8             769ms ± 3%
ReadScalar/GoHEP/Zlib-8            1.33s ± 1%
ReadScalar/ROOT-TreeBranch/None-8  1.22s ± 3%
ReadScalar/ROOT-TreeBranch/LZ4-8   1.35s ± 3%
ReadScalar/ROOT-TreeBranch/Zlib-8  2.47s ± 1%
ReadScalar/ROOT-TreeReader/None-8  1.43s ± 5%
ReadScalar/ROOT-TreeReader/LZ4-8   1.57s ± 2%
ReadScalar/ROOT-TreeReader/Zlib-8  2.69s ± 1%
```

compared to the old `Go-HEP@v0.26`:
```
name                     time/op
ReadScalar/GoHEP/None-8  1.27s ± 3%
ReadScalar/GoHEP/LZ4-8   1.39s ± 1%
ReadScalar/GoHEP/Zlib-8  4.10s ± 1%
```

(statistical uncertainty, computed over 20 runs with [benchstat](https://golang.org/x/perf/cmd/benchstat))

**Comment by tamasgal** [comment]
Quite impressive! Btw. which ROOT version and compiler did you use? I tried to replicate the benchmark results (ROOT 6.18.04 and 6.20.04 with GCC 4.8.2 and 9.2.1) but got errors like

```
./cxx-root/read-scalar-rd.cxx:21:31: error: use of deleted function ‘TTreeReader::TTreeReader(const TTreeReader&)’
  auto r = TTreeReader(tname, f);
```

and 

```
ROOT::Internal::TNamedBranchProxy> > >]’ is implicitly deleted because the default definition would be ill-formed:
       unordered_map(const unordered_map&) = default;
       ^
/usr/include/c++/4.8.2/bits/unordered_map.h:168:7: error: use of deleted function ‘std::__allow_copy_cons<false>::__allow_copy_cons(const std::__allow_copy_cons<false>&)’
```

**Comment by sbinet** [comment]
FTR, it's ROOT 6.20/04 and gcc 10.1.0.
(I am on archlinux, 64b)
