### ISSUE TITLE
Add Zenodo DOI

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/uproot#51]
Hi Jim. What do you think about getting a [Zenodo](https://zenodo.org/) DOI for `uproot` (and badge for the README)? I think it would be nice for citations.

**Comment by jpivarski** [comment]
That's a good idea. Since I'm creating releases so frequently (to keep PyPI up to date), the Zenodo would also be easy to keep up to date.

There you are:

https://github.com/scikit-hep/uproot/blob/master/README.rst

**Comment by matthewfeickert** [comment]
Fantastic! :)

**Comment by matthewfeickert** [comment]
Hi @jpivarski, [this bug](https://github.com/zenodo/zenodo/issues/912) that [Lukas and I saw](https://github.com/diana-hep/pyhf/issues/90) also affects you. So I think that you want to change your badge `rst` to
```
.. image:: https://zenodo.org/badge/DOI/10.5281/zenodo.1173083.svg
   :target: https://doi.org/10.5281/zenodo.1173083
```
which should then create the following up to date badge
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1173083.svg)](https://doi.org/10.5281/zenodo.1173083)

**Comment by jpivarski** [comment]
Thanks!
