### ISSUE TITLE
Converting certain sub branches to arrays doesn't work

### ISSUE THREAD

**Issue by shahidzk1** [scikit-hep/uproot#535]
I have a complicated tree with branches and sub branches. Some of the branches are recognized and picked by uproot while others aren't. For exapmle the momentum distribution fPx branch. 
![Screenshot from 2021-02-15 18-09-58](https://user-images.githubusercontent.com/47216877/107975887-0ba61a00-6fb9-11eb-95d2-7284ab40ebaa.png)

Pyroot shows that they are Double32_t type branches
![Screenshot from 2021-02-15 18-13-08](https://user-images.githubusercontent.com/47216877/107976268-91c26080-6fb9-11eb-87c9-86d094d5fa3d.png)

Could you help me some how convert these sub branches to arrays?

**Comment by jpivarski** [comment]
I'll handle this in scikit-hep/uproot4#268. (If you hadn't copied it, I would have used GitHub's "transfer issue" to get it over there, but this is just as good.)
