### ISSUE TITLE
Can't access some branches in MiniAOD

### ISSUE THREAD

**Issue by yhs07128** [scikit-hep/uproot#536]
I'm trying to read some branch

`patMETs_slimmedMETs__PAT.obj.m_state.p4Polar_.Pt()`

in MiniAOD, but uproot doesn't recognize it as a branch. If I do

`event['patMETs_slimmedMETs__PAT.'].show()`

it shows that the branch is not interpreted properly.

name                 | typename                 | interpretation    
---------------------+--------------------------+-------------------------------
patMETs_slimmedMETs_ | edm::Wrapper<vector<pat: | AsGroup(<TBranchElement 'patMEpatMETs_slimmedME... | bool                     | AsDtype('bool')
patMETs_slimmedME... | unknown                  | <UnknownInterpretation 'non...

There are multiple other branches with the same problem, but I'm not sure what's causing it.

**Comment by tamasgal** [comment]
Have you tried to read the file with `uproot4`? The new version is highly recommended and can easily be installed e.g.  via `pip install -U uproot`.

Edit: just realised, it's `uproot4` ;)

**Comment by yhs07128** [comment]
Actually I'm using uproot4. Should move the issue.
