### ISSUE TITLE
Cannot write u8 type

### ISSUE THREAD

**Issue by wiso** [scikit-hep/uproot#537]
I get an `NotImplementedError` when trying to write a u8 type (l : a 64 bit unsigned integer (ULong64_t) in ROOT).

I tried to naively add here https://github.com/scikit-hep/uproot3/blob/master/uproot3/write/objects/TTree.py#L818

```
   elif self.type == ">u8":
            title_pad = b"/l"
            self.fields["_fLeaves"] = [self, "TLeafl"]
```

but it seems not sufficient since when opening it with ROOT I get a segmentation fault.
I can't use uproot4 since I need to write a TTree.

**Comment by jpivarski** [comment]
I don't think there's any such thing as a `TLeafl` (lowercase "`l`") class.

![](https://root.cern.ch/doc/master/classTLeaf__inherit__graph_org.svg)

(from https://root.cern.ch/doc/master/classTLeaf.html)

That would explain the segmentation fault. However, `TLeaf` has a `fIsUnsigned` boolean, which presumably only has meaning for the leaf-types that describe integers.

https://github.com/root-project/root/blob/87a998d48803bc207288d90038e60ff148827664/tree/tree/inc/TLeaf.h#L76

The Uproot 3 implementation always sets this to False (in the nested `put_tleaf` function):

https://github.com/scikit-hep/uproot3/blob/54f5151fb7c686c3a161fbe44b9f299e482f346b/uproot3/write/objects/TTree.py#L897

What should happen instead is that each of these type tests should set `fIsUnsigned` to False except for new ones that check for the unsigned integer types, which should set `fIsUnsigned` to True, and the nested `put_tleaf` function should not set `fIsUnsigned`.

https://github.com/scikit-hep/uproot3/blob/54f5151fb7c686c3a161fbe44b9f299e482f346b/uproot3/write/objects/TTree.py#L796-L819

Also, all of these types will be handled correctly from the outset in Uproot 4 file-writing.

https://github.com/scikit-hep/uproot4/discussions/321

**Comment by wiso** [comment]
ok, I will wait for the new version of uproot4
