### ISSUE TITLE
NotImplementedError when using newtree("var",np.uint64)

### ISSUE THREAD

**Issue by bualust** [scikit-hep/uproot#540]
I need to declare a branch of the type unsigned long long int. I get the NotImplementedError so I imagine this is being developed. Is there any workaround for now?

**Comment by jpivarski** [comment]
Did you switch over to Uproot 4? The `newtree` name is an Uproot 3 thing; here's how it looks in Uproot 4:

```python
>>> import uproot
>>> import numpy as np
>>> f = uproot.recreate("new-file.root")
>>> array = np.arange(10, dtype=np.uint64)
>>> f["tree"] = {"branch": array}
>>> f.close()
>>> 
>>> 
>>> f2 = uproot.open("new-file.root")
>>> f2["tree/branch"].array()
<Array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] type='10 * uint64'>
```

(Should use `with` statements, of course; I'm being lazy.)
