### ISSUE TITLE
ValueError: attempting to read TAttLine object version 2 with a class generated by streamer version 1

### ISSUE THREAD

**Issue by fyuuhi** [scikit-hep/uproot#56]
I cannot read root files (~13GB) like below (python 2.7.13).
```
>>> branch = uproot.open("/path/to/mydir/foo.root")["mytree"]['mybranch']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/workdir/envname/lib/python2.7/site-packages/uproot/rootio.py", line 219, in __getitem__
    return self.get(name)
  File "/path/to/workdir/envname/lib/python2.7/site-packages/uproot/rootio.py", line 334, in get
    return key.get()
  File "/path/to/workdir/envname/lib/python2.7/site-packages/uproot/rootio.py", line 827, in get
    return self._context.classes[classname].read(self._source, self._cursor.copied(), self._context, self)
  File "/path/to/workdir/envname/lib/python2.7/site-packages/uproot/rootio.py", line 764, in read
    out = cls._readinto(out, source, cursor, context, parent)
  File "<generated from TStreamerInfo 'TTree' at 0x7fe3f7f22390>", line 11, in _readinto
  File "<generated from TStreamerInfo 'TAttLine' at 0x7fe3f7f223d0>", line 9, in _readinto
ValueError: attempting to read TAttLine object version 2 with a class generated by streamer version 1

```
I don't understand what happens, so any idea?

Best regards

**Comment by jpivarski** [comment]
Could I see a copy of this file? It says that the data in the file aren't consistent with the class definitions in the same file.

**Comment by jpivarski** [comment]
Incidentally, it has nothing to do with the size of the file. The same would probably be true of an empty TTree, made the same way.

TTree is a subclass of TAttLine, and therefore it has to deserialize TAttLine just to read the header of the TTree.

**Comment by jpivarski** [comment]
Hi again! Please let me see an example file, even if it's not one that can be made public in unit tests. I'm working on streamers right now and so now would be a great time to fix this.

I'm thinking it might be that `hadd` combined two files with different versions of a streamer for `TAttLine`, so they're both in the streamers table, and I made a class from one and ignored the other. Thus, my class lookup should be by class name _and_ version, rather than just class name, and that will require some thinking that I would not want to do purely theoretically (without an example file).

Thanks!

**Comment by fyuuhi** [comment]
Thank you.

I surely `hadd` two files which has same `TTree`, `TBranch`. But I cannot understand difference between two files `version`. These were made by same methods.

Can you acsess CERN-lxplus server (/afs/cern.ch/user/...) ? I can put these root files on lxplus or send link to these root files.

My using verions is below:
```
python 2.7.13
 pip version 6.0.8
```

Best regards.

**Comment by jpivarski** [comment]
Yes, please put them on lxplus with permissions sick that user `pivarski` can access them (me). Thanks!

**Comment by fyuuhi** [comment]
Defualt environment,
```sh
$ which hadd
 /usr/bin/hadd  # when this hadd, failure uproot.open   
```
After 
```sh
$ export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase 
$ alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
$ setupATLAS 
$ lsetup root
```
,
```sh
$ which hadd
/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/6.10.04-x86_64-slc6-gcc62-opt/bin/hadd
```
For root files hadded after `lsetup root`, `uproot.open` is succesfully worked. However, root files made by default `hadd`, `uproot.open` is failured.
So I think the cause is `hadd` version (ROOT5 or ROOT6 ?).

I put root files on "/afs/cern.ch/user/y/yfukuhar/public/test_uproot/".

`before_01.root` and `before_02.root` are not `hadded` files. 
`hadd_default.root` is  made by default `hadd`:
```
$ hadd hadd_default.root before_01.root before_02.root # default hadd
```
For `hadd_defalut.root`,
```python
branch = uproot.open('~/public/test_uproot/hadd_default.root')['t_tap']['probe_pt']
>>> (some messages)
ValueError: attempting to read TBranchElement object version 9 with a class generated by streamer version 10
```

`hadd_v6.root` is  made after `lsetup root`:
```
$ hadd hadd_v6.root before_01.root before_02.root # hadd after lsetup root
```
For `hadd_v6.root`,
```python
branch = uproot.open('~/public/test_uproot/hadd_v6.root')['t_tap']['probe_pt']
>>> # sucess
```

Best regards

**Comment by fyuuhi** [comment]
With that update, I think that `uproot` will be more useful for me !!!
Thanks:smile:!
