### ISSUE TITLE
TVector2 & TVector3 in a nested TTree

### ISSUE THREAD

**Issue by kreczko** [scikit-hep/uproot#74]
From #57 it looks like there should be no problem reading TVector3 and vectors thereof.
However, when reading a quite nested structure with uproot, I get
```
  for events in uproot.iterate(input_files, "Events", branches=branches):
  File "/home/lzuser/.local/lib/python2.7/site-packages/uproot/tree.py", line 120, in iterate
    for tree, newbranches, globalentrystart in _iterate(path, treepath, branches, localsource, xrootdsource, httpsource, **options):
  File "/home/lzuser/.local/lib/python2.7/site-packages/uproot/tree.py", line 144, in _iterate
    listbranches = list(tree._normalize_branches(branches))
  File "/home/lzuser/.local/lib/python2.7/site-packages/uproot/tree.py", line 708, in _normalize_branches
    raise ValueError("cannot interpret branch {0} as a Python type".format(repr(branch.name)))
ValueError: cannot interpret branch 'singleScatters.xyzPosition' as a Python type
```
where `singleScatters` is a vector of a class (`Interaction`) and `xyzPosition` is a `TVector3`. The full structure is
```yaml
  - Events: `TTree`
    - `RQEvent`: Event class containing vectors of other classes
      - `singleScatters`: vector of `Interaction` class
        - `xyzPosition`: `TVector3`
```

Reading a `float` from the same `Interaction` class works.
Comparing `.show()` between the two:
```
singleScatters.driftTime   TStreamerBasicType         asjagged(asdtype('>f4'))
None
#
singleScatters.xyPosition  TStreamerObject            None
None
```

**Comment by jpivarski** [comment]
Yeah... funny story... The request in #57 was for `std::vector<anything>`, not `anything`, and they didn't have any examples of an object not inside of a `std::vector`, so I only implemented the former. uproot is in a weird position of being able to read (in theory) any kind of object in a TTree, but only if it is also in a `std::vector` (i.e. zero or more per event, but not exactly one per event). We've been looking for a good case to fill this gap, and yours is it.

@reikdas has been working on this as a practice problem, but the only example we had of a streamer-defined object in a TTree without also being in a `std::vector` was the `Event.root` from the ROOT unit tests that has whole histograms in a TTree branch. Your example is simpler and would be a much easier case for developing this feature. Could you send a sample file?

Ideally, could you attach a small (< MB) file with a few events that would not be considered confidential by your experiment? That way, we could add it to the unit tests to know if the feature ever breaks in the future. GitHub has a hidden feature where you can drag and drop such files into an issue chat box, but maybe you have to change the file extension or compress it first.

**Comment by kreczko** [comment]
Thanks for the quick response.
I will ask the simulation contacts about confidentiality and will try to reduce the file below 10 MB (currently 124 MB).

**Comment by kreczko** [comment]
OK, managed to create a dummy file with similar structure ([dummy.root.tar.gz](https://github.com/scikit-hep/uproot/files/1938972/dummy.root.tar.gz) - 1000 entries, created with https://goo.gl/ihHSZm)
To reproduce:
```python
import uproot

branches = [
    'ayes.start_ns',
    'ayes.start_ns',
    'bees.driftTime',
    'bees.xyzPosition',
    'eventID',
]

for events in uproot.iterate(['dummy.root'], 'Events', branches=branches):
    print(events)
```
output should be
```
Traceback (most recent call last):
  File "kreczko/dummy.py", line 24, in <module>
    for events in uproot.iterate([input_file], "Events", branches=branches):
  File "/home/lzuser/.local/lib/python2.7/site-packages/uproot/tree.py", line 120, in iterate
    for tree, newbranches, globalentrystart in _iterate(path, treepath, branches, localsource, xrootdsource, httpsource, **options):
  File "/home/lzuser/.local/lib/python2.7/site-packages/uproot/tree.py", line 144, in _iterate
    listbranches = list(tree._normalize_branches(branches))
  File "/home/lzuser/.local/lib/python2.7/site-packages/uproot/tree.py", line 708, in _normalize_branches
    raise ValueError("cannot interpret branch {0} as a Python type".format(repr(branch.name)))
ValueError: cannot interpret branch 'bees.xyzPosition' as a Python type
```

**Comment by jpivarski** [comment]
@reikdas: Please let me know (here) if you've downloaded this file and are working on it. Thanks!

**Comment by jpivarski** [comment]
For @reikdas: I've modified `uproot.interp.auto.interpret` to add support for `Double32_t`. You'll have an easier time merging if you start from the latest master.

**Comment by jpivarski** [comment]
The pull request is good; it closed this issue. Try it out in `master` or the next version.

**Comment by jpivarski** [comment]
In the debugging of uproot 3, I noticed that this issue was handled incorrectly— the issue74.root file contains _arrays_ of `TVector3` (and `TVector2`) objects, not `std::vectors` but not single objects, either. Each array is jagged— it may have any number of items per event, but in this file, it always has exactly two. The old code was reading just the first one.

uproot 3 will handle this case right, as well as single-object events, which I'm testing independently.

**Comment by kreczko** [comment]
Thanks for updating the issue!
