### ISSUE TITLE
Vectors of TString in a nested TTree

### ISSUE THREAD

**Issue by kreczko** [scikit-hep/uproot#76]
# Summary
From the documentation, it seems that strings and vectors of strings are indeed supported.
However, vectors of TString cause problems:
```
Traceback (most recent call last):
...
  File "/software/cmsl1t/miniconda/envs/cms/lib/python2.7/site-packages/uproot/interp/auto.py", line 256, in interpret
    return asobjs(branch._vecstreamer.pyclass, branch._context)
AttributeError: 'TStreamerInfo' object has no attribute 'pyclass'
```

More details on the particular structure
 - https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TNtuples/interface/L1AnalysisEventDataFormat.h#L43
 - https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TNtuples/src/L1AnalysisEvent.cc#L66

# Example code
Example file: [issue_76.tar.gz](https://github.com/scikit-hep/uproot/files/1967119/issue_76.tar.gz)

Code
```python
import uproot

f = uproot.open('issue_76.root')
events = f['Events']
events['normalStrings'].show()
events['rootStrings'].show()
```

Output:
```
normalStrings              TStreamerSTL               asvar(ListStrings, skip_bytes=10)
Traceback (most recent call last):
  File "bin/dummy.py", line 8, in <module>
    events['rootStrings'].show()
  File "/software/cmsl1t/miniconda/envs/cms/lib/python2.7/site-packages/uproot/tree.py", line 1523, in show
    for line in self._format(foldnames):
  File "/software/cmsl1t/miniconda/envs/cms/lib/python2.7/site-packages/uproot/tree.py", line 1510, in _format
    out = [indent + "{0:26s} {1:26s} {2}".format(name, "(no streamer)" if self._streamer is None else self._streamer.__class__.__name__, interpret(self))]
  File "/software/cmsl1t/miniconda/envs/cms/lib/python2.7/site-packages/uproot/interp/auto.py", line 256, in interpret
    return asobjs(branch._vecstreamer.pyclass, branch._context)
AttributeError: 'TStreamerInfo' object has no attribute 'pyclass'
````

**Comment by jpivarski** [comment]
@reikdas: Could you look into this? Create a new branch and pull request as before.

It is true that `TString` has no `pyclass`. And I think the "handling of strings" went as far as `std::string` and `char *`, so there very well could be some special cases to handle with ROOT's `TString`.

**Comment by jpivarski** [comment]
Thanks! (It's good practice, I promise!)

**Comment by kreczko** [comment]
Thanks!
