### ISSUE TITLE
Problem reading branches with more than one basket on Windows

### ISSUE THREAD

**Issue by kandrosov** [scikit-hep/uproot#79]
Hello,
I'm having problems to read any branches that have more than one basket on Windows. The same files are read without any problems on *nix or mac systems.

Here is a minimal example code and the output that illustrates a typical behaviour:
```python
import uproot
file = uproot.open('events.root')
events = file["events"]
pt = events["pt"].array()
```
Output:
```
Traceback (most recent call last):
  File "read_events.py", line 7, in <module>
    pt = events["pt"].array()
  File "C:\Users\konst\AppData\Roaming\Python\Python36\site-packages\uproot\tree.py", line 1202, in array
    self._tryrecover()
  File "C:\Users\konst\AppData\Roaming\Python\Python36\site-packages\uproot\tree.py", line 1490, in _tryrecover
    self._recover()
  File "C:\Users\konst\AppData\Roaming\Python\Python36\site-packages\uproot\tree.py", line 1486, in _recover
    raise ValueError("entries in recovered baskets (offsets {0}) don't add up to total number of entries ({1})".format(entryoffsets, self.numentries))
ValueError: entries in recovered baskets (offsets [0, 288691]) don't add up to total number of entries (1000000)
```
Here is a link to the input events.root used above:
https://www.dropbox.com/s/p480trum1l3f99z/events.root?dl=0

uproot version:  2.8.21

**Comment by jpivarski** [comment]
This is a bug that needs to be addressed, but note that the error happened during recovery of an incompletely closed file. If the `events.root` file was made with an explicit `ttree->Write(); tfile->Close()` before its writing process terminated, there wouldn't be any need to enter the recovery logic on reading. I'm telling you this in case the failure to read on Windows is a blocking error: you can get around it in more ways that switching to *nix/mac.

Meanwhile, does anyone have a Windows development machine they can use to debug this? I'm baffled that there's a difference between *nix/mac and Windows in this part of the program, which is just about interpreting bytes that have already been read.

**Comment by sbinet** [comment]
not sure the OS is really at play here.
FWIW, running `root-dump` on this file fails with:

```
$> root-dump ./events.root
>>> file[/home/binet/Downloads/events.root]
key[000]: taus;1 "taus" (TTree)
[000][pt]: 26.47025
[001][pt]: 21.148115
[...]
key[001]: events;1 "taus" (TTree)
[000][pt]: 26.47025
[001][pt]: 21.148115
[002][pt]: 66.06361
[...]
[711307][pt]: 26.304783
[711308][pt]: 60.293434
root-dump: error dumping file "/home/binet/Downloads/events.root": error dumping key "events": error scanning entry 711309: rootio: no basket for entry 711309
```

(on my ArchLinux machine)

**Comment by kandrosov** [comment]
Here how this example file was created from the original big TTree (which has exactly the same errors while reading on Windows with uproot):
```python
import ROOT

ROOT.gROOT.ProcessLine('ROOT::EnableImplicitMT(6)')

f_in = ROOT.TFile("TTToSemiLeptonic1_100.root", "READ")
taus = f_in.Get("taus")
taus.SetBranchStatus("*", 0)
taus.SetBranchStatus("pt", 1)

f_out = ROOT.TFile("events.root", "RECREATE")
f_out.SetCompressionAlgorithm(4)
f_out.SetCompressionLevel(3)
taus_out = taus.CloneTree(0)
taus_out.CopyEntries(taus, 1000000)
f_out.WriteTObject(taus_out, "taus", "Overwrite")
f_out.Close()
f_in.Close()
```
So, the file should be closed properly...
 
I tried again to open "events.root" on my Mac both using the uproot code quoted in the first message as well as using standard ROOT (see below) and I'm not getting any I/O warnings or errors....

```python
import ROOT
import numpy as np

file = ROOT.TFile("events.root", "READ")
events = file.Get("events")
pt = np.zeros(events.GetEntries())
n = 0
for event in events:
    pt[n] = event.pt
    n += 1
```

On the other hand, I confirm that root-dump gives the following error:
```
root-dump: error dumping file "events.root": error scanning entry 711309: rootio: no basket for entry 711309
```

**Comment by sbinet** [comment]
Go-HEP/rootio doesn't have (yet?) the TBasket recovery code that Jim put into uproot.

But I suppose there's some kind of racy behavior in C++ ROOT when multi-threaded TTree cloning is involved.

**Comment by kandrosov** [comment]
I recreated events.root without enabling implicit multi-thread in root. The result is the same...
https://www.dropbox.com/s/mmhs4cn76pja8e5/events_noMT.root?dl=0

**Comment by sbinet** [comment]
I guess it's a feature of 'CopyEntries' then.

**Comment by jpivarski** [comment]
As I understand it, neither the big TTree nor the small copy made with `CopyEntries` can be read in uproot on Windows (but can be in Mac and Linux?). The small copy looks invalid in root-dump, but ROOT is able to read it anyway. What does root-dump say about the big TTree?

Even if ROOT is able to read it, a file that fails ROOT's linter (root-dump) is probably not trustworthy for doing science. Are you sure you want to use this file? How do you know that what ROOT manages to read is correct? (If you do know it's correct, we can make uproot reproduce that behavior.)

**Comment by jpivarski** [comment]
Oh, okay. Yes, I misunderstood.

**Comment by reikdas** [comment]
@kandrosov , uproot isn't able to read the contents of the file in my linux machine as well. And I get the same stack trace and error you got on windows on my linux machine.

**Comment by jpivarski** [comment]
Okay, so it's not an operating system dependent thing (GOOD— that would make no sense).

Actually, do we have any confirmation that the original big file fails the same way? In certain modes, `TTree::CopyEntries` copies whole baskets without descending into their contents (for speed). That could copy an error from the original big file into the skim.

You know, this file has two TTrees in it, a "taus" TTree that presumably was copied unintentionally. ROOT says that both "taus" and "events" have 1000000 entries. When I look at it with uproot, "taus" looks like a good TTree with 711309 entries (its `TTree::fEntries` and `TBranch::fEntries` are in agreement on that, and I find exactly that many entries in its only basket). The The "events" TTree has the problems we've discussed.

But lo! If you combine the contents of the "taus" TTree with the subset that we can recover from "events", you get the right result!

```python
import ROOT
import numpy
import uproot

# read the data from ROOT, using ROOT's interpretation of the file
# (note: ROOT can see "taus" too, presenting it as having the same data)
file = ROOT.TFile("events.root")
events = file.Get("events")
rootarray = numpy.zeros(events.GetEntries())
n = 0
for event in events:
  rootarray[n] = event.pt
  n += 1

assert n == 1000000

# now from uproot, we can patch it together from both TTrees (using internal methods)
f = uproot.open("events.root")
taus = f["taus"]["pt"]
events = f["events"]["pt"]   # note: TObjArray.read can only be called ONCE per object
recoveredbasket = None
for basket in uproot.rootio.TObjArray.read(
        events._source,
        events.fBaskets._cursor,
        events._context,
        events,
        asclass=uproot.tree.TBranchMethods._RecoveredTBasket):
    if basket is not None:
        recoveredbasket = basket

# interpret the recovered basket as big-endian float32 and concatenate
recoveredarray = numpy.concatenate([
    taus.array(),
    recoveredbasket.basketdata().view(">f4")])

# ROOT and hacked-uproot agree!
print(numpy.absolute(rootarray - recoveredarray).max())
```

The trouble is, I don't see a way to make this a general method. Who would have thought that the missing data from "events" _is in another TTree_ named "taus"? (And then present both TTrees as having the same data?!?)

@kandrosov This is a seriously messed up file.  :)  Is there a reason you can't work directly with the big original? (I'd like to know if the original has the same feature or if that's something that `CopyEntries` introduced.) If you want to speed up your workflow by reading less data, know that you can pass `entrystart` and `entrystop` parameters to uproot branch-reading functions to limit how many you read.

**Comment by kandrosov** [comment]
@reikdas, hm... you are right, before I checked that uproot correctly reads the file only on my Mac, and wrongly "extrapolated" this behaviour to linux. My apologies.
However, I tried again and file reads just fine using ROOT (see code above) in both linux and Mac. I also checked that the data in the entries from the second basket looks "physical" and compatible with the data from the first basket, and not some "garbage"...

**Comment by kandrosov** [comment]
@jpivarski sorry, the first example file was messed up while create a copy, sorry. Please, use the second example file that I produced: https://www.dropbox.com/s/mmhs4cn76pja8e5/events_noMT.root?dl=0.

Here is a error message that I get when reading big file with uproot (again "standard" ROOT reads it correctly):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/soft/cmssw/slc6_amd64_gcc630/external/python/2.7.11-fmblme/lib/python2.7/site-packages/uproot/tree.py", line 1202, in array
    self._tryrecover()
  File "/soft/cmssw/slc6_amd64_gcc630/external/python/2.7.11-fmblme/lib/python2.7/site-packages/uproot/tree.py", line 1490, in _tryrecover
    self._recover()
  File "/soft/cmssw/slc6_amd64_gcc630/external/python/2.7.11-fmblme/lib/python2.7/site-packages/uproot/tree.py", line 1486, in _recover
    raise ValueError("entries in recovered baskets (offsets {0}) don't add up to total number of entries ({1})".format(entryoffsets, self.numentries))
ValueError: entries in recovered baskets (offsets [0, 262126, 524252, 711309, 1422618, 2133927, 2845236, 3556545, 4267854, 4979163, 5690472, 6401781, 7113090, 7824399, 8535708, 9247017, 9958326, 10669635, 11380944, 12092253, 12803562, 13514871, 14226180, 14937489, 15648798, 15851513]) don't add up to total number of entries (16562822)
```

**Comment by jpivarski** [comment]
Does the file read correctly in uproot on Mac? (I'd be very surprised about any difference related to operating system.)

I concur that both baskets are okay, not garbage, but they're in weird places in the file. When you ask ROOT for either the "events" or the "taus" TTree, it presents a two-basket view where the first basket comes from "taus" (and is good) and the second basket comes from "events" (and is recovered). That's where the data are in the file. I don't know how ROOT knows that it's supposed to splice the two TTrees together and present them as one.

**Comment by kandrosov** [comment]
@jpivarski yes on Mac uproot reads it correctly for some reason...
Sorry again, in the first example I changed the name of the tree while copying from "taus" in the original file to "events" and it additionally messed up the things. In the second example, I kept the original name of the tree "taus", please, try to use it: uproot gives exactly the same error on it.

**Comment by jpivarski** [comment]
Looking at it now. I see that the second `_noMT` file has only one TTree containing all the data...

**Comment by jpivarski** [comment]
Okay, yes. Things are falling into place. (I'm glad to hear we're not supposed to try to combine data from different TTrees!)

I can find all of the data in the file, but uproot's recovery mechanism must be unaware of this case. For instance, the following works:

```python
import ROOT
import numpy
import uproot

file = ROOT.TFile("/tmp/downloads/events_noMT.root")
tree = file.Get("taus")
rootarray = numpy.zeros(tree.GetEntries())
n = 0
for event in tree:
  rootarray[n] = event.pt
  n += 1

assert n == 1000000

f = uproot.open("/tmp/downloads/events_noMT.root")
branch = f["taus"]["pt"]
recovery = uproot.rootio.TObjArray.read(
    branch._source,
    branch.fBaskets._cursor,
    branch._context,
    branch,
    asclass=uproot.tree.TBranchMethods._RecoveredTBasket)

firstbasket = branch._basket(0, uproot.interp.asdtype(">f4"), 0, 711309, None, None)
secondbasket = recovery[1].basketdata().view(">f4")

uprootarray = numpy.concatenate([firstbasket, secondbasket])

print(numpy.absolute(rootarray - uprootarray).max())
```

The first basket is in its normal place, but somehow we don't include it in `_numgoodbaskets` and it doesn't get counted. (That's why the entries don't add up to 1000000, and it's also why I have to use the underscored version of the basket reading function, to bypass some mistaken sanity checks.)

The second basket needs to be recovered and the recovery is successful— it's in the second recovery slot (the first is `None`/`null`). But since uproot's `_numgoodbaskets` is off by one, we never get to the point where we can see it normally.

So it looks like we're 90% of the way there— uproot's recovery book-keeping has to be updated to include this case. @reikdas, can you look into this? The above shows how to get all the data; could you investigate why the book-keeping is wrong and how to fix it?

**Comment by jpivarski** [comment]
(Hopefully, solving the bug for the small file will fix it for the large file. It looks like it's missing one basket, too.)

**Comment by reikdas** [comment]
Sure.
