### ISSUE TITLE
tests/HZZ*.root typo in Photon_E branch descriptor

### ISSUE THREAD

**Issue by sbinet** [scikit-hep/uproot#8]
running `root-dump` on the `tests/HZZ.root` files I get:

```sh
$> root-dump HZZ.root
>>> file[HZZ.root]
key[000]: events;1 "" (TTree)
root-dump: error dumping file "HZZ.root": rootio: Tree "events" has no branch named "Photons_E"

```

and indeed:

```sh
root-ls -t HZZ.root 
=== [HZZ.root] ===
version: 53201
TTree                         events                                  (entries=2421)
  NJet                        "NJet/I"                        TBranch
[...]
  NPhoton                     "NPhoton/I"                     TBranch
  Photon_Px                   "Photon_Px[NPhoton]/F"          TBranch
  Photon_Py                   "Photon_Py[NPhoton]/F"          TBranch
  Photon_Pz                   "Photon_Pz[NPhoton]/F"          TBranch
  Photon_E                    "Photons_E[NPhoton]/F"          TBranch
  Photon_Iso                  "Photon_Iso[NPhoton]/F"         TBranch
[...]
```

there is a typo in the branch descriptor for `Photon_E` (which reads `Photons_E`, with an extra `s`).

not sure who's "right" here (`uproot` that presumably correctly reads that file, or `groot` that chokes on it)

**Comment by jpivarski** [comment]
This was probably a typo when creating the file, but it's not an invalid file. The branch's name is `"Photon_E"` and its title is `"Photons_E[NPhoton]/F"`. There's nothing illegal about that.

Inside of the branch, there's a name and title for each basket (only 1 in this case), and I suppose it could break something if the basket's name is different from the branch name. The basket name in this case is `"Photon_E"`, in agreement with the branch name.

The branch has one leaf, and its name is different from the branch name: `"Photons_E"` with title `"Photons_E[NPhoton]"`. If some process requires the singleton leaf name to equal the branch name, I suppose that would be a problem. But a branch can in principle have many leaves, all with different names, so I don't know why a tool would require the leaf name to be equal to the branch name.

I'll close this then.
