### ISSUE TITLE
Unspecified Branch-level Compression

### ISSUE THREAD

**Issue by AlexSchuy** [scikit-hep/uproot#90]
Hi,
We have a single-tree root file that has fCompress=1 at file-level but each branch has fCompress=-1. The file is readable by root and tools such as root_numpy but uproot throws the following error: “ValueError: unrecognized compression level: 99 (from fCompress -1)”. We can work around the issue by creating a new file with a clone of the tree, which we assume is because it sets fCompress for each branch to be the file-level fCompress. 
However, since root and root_numpy can read the original file, we think this is an issue with uproot and not with the file. We have sent an example root file by private communication. Given this file, the following code results in the error:
```uproot.open(filename)['recoTree'].arrays()```

A full traceback is available below:
```Traceback (most recent call last):
  File "varcheck.py", line 5, in <module>
    uproot.open(filename)['recoTree'].arrays()
  File "/phys/users/schuya/.local/lib/python3.4/site-packages/uproot/tree.py", line 440, in arrays
    futures = [(branch.name, interpretation, branch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=False)) for branch, interpretation in branches]
  File "/phys/users/schuya/.local/lib/python3.4/site-packages/uproot/tree.py", line 440, in <listcomp>
    futures = [(branch.name, interpretation, branch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=False)) for branch, interpretation in branches]
  File "/phys/users/schuya/.local/lib/python3.4/site-packages/uproot/tree.py", line 1240, in array
    basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
  File "/phys/users/schuya/.local/lib/python3.4/site-packages/uproot/tree.py", line 1200, in _basket_itemoffset
    for j, key in enumerate(self._threadsafe_iterate_keys(keycache, True, basketstart, basketstop)):
  File "/phys/users/schuya/.local/lib/python3.4/site-packages/uproot/tree.py", line 922, in _threadsafe_iterate_keys
    key = self._basketkey(keysource, i, complete)
  File "/phys/users/schuya/.local/lib/python3.4/site-packages/uproot/tree.py", line 1508, in _basketkey
    return self._BasketKey(source.parent(), Cursor(self.fBasketSeek[i]), uproot.source.compressed.Compression(self.fCompress), complete)
  File "/phys/users/schuya/.local/lib/python3.4/site-packages/uproot/source/compressed.py", line 48, in __init__
    raise ValueError("unrecognized compression level: {0} (from fCompress {1})".format(self.level, fCompress))
ValueError: unrecognized compression level: 99 (from fCompress -1)```

**Comment by jpivarski** [comment]
I don't have the file for testing, but this is simple enough: uproot should fall back to the file's compression parameters if a branch's compression enum is not a recognized value, following ROOT's policies for minimal surprise to users. (Thanks for reporting it!)

I've put a patch in the [issue-90-unspec-compress](https://github.com/scikit-hep/uproot/tree/issue-90-unspec-compress) branch. Could you check your file with it and see if it works now? (Checkout branch and `python setup.py install --user`...)

**Comment by AlexSchuy** [comment]
Yep, that fixed it. Thanks!

**Comment by jpivarski** [comment]
Thanks! It will be release [2.8.32](https://github.com/scikit-hep/uproot/releases/tag/2.8.32).

**Comment by gordonwatts** [comment]
Thanks!!
