### ISSUE TITLE
Support for TLorentzVector not in std::vector?

### ISSUE THREAD

**Issue by imruffin** [scikit-hep/uproot#96]
I am trying to read TLorentzVector type branches using uproot, and in tree.show() I see None as the type (and when doing tree['branchName'].array() the error is: "cannot interpret branch 'branchName' as a Python type." However, I also have a std::vector of TLorentzVectors which can be read.

After reading issue #57 I am thinking there is just not support for reading TLorentzVectors that are not in vectors. If there is a way around this issue it would be greatly appreciated!

**Comment by jpivarski** [comment]
That was added in a later version, though I don't remember which one. (pip install with a `-U`.) We explicitly tested single TLorentzVectors. Reopen this if you find that the latest version doesn't work for you— that wouldn't be a feature request, but a bug report.

**Comment by imruffin** [comment]
Hi again, I made sure I am on the latest version (2.9.2) and tree.show() still gives None for the single TLorentzVectors (but works for the vector of TLorentzVectors).

**Comment by reikdas** [comment]
Would it be possible for you to share the file that you are trying to read?

**Comment by imruffin** [comment]
Sure, I've emailed you.
